### PR TITLE
Make 3118 and 3553 usable

### LINKED ISSUE #1869: Two objects cause crash
**Describe the bug**
Crash

**To reproduce**
```lua
Object( 3118, 0, 0, 5 )
Object( 3553, 0, 0, 5 )
```

Crash offset 0x59F8B4

**Version**
Client from r20716

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #1869

This PR add collision for 3118 and 3553. Model 3118 is broken itself, but still usable with custom DFF and COL.

### CODE REVIEW

File: Client/game_sa/CGameSA.cpp [hunk 1]
```diff
@@ -814,6 +815,12 @@ void CGameSA::SetupSpecialCharacters()
     */
 }
 
+void CGameSA::SetupBrokenModels()
+{
+    ModelInfo[3118].GetInterface()->pColModel = ModelInfo[3059].GetInterface()->pColModel;
+    ModelInfo[3553].GetInterface()->pColModel = ModelInfo[3554].GetInterface()->pColModel;
```
Comment (ghost) [inline Client/game_sa/CGameSA.cpp:821]: Is the col model always loaded?

Comment (TheNormalnij) [reply Client/game_sa/CGameSA.cpp:821]: Col is preloaded for all models

**Review by ghost — APPROVED** [review]

**Comment by Allerek** [comment]
We should add 19831 too.
Barbeque model from "Misappropriation" mission.
Dev prineside says its SAMP but it was in game itself.

image

**Comment by TheNormalnij** [comment]
Can you provide more info about this model? This model is not registered in GTA SA

**Comment by TheNormalnij** [comment]
I think this is cutscene model from `cutscene.img`. You can use this model via `engineRequestModel`. You need manually find dff and txd there and add right col

**Comment by PlatinMTA** [comment]
> We should add 19831 too.
> Barbeque model from "Misappropriation" mission.
> Dev prineside says its SAMP but it was in game itself.
> 
> image

A lot of SAMPs custom models are from the base game itself, if the ID is more than 19000 then probably is just added in the IMG of SAMP.
