### PR TITLE
Fixes getTimerDetails negative remaining duration

### LINKED ISSUE #3355: getTimerDetails returns strange numbers as the remaining time inside the timer function
### Describe the bug

The ``getTimerDetails`` function returns strange numbers as the remaining time. This problem only occurs when we use getTimerDetails inside a timer function. Otherwise, it returns the correct remaining time.

image

image

### Steps to reproduce

```lua
local exampleTimer

function timerCallback()
	local remainingTime = getTimerDetails(sourceTimer)
	print('Reamining time in callback: ', remainingTime)
end
exampleTimer = setTimer(timerCallback, 1000, 10)

setTimer(function()
	local remainingTime = getTimerDetails(exampleTimer)
	print('Remaining time beyond callback: ', remainingTime)
end, 100, 10) -- 100 or 1000
```

### Version

Multi Theft Auto v1.6-release-22396

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by jjustns**
Fixes #3355

### CODE REVIEW

File: Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp [hunk 1]
```diff
@@ -68,5 +68,9 @@ CTickCount CLuaTimer::GetTimeLeft()
 {
     CTickCount llCurrentTime = CTickCount::Now();
     CTickCount llTimeLeft = m_llStartTime + m_llDelay - llCurrentTime;
+    
+    if (llTimeLeft.ToLongLong() < 0)
+        return CTickCount(0LL);
+    
     return llTimeLeft;
```
Comment (ghost) [inline Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp]: What about using the ternary operator?
We could combine the logic into a single return statement.

```suggestion
    return llTimeLeft.ToLongLong() < 0 ? CTickCount(0LL) : llTimeLeft;
```

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by ghost — APPROVED** [review]
LGTM

File: Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp [hunk 2]
```diff
@@ -68,5 +68,5 @@ CTickCount CLuaTimer::GetTimeLeft()
 {
     CTickCount llCurrentTime = CTickCount::Now();
     CTickCount llTimeLeft = m_llStartTime + m_llDelay - llCurrentTime;
-    return llTimeLeft;
+    return llTimeLeft.ToLongLong() < 0 ? CTickCount(0LL) : llTimeLeft;
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp]: `llTimeLeft.ToLongLong() < 0ll`

**Review by tederis — APPROVED** [review]
