### PR TITLE
Fix #2677: MTA does not render grass correctly

### LINKED ISSUE #2677: MTA does not render grass correctly
### MTA grass rendering:
mta-screen_2022-07-22_09-01-57
### MTA grass rendering without "HOOK_CPlantMgr_Render" in CMultiplayerSA:
mta-screen_2022-07-22_08-45-25

As you can see, there is less grass rendered in current version of MTA.

### Steps to reproduce

None

### Version

Current

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TFP-dev**
Fixes #2677

### CODE REVIEW

**Comment by lopezloo** [comment]
Wouldn't this change break rendering under water plants? If not - why not?

**Comment by TFP-dev** [comment]
> Wouldn't this change break rendering under water plants? If not - why not?

No problems with underwater plants, probably because ```watercheck:``` is untouched.

Camera above water level:
mta-screen_2022-07-26_12-14-04

Camera below water level:
mta-screen_2022-07-26_12-15-45

File: Client/multiplayer_sa/CMultiplayerSA.cpp [hunk 1]
```diff
@@ -5361,9 +5361,10 @@ void _declspec(naked) HOOK_CPlantMgr_Render()
         add esp, 8
 
 rendercheck:
-        xor eax, [esp+0x88+4]   // Decide whether or not to draw the plant right now
-        cmp eax, [esp+0x88+8]
-        jnz fail
+        // causes some foliage not generating in certain places when uncommented
+        //xor eax, [esp+0x88+4]   // Decide whether or not to draw the plant right now
+        //cmp eax, [esp+0x88+8]
+        //jnz fail
```
Comment (botder) [inline Client/multiplayer_sa/CMultiplayerSA.cpp]:
```suggestion
        // NOTE: Causes some foliage not generating in certain places when uncommented (see also: PR #2679)
        // xor eax, [esp+0x88+4]   // Decide whether or not to draw the plant right now
        // cmp eax, [esp+0x88+8]
        // jnz fail
```

**Review by botder — APPROVED** [review]
