### PR TITLE
Fix #1440 Driveby aiming is inverted in some cases

### LINKED ISSUE #1440: Driveby aiming is inverted in some cases
**Describe the bug**
When aiming left or behind in driveby, the gun pitch is inverted. When you aim down, the player points the gun up.
It only applies to the local player as MTA only syncs 1 aim rotation value for remote players in vehicles (Maybe this should be changed).

**To reproduce**
Get in a car or bike, perform driveby and point left or behind.

**Expected behaviour**
Gun should point where you aim.

**Screenshots**
image

**Version**
v1.5.7-release-20520
Bug has been in MTA for a long time

**Additional context**

### PR DESCRIPTION
**Pull request by Zangomangu**
Fixed by inverting fGunDirectionY if doing driveby and aiming left or behind.
Fixes #1440

### CODE REVIEW

**Review by qaisjp — CHANGES_REQUESTED** [review]
The nested `if`s are a bit intense - please can you use `return` where possible?

File: Client/multiplayer_sa/multiplayer_shotsync.cpp [hunk 1]
```diff
@@ -168,6 +174,16 @@ VOID WriteGunDirectionDataForPed(CPedSAInterface* pPedInterface, float* fGunDire
             // Make sure our pitch is updated (fixes first-person weapons not moving)
             *fGunDirectionY = pGameInterface->GetCamera()->Find3rdPersonQuickAimPitch();
 
+            // Are we doing driveby?
+            if (pAimingPed->IsDoingGangDriveby())
```
Comment (ghost) [inline Client/multiplayer_sa/multiplayer_shotsync.cpp]: Comments like these are not needed. They just take up space but are not helpful. `IsDoingGangDriveby` is self-explanatory.

File: Client/multiplayer_sa/multiplayer_shotsync.cpp [hunk 2]
```diff
@@ -168,6 +174,16 @@ VOID WriteGunDirectionDataForPed(CPedSAInterface* pPedInterface, float* fGunDire
...
+            {
+                // Fix pitch in driveby when facing left or backwards
+                if (LocalShotSyncData.m_cInVehicleAimDirection == 1 || LocalShotSyncData.m_cInVehicleAimDirection == 2)
+                {
+                    *fGunDirectionY = -*fGunDirectionY;
+                }
```
Comment (ghost) [inline Client/multiplayer_sa/multiplayer_shotsync.cpp]: I can see magic numbers here. It would be nice if you can define an enum in CMultiplayer.h. 

```
enum class eVehicleAimDirection : char
{
    FORWARDS = 0,
    LEFT, 
    BACKWARDS,
    RIGHT
};
```
CShotSyncData:
```
 eVehicleAimDirection m_cInVehicleAimDirection;
```

The fix:
```
switch (LocalShotSyncData.m_cInVehicleAimDirection)
{
    case eVehicleAimDirection::LEFT:
    case eVehicleAimDirection::BACKWARDS:
    *fGunDirectionY = -*fGunDirectionY;
    break;
}
```
You would also need to change a few references in multiplayer_shotsync.cpp from char to eVehicleAimDirection in multiplayer_shotsyn.cpp, CClientGame, and CClientPed. The compiler will throw errors and let you know where to change them.

File: Client/mods/deathmatch/logic/CNetAPI.cpp [hunk 3]
```diff
@@ -631,12 +631,12 @@ void CNetAPI::ReadKeysync(CClientPlayer* pPlayer, NetBitStreamInterface& BitStre
             // Set the aim data (immediately if in vehicle, otherwize delayed/interpolated)
             if (pVehicle)
             {
-                pPlayer->SetAimingData(TICK_RATE_AIM, aim.data.vecTarget, aim.data.fArm, 0.0f, ucDriveByAim, &(aim.data.vecOrigin), false);
+                pPlayer->SetAimingData(TICK_RATE_AIM, aim.data.vecTarget, aim.data.fArm, 0.0f, static_cast<EVehicleAimDirection>(ucDriveByAim), &(aim.data.vecOrigin), false);
```
Comment (ghost) [inline Client/mods/deathmatch/logic/CNetAPI.cpp]: Remove static_cast and change the type of the parameter. Using casts for enums defeats the purpose of having enums in the first place. I think only using it for bitstreams is fine or in some cases where the type of enum is different from the local variable/function parameter and changing it to enum might possibly break things.

File: Client/mods/deathmatch/logic/CNetAPI.cpp [hunk 4]
```diff
@@ -631,12 +631,12 @@ void CNetAPI::ReadKeysync(CClientPlayer* pPlayer, NetBitStreamInterface& BitStre
...
             }
             else
             {
                 pPlayer->SetTargetTarget(TICK_RATE_AIM, aim.data.vecOrigin, aim.data.vecTarget);
-                pPlayer->SetAimInterpolated(TICK_RATE_AIM, fPlayerRotation, aim.data.fArm, flags.data.bAkimboTargetUp, ucDriveByAim);
+                pPlayer->SetAimInterpolated(TICK_RATE_AIM, fPlayerRotation, aim.data.fArm, flags.data.bAkimboTargetUp, static_cast<EVehicleAimDirection>(ucDriveByAim));
             }
```
Comment (ghost) [inline Client/mods/deathmatch/logic/CNetAPI.cpp]: remove static_cast

File: Client/sdk/multiplayer/CMultiplayer.h [hunk 5]
```diff
@@ -37,6 +37,14 @@ struct SClothesCacheStats
     uint uiNumRemoved;
 };
 
+enum class EVehicleAimDirection : char
+{
```
Comment (ghost) [inline Client/sdk/multiplayer/CMultiplayer.h]: Hmm, I'm not sure why you changed the prefix to `E`. It's not consistent with the coding style. If you don't like using Hungarian notation, that's completely fine, but it's important to be consistent. I don't think we have any enums with the capital letter "E". I'd rename it to `VehicleAimDirection` or `eVehicleAimDirection`.

Comment (qaisjp) [reply Client/sdk/multiplayer/CMultiplayer.h]: image
and more


But yes there's 256 `enum e` and 58 `enum E`, so indeed we should prefer lowercase.

Comment (qaisjp) [reply Client/sdk/multiplayer/CMultiplayer.h]: Should it be `char` or `unsigned char`, though?

Comment (ghost) [reply Client/sdk/multiplayer/CMultiplayer.h]: Oh my.. 

> Should it be `char` or `unsigned char`, though?

It doesn't make any difference if the range is between 0-127

Comment (Zangomangu) [reply Client/sdk/multiplayer/CMultiplayer.h]: I looked around and the first enum I found had E. But I changed it now.

**Comment by Zangomangu** [comment]
I've tested it again after the commits.

**Review by qaisjp — APPROVED** [review]
Refactor looks good. Force pushed to keep the bugfix and the refactor in distinct commits, so that we can do a rebase-merge or a merge commit.
