### PR TITLE
Use new argument parser for generic server functions

### LINKED ISSUE #817: clearChatBox() returns false serverside if the player is root
**Describe the bug**
When using clearChatBox() or clearChatBox(root) it returns false even when the chatBox is cleared for every user. This only happens serverside.

**To reproduce**
/srun clearChatBox()

It will return false

**Expected behaviour**
It should return true.

**Version**
Client: v1.5.6-release-16183
Server: v1.5.6-release-16362

### PR DESCRIPTION
**Pull request by botder**
Fixes #817 and includes #2014

### CODE REVIEW

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 1]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+    {
+        return result;
+    }
+
+    return false;
+}
+
+bool CLuaGenericDefs::SetServerPassword(std::optional<std::string> rawPassword)
+{
+    std::string password = (rawPassword.has_value() ? std::move(rawPassword.value()) : std::string());
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:67]:
```cpp
if (!rawPassword)
    rawPassword  = std::string{};
```

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 2]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+        throw std::invalid_argument("password must be shorter than 32 chars and just contain visible characters");
+
+    return true;
+}
+
+std::variant<std::nullptr_t, std::string_view> CLuaGenericDefs::GetServerPassword()
+{
+    if (g_pGame->GetConfig()->HasPassword())
+    {
+        return std::string_view{g_pGame->GetConfig()->GetPassword()};
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:76]: `return g_pGame->GetConfig()->GetPassword()` should work implicitly.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 3]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+}
+
+unsigned int CLuaGenericDefs::GetServerHttpPort()
+{
+    return g_pGame->GetConfig()->GetHTTPPort();
+}
+
+std::string_view CLuaGenericDefs::GetServerName()
+{
+    return std::string_view{g_pGame->GetConfig()->GetServerName()};
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp]: `return g_pGame->GetConfig()->GetServerName()`

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 4]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+{
+    unsigned char colorR = 231, colorG = 217, colorB = 176;
+    bool          colorCoded = rawColorCoded.value_or(false);
+
+    if (rawColorR.has_value() && rawColorG.has_value() && rawColorB.has_value())
+    {
+        colorR = rawColorR.value();
+        colorG = rawColorG.value();
+        colorB = rawColorB.value();
+    }
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:150]: This isn't the old behavior.
```cpp
argStream.ReadNumber(ucRed, 231);
argStream.ReadNumber(ucGreen, 217);
argStream.ReadNumber(ucBlue, 176);
```
This is:
```cpp
unsigned char colorR = rawColorR.value_or(231);
unsigned char colorG = rawColorG.value_or(217);
unsigned char colorB = rawColorB.value_or(176);
```

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 5]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+    std::vector<CPlayer*> sendList;
+
+    if (!rawVisibleTo.has_value() || std::holds_alternative<CElement*>(rawVisibleTo.value()))
+    {
+        CElement* element = (rawVisibleTo.has_value() ? std::get<CElement*>(rawVisibleTo.value()) : m_pRootElement);
+
+        if (IS_TEAM(element))
+        {
+            auto team = static_cast<CTeam*>(element);
+            sendList.resize(team->CountPlayers());
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:164]: `.reserve`

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 6]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+            sendList.assign(team->PlayersBegin(), team->PlayersEnd());
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:165]: `.insert(sendList.begin(), team->PlayersBegin(), team->PlayersEnd())`

Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp]:
```cpp
sendList.reserve(team->CountPlayers());
sendList.insert(sendList.begin(), team->PlayersBegin(), team->PlayersEnd());
```
Your code default initializes with `resize`, we dont need that.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 7]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+        else
+        {
+            CLuaMain* luaMain = m_pLuaManager->GetVirtualMachine(luaVM);
+            CStaticFunctionDefinitions::OutputChatBox(message.c_str(), element, colorR, colorG, colorB, colorCoded, luaMain);
+            return true;
+        }
+    }
+    else
+    {
+        sendList = std::move(std::get<std::vector<CPlayer*>>(rawVisibleTo.value()));
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:173]: Perhaps add a `throw` here if `sendList.empty()`?

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 8]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+    return true;
+}
+
+bool CLuaGenericDefs::OutputConsole(std::string message, std::optional<CElement*> rawElement)
+{
+    CStaticFunctionDefinitions::OutputConsole(message.c_str(), rawElement.value_or(m_pRootElement));
+    return true;
+}
+
+bool CLuaGenericDefs::OutputChatBox(lua_State* luaVM, std::string message, std::optional<std::variant<CElement*, std::vector<CPlayer*>>> rawVisibleTo,
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:138]: Let's use `std::string_view` here. Lua's string are always null terminated. What do you think?

**Comment by Pirulax** [comment]
Thanks tho, nice refactor.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 3 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp]:
```suggestion
    return g_pGame->GetConfig()->GetServerName();
```
Converted to a suggestion, so I can apply it directly.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 2 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:76]: I would rather keep it explicit, because the return type is actually a variant in this case.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 8 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:138]: I might be wrong, but string-convertible values won't work with `std::string_view` - needs testing.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 4 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:150]: It actually is the old behavior, because the colors are only used, if all three are available:
https://github.com/multitheftauto/mtasa-blue/blob/7b79541e8d9750ca0156e0f4ac4752e9ae4831e7/Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp#L68-L75

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 6 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp]:
```suggestion
            sendList.reserve(team->CountPlayers());
            sendList.insert(sendList.begin(), team->PlayersBegin(), team->PlayersEnd());
```
Converted to suggestion block :)

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 7 above)
Comment (botder) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:173]: We could, but ReadUserDataTable (old behavior) wouldn't show a warning in such case.

**Review by patrikjuvonen — APPROVED** [review]

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 2 above)
Comment (Pirulax) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:76]: It'll work no problem.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 8 above)
Comment (Pirulax) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:138]: What do you mean?
Tbh, not worth the effort, keep it like this. The performance penality is really minimal.

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp [hunk 9]
```diff
@@ -26,3 +38,153 @@ bool CLuaGenericDefs::IsTransferBoxVisible()
...
+    return false;
+}
+
+bool CLuaGenericDefs::SetServerPassword(std::optional<std::string> rawPassword)
+{
+    std::string password = (rawPassword.has_value() ? std::move(rawPassword.value()) : std::string());
+
+    if (!CStaticFunctionDefinitions::SetServerPassword(password, true))
+        throw std::invalid_argument("password must be shorter than 32 chars and just contain visible characters");
+
```
Comment (Pirulax) [inline Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp]:
```suggestion
if (!CStaticFunctionDefinitions::SetServerPassword(rawPassword.value_or(""), true))
    throw std::invalid_argument("password must be shorter than 32 chars and just contain visible characters");
```

File: Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp (hunk 4 above)
Comment (Pirulax) [reply Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp:150]: My bad then, sorry.
