### PR TITLE
Fix #2963: Add support for double click events in CEF

### LINKED ISSUE #2963: CEF : jquery dblclick event not working
### Describe the bug

hi, the double click event is not working, everything is ok in external browser but the event is not getting called inside mta cef.

the event : https://api.jquery.com/dblclick/

### Steps to reproduce

use dblclick event, example code:
```
$("#an_element").dblclick(function() {
        $(this).hide();
});
```

### Version

client: Multi Theft Auto v1.5.9-release-21630 - windows 10, 64bit
server: MTA:SA Server v1.5.9-release-21476 - windows 10, 64bit

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by Lpsd**
Resolves #2963

As mentioned in the issue description above, double click events previously weren't being sent to CEF.

Test resource: 
[cef.zip](https://github.com/multitheftauto/mtasa-blue/files/11559836/cef.zip)

Usage: start the resource & click your mouse. a status (`single` or `double` click) will be displayed on the browser page, as well as in the console

### CODE REVIEW

**Comment by lopezloo** [comment]
I think we shouldn't test such things with jQuery. I have modified your script to do not use jQuery and also handle `mousedown` and `mousedown` events:
<details>
  <summary>index.html</summary>

```html
<html>
    <head>
        <title>CEF Test</title>
    </head>
    <style>
        div {
            width: 100%; 
            color: #ccc; 
            margin-top: 10vh; 
            text-align: center; 
            font-size: 30px
        }
    </style>
    <body style="background: #222;">
        <div>Click anywhere</div>
        <div class="output" style="color: rgb(184, 49, 49); margin-top: 25px;"></div>

        <script>
            function log(message) {
                console.log(message);
                document.querySelector('.output').innerHTML += '<br>' + message;
            }

            addEventListener("mousedown", (event) => {
                log("mousedown @" + new Date().getTime());
            });

            addEventListener("mouseup", (event) => {
                log("mouseup @" + new Date().getTime());
            });

            addEventListener("dblclick", (event) => {
                log("double click @" + new Date().getTime());
            });

            addEventListener("click", (event) => {
                log("click @" + new Date().getTime());
            });
        </script>
    </body>
</html>

```
</details>

**Comment by lopezloo** [comment]
Tested and it works but I don't understand why Chromium can't handle it by own?

From https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event:
> dblclick fires after two [click](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) events (and by extension, after two pairs of [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) and [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) events).

Possibly because because it doesn't fire mousedown for next click? This is what double clicking prints on master:

```
mousedown @1685127605133
mouseup @1685127605179
click @1685127605179
mouseup @1685127605278
```

This is what slow double clicking prints (on master):
```
mousedown @1685127891780
mouseup @1685127891887
click @1685127891888
mousedown @1685127892265
mouseup @1685127892368
click @1685127892368
```

This is what Chrome prints when fast double clicking:
```
mousedown @1685127953616
mouseup @1685127953662
click @1685127953662
mousedown @1685127953697
mouseup @1685127953758
click @1685127953758
double click @1685127953758
```

**Comment by Lpsd** [comment]
Can you review your comments above please @lopezloo as I'm fairly certain this PR fixes the issue in the correct way, and is working as intended, as discussed on Discord: https://discord.com/channels/801330706252038164/801411628600000522/1111735006142939136

**Comment by lopezloo** [comment]
> Can you review your comments above please @lopezloo as I'm fairly certain this PR fixes the issue in the correct way, and is working as intended, as discussed on Discord: https://discord.com/channels/801330706252038164/801411628600000522/1111735006142939136

It works but it still looks strange to me that the `CEGUI::Window::EventMouseButtonDown` event is not being called on double click. Looks like CEGUI thing not really related to this issue. I thought if it would be called then it would be interpreted as double click by Chromium but have tested it and that's not the case so your approach is correct.

File: Client/cefweb/CWebView.h [hunk 1]
```diff
@@ -80,7 +80,7 @@ class CWebView : public CWebViewInterface,
     bool GetProperty(const SString& strKey, SString& outProperty);
 
     void InjectMouseMove(int iPosX, int iPosY);
-    void InjectMouseDown(eWebBrowserMouseButton mouseButton);
+    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1);
```
Comment (botder) [inline Client/cefweb/CWebView.h]:
```suggestion
    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count);
```

File: Client/mods/deathmatch/logic/CClientWebBrowser.h [hunk 2]
```diff
@@ -40,7 +40,7 @@ class CClientWebBrowser : public CClientTexture, public CWebBrowserEventsInterfa
     bool GetProperty(const SString& strKey, SString& outValue);
 
     void InjectMouseMove(int iPosX, int iPosY);
-    void InjectMouseDown(eWebBrowserMouseButton mouseButton);
+    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1);
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientWebBrowser.h]:
```suggestion
    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count);
```

File: Client/sdk/core/CWebViewInterface.h [hunk 3]
```diff
@@ -36,7 +36,7 @@ class CWebViewInterface
     virtual bool GetProperty(const SString& strKey, SString& outProperty) = 0;
 
     virtual void InjectMouseMove(int iPosX, int iPosY) = 0;
-    virtual void InjectMouseDown(eWebBrowserMouseButton mouseButton) = 0;
+    virtual void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1) = 0;
```
Comment (botder) [inline Client/sdk/core/CWebViewInterface.h]:
```suggestion
    virtual void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count) = 0;
```

**Review by botder — CHANGES_REQUESTED** [review]
Is the default value necessary? From what I see you never rely on it.

**Review by botder — DISMISSED** [review]
