### PR TITLE
Refactor dxDrawCircle to use primitives queue, fix it's postGui issues

### LINKED ISSUE #432: dxDrawCircle: Not rendered at all if postGUI is enabled
**Describe the bug**
If `postGUI` is set to `true`, circles are not rendered at all.

**To Reproduce**
```lua
addEventHandler("onClientRender", root,
    function()
        dxDrawCircle(150, 150, 100, 0, 360, tocolor(255, 255, 255), tocolor(255, 255, 255), 32, 1, true)
    end
)
```

**Expected behavior**
I expect a circle to be rendered

**MTA Client (please complete the following information):**
 - Version: 1.5.6
 - Running in Wine? No

**Additional context**
Maybe it's somehow related to #431

### PR DESCRIPTION
**Pull request by forkerer**
Fixes #432, #431.

As the title suggest, this pull request forces dxDrawCircle to use primitives drawing, and fixes it's postGui issues. It also includes a bit of general code cleanup and removal of unnecessary vertices creation. I tried to test most of the common scenarios with that, and couldn't find any issues.

### CODE REVIEW

File: Client/core/Graphics/CGraphics.cpp [hunk 1]
```diff
@@ -824,25 +824,32 @@ void CGraphics::DrawRectQueued(float fX, float fY, float fWidth, float fHeight,
...
-    Item.Circle.fRatio = fRatio;
-    Item.Circle.ulColor = ulColor;
-    Item.Circle.ulColorCenter = ulColorCenter;
-    // Add it to the queue
-    AddQueueItem(Item, bPostGUI);
+    auto pVecVertices = new std::vector<PrimitiveVertice>();
+    fStartAngle = D3DXToRadian(fStartAngle);
+    fStopAngle = D3DXToRadian(fStopAngle);
+    // Calculate each segment angle
+    const float kfSegmentAngle = (fStopAngle - fStartAngle) / (siSegments-1);
```
Comment (ghost) [inline Client/core/Graphics/CGraphics.cpp:835]: I remember removing `-1` in `(siSegments-1)`, and it worked without any issues. Any reason for adding it back?

**Review by ghost — COMMENTED** [review]
Good job.

File: Client/core/Graphics/CGraphics.cpp (hunk 1 above)
Comment (forkerer) [reply Client/core/Graphics/CGraphics.cpp:835]: Instead of floating point based loop, i made it to use exactly the amount of segments specified in dxDrawCircle call, that required adding ```-1``` again

**Comment by ccw808** [comment]
Thank you
