### PR TITLE
Fix #1292: return vector3 instead of number at ped's target

### LINKED ISSUE #1292: getPedTargetStart/End returns single value in OOP
**Describe the bug**

individual number is returned instead of a vector3

**To reproduce**

```
Executing client-side command: me.targetStart
Command results: -1402.6716308594 [number]
Executing client-side command: me.targetEnd
Command results: -1409.7946777344 [number]
```

**Expected behaviour**

vector3 should be returned

**Screenshots**

n/a

**Version**

latest master 1.5.7 (250053a)

**Additional context**

### PR DESCRIPTION
**Pull request by ecastro98**
Fix #1292

### CODE REVIEW

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp [hunk 1]
```diff
@@ -637,6 +637,27 @@ int CLuaPedDefs::GetPedTargetStart(lua_State* luaVM)
     return 1;
 }
 
+int CLuaPedDefs::OOP_GetPedTargetStart(lua_State* luaVM)
+{
+    CClientPed*      pPed = NULL;
```
Comment (StrixG) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: Please use `nullptr` instead of `NULL`

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp [hunk 2]
```diff
@@ -206,9 +206,9 @@ void CLuaPedDefs::AddClass(lua_State* luaVM)
     lua_classvariable(luaVM, "dead", NULL, "isPedDead");
     lua_classvariable(luaVM, "targetingMarker", "setPedTargetingMarkerEnabled", "isPedTargetingMarkerEnabled");
     lua_classvariable(luaVM, "footBlood", "setPedFootBloodEnabled", NULL);
-    lua_classvariable(luaVM, "targetCollision", NULL, "getPedTargetCollision");
-    lua_classvariable(luaVM, "targetEnd", NULL, "getPedTargetEnd");
-    lua_classvariable(luaVM, "targetStart", NULL, "getPedTargetStart");
+    lua_classvariable(luaVM, "targetCollision", NULL, OOP_GetPedTargetCollision);
+    lua_classvariable(luaVM, "targetEnd", NULL, OOP_GetPedTargetEnd);
+    lua_classvariable(luaVM, "targetStart", NULL, OOP_GetPedTargetStart);
```
Comment (StrixG) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]:
```suggestion
    lua_classvariable(luaVM, "targetCollision", nullptr, OOP_GetPedTargetCollision);
    lua_classvariable(luaVM, "targetEnd", nullptr, OOP_GetPedTargetEnd);
    lua_classvariable(luaVM, "targetStart", nullptr, OOP_GetPedTargetStart);
```

**Comment by qaisjp** [comment]
maybe use the new arg parser? 

see https://github.com/multitheftauto/mtasa-blue/blob/a7b752f8154cafc94dc7de1a9d9c5fd2e28e4f8b/Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp#L17 but instead of `ArgumentParserWarn<false, fn>`, I think it's `ArgumentParser<fn>`

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp [hunk 3]
```diff
@@ -637,18 +637,39 @@ int CLuaPedDefs::GetPedTargetStart(lua_State* luaVM)
...
+    if (!argStream.HasErrors())
+    {
+        CVector vecStart;
+        pPed->GetShotData(&vecStart);
+
+        lua_pushvector(luaVM, vecStart);
+        return 1;
+    }
+    else
+        m_pScriptDebugging->LogCustom(luaVM, argStream.GetFullErrorMessage());
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: should be an error rather than warning

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp [hunk 4]
```diff
@@ -663,10 +684,31 @@ int CLuaPedDefs::GetPedTargetEnd(lua_State* luaVM)
...
+    if (!argStream.HasErrors())
+    {
+        CVector vecEnd;
+        pPed->GetShotData(nullptr, &vecEnd);
+
+        lua_pushvector(luaVM, vecEnd);
+        return 1;
+    }
+    else
+        m_pScriptDebugging->LogCustom(luaVM, argStream.GetFullErrorMessage());
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: here 2

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp [hunk 5]
```diff
@@ -690,6 +732,28 @@ int CLuaPedDefs::GetPedTargetCollision(lua_State* luaVM)
...
+    {
+        CVector vecCollision;
+        if (CStaticFunctionDefinitions::GetPedTargetCollision(*pPed, vecCollision))
+        {
+            lua_pushvector(luaVM, vecCollision);
+            return 1;
+        }
+    }
+    else
+        m_pScriptDebugging->LogCustom(luaVM, argStream.GetFullErrorMessage());
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: & here

**Review by qaisjp — CHANGES_REQUESTED** [review]

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp (hunk 3 above)
Comment (ecastro98) [reply Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: What do you mean? All the `else` path for argStream errors that I saw so far are logging like this 🤔

Comment (qaisjp) [reply Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp]: new functions should throw errors rather than log warnings - https://github.com/multitheftauto/mtasa-blue/blob/b9d509a6855c285df9439016604782bea1ae8440/Shared/mods/deathmatch/logic/luadefs/CLuaXMLDefs.cpp#L227

**Review by qaisjp — APPROVED** [review]
Thanks

**Review by StrixG — APPROVED** [review]
