### PR TITLE
Fix #467 Ped animations don't sync for new players

### LINKED ISSUE #467: Ped animations don't sync for new players
**Bug**
The ped animations don't sync for new players, it gets reseted for them.
For players that remain in the server the animation remain there.

**How to reproduce**
(only server-side)
1. create a ped
2. set an animation for the ped
3. reconnect and the ped will have no animation set

**Example image**

mta-screen_2018-09-15_13-58-39

### PR DESCRIPTION
**Pull request by FileEX**
Fixed #467

### CODE REVIEW

**Comment by Dutchman101** [comment]
Awesome! Hope this gets a bunch of code reviews..

File: Server/mods/deathmatch/logic/CPed.h [hunk 1]
```diff
@@ -316,6 +355,7 @@ class CPed : public CElement
     bool                                 m_bFrozen;
     bool                                 m_bStealthAiming;
     CVehicle*                            m_pJackingVehicle;
+    SPlayerAnimData                      m_pAnimData;
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CPed.h]: It's not a pointer. Should be `m_AnimData`.

File: Server/mods/deathmatch/logic/CPed.h [hunk 2]
```diff
@@ -278,6 +314,9 @@ class CPed : public CElement
     std::vector<CPlayer*>::const_iterator NearPlayersIterBegin() { return m_nearPlayersList.begin(); }
     std::vector<CPlayer*>::const_iterator NearPlayersIterEnd() { return m_nearPlayersList.end(); }
 
+    const SPlayerAnimData& GetAnimationData() const noexcept { return m_pAnimData; };
+    void                   SetAnimationData(SPlayerAnimData animData) noexcept { m_pAnimData = animData; };
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CPed.h]: `const SPlayerAnimData& animData` or `m_pAnimData = std::move(animData)` (with the corresponding changes within `SPlayerAnimData`).

File: Server/mods/deathmatch/logic/CPed.h [hunk 3]
```diff
@@ -103,6 +103,42 @@ enum eBone
...
+    bool        updatePosition;
+    bool        interruptable;
+    bool        freezeLastFrame;
+    int         blendTime;
+    bool        taskToBeRestoredOnAnimEnd;
+
+    SPlayerAnimData()
+        : blockName(""),
+          animName(""),
+          time(-1),
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CPed.h]: Please, use default member initialization instead of the member initializer list. I mean `bool loop{true};`, for example.

**Review by tederis — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/CPed.h [hunk 4]
```diff
@@ -103,6 +103,33 @@ enum eBone
     BONE_RIGHTFOOT
 };
 
+struct SPlayerAnimData
+{
+    std::string blockName{""};
+    std::string animName{""};
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CPed.h]: Initialization by C-string isn't necessary here.

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp [hunk 5]
```diff
@@ -959,6 +959,25 @@ bool CEntityAddPacket::Write(NetBitStreamInterface& BitStream) const
                         BitStream.Write(currentWeaponSlot);
                     }
 
+                    // Aniamtion
```
Comment (tederis) [inline Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: A typo

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp [hunk 6]
```diff
@@ -959,6 +959,25 @@ bool CEntityAddPacket::Write(NetBitStreamInterface& BitStream) const
...
+                    if (BitStream.Can(eBitStreamVersion::AnimationsSync))
+                    {
+                        const SPlayerAnimData& animData = pPed->GetAnimationData();
+
+                        if (!animData.blockName.empty() && !animData.animName.empty())
+                        {
+                            BitStream.WriteString(animData.blockName);
```
Comment (tederis) [inline Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp:991]: You have to write a **bit** that signalling whether this packet contains animation data or not.

**Review by tederis — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp (hunk 6 above)
Comment (FileEX) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp:991]: What is the difference in this case?

Comment (tederis) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp:991]: Because you have a packet corruption now.

Comment (FileEX) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp:991]: I understand, the idea is that later data will be incorrect due to "holes" when reading?

Comment (tederis) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp:991]: Yes, without that **bit** a client doesn't know what exactly is written inside a packet. Because a string itself doesn't contain sufficient information. You should explicitly mark it.

File: Server/mods/deathmatch/logic/CPed.h [hunk 7]
```diff
@@ -278,6 +305,9 @@ class CPed : public CElement
     std::vector<CPlayer*>::const_iterator NearPlayersIterBegin() { return m_nearPlayersList.begin(); }
     std::vector<CPlayer*>::const_iterator NearPlayersIterEnd() { return m_nearPlayersList.end(); }
 
+    const SPlayerAnimData& GetAnimationData() const noexcept { return m_animData; };
+    void                   SetAnimationData(const SPlayerAnimData& animData) noexcept { m_animData = animData; };
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CPed.h]: One more thing. This method can potentially throw bad_alloc exception. I would not mark it as noexcept.

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp [hunk 8]
```diff
@@ -959,6 +959,25 @@ bool CEntityAddPacket::Write(NetBitStreamInterface& BitStream) const
...
 
+                    // Animation
+                    if (BitStream.Can(eBitStreamVersion::AnimationsSync))
+                    {
+                        const SPlayerAnimData& animData = pPed->GetAnimationData();
+
+                        // Contains animation data?
+                        BitStream.WriteBit(!animData.blockName.empty() && !animData.animName.empty());
+
+                        BitStream.WriteString(animData.blockName);
```
Comment (tederis) [inline Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: You forgot a condition here. You can see that a client doesn't expect the data if a bit is set to zero.

**Comment by tederis** [comment]
Good job. But there's a problem. Animations can be interrupted on a client and that information won't be available for a server. This will break the animation consistency and lead to a desync for just joined new players. There have to be a mechanism for an animation's data invalidation.

**Comment by FileEX** [comment]
I introduced an animation validation mechanism. It supports:

- Interrupted animation on the client side (damage, explosion, death, etc.).

- Animation time has ended

- Animation was overwritten/changed by setPedAnimation on the client side

- Animation was killed by setPedAnimationProgress

I tested it on a local server with peds and the tests were successful.

**Review by Fernando-A-Rocha — APPROVED** [review]
Congratulations

File: Client/mods/deathmatch/logic/CClientPed.h [hunk 9]
```diff
@@ -788,4 +790,7 @@ class CClientPed : public CClientStreamElement, public CAntiCheatModule
     CClientPed*   m_pGettingJackedBy;                    // The ped that is jacking us
 
     std::shared_ptr<CClientModel> m_clientModel;
+
+    bool m_hasSyncedAnim;
+    bool m_animationOverridedByClient;
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientPed.h]: You should zero-initialize these member fields.
```suggestion
    bool m_hasSyncedAnim{};
    bool m_animationOverridedByClient{};
```

File: Client/mods/deathmatch/logic/CClientPed.h [hunk 10]
```diff
@@ -553,6 +553,8 @@ class CClientPed : public CClientStreamElement, public CAntiCheatModule
 
     std::unique_ptr<CAnimBlendAssociation> GetAnimAssociation(CAnimBlendHierarchySAInterface* pHierarchyInterface);
 
+    void SetHasSyncedAnim(bool synced) noexcept { m_hasSyncedAnim = synced; };
+    bool HasSyncedAnim() const noexcept { return m_hasSyncedAnim; };
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientPed.h]: Removed the semicolon after the last brace.
```suggestion
    void SetHasSyncedAnim(bool synced) noexcept { m_hasSyncedAnim = synced; }
    bool HasSyncedAnim() const noexcept { return m_hasSyncedAnim; }
```

File: Shared/sdk/net/bitstream.h [hunk 11]
```diff
@@ -556,6 +556,10 @@ enum class eBitStreamVersion : unsigned short
     // 2024-06-16
     PedSync_Revision,
 
+    // Ped animations synchronization
+    // 2024-06-29
+    AnimationsSync,
+
```
Comment (botder) [inline Shared/sdk/net/bitstream.h]: You have to move this to the end of the list before merge.

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp [hunk 12]
```diff
@@ -978,6 +978,42 @@ bool CEntityAddPacket::Write(NetBitStreamInterface& BitStream) const
                         BitStream.Write(currentWeaponSlot);
                     }
 
+                    // Animation
+                    if (BitStream.Can(eBitStreamVersion::AnimationsSync))
+                    {
+                        const SPlayerAnimData& animData = pPed->GetAnimationData();
+
+                        // Contains animation data?
+                        bool animRunning = !animData.blockName.empty() && !animData.animName.empty();
```
Comment (botder) [inline Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: Nit-picking here, but you could move this decision logic, whether an animation is running or not, to the SPlayerAnimData class: `animData.IsAnimating()`

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp [hunk 13]
```diff
@@ -978,6 +978,42 @@ bool CEntityAddPacket::Write(NetBitStreamInterface& BitStream) const
...
+
+                        // Is animation still running?
+                        float deltaTime = GetTickCount64_() - animData.startedTick;
+                        if (!animData.freezeLastFrame && animData.time > 0 && deltaTime >= animData.time)
+                        {
+                            animRunning = false;
+                            pPed->SetAnimationData({});
```
Comment (botder) [inline Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: A little bit strange to manipulate the ped's state here in the packet writing function.

File: Server/mods/deathmatch/logic/CPed.h [hunk 14]
```diff
@@ -103,6 +103,41 @@ enum eBone
...
+          time(time),
+          loop(loop),
+          updatePosition(updatePos),
+          interruptable(interrupt),
+          freezeLastFrame(freeze),
+          blendTime(blend),
+          taskToBeRestoredOnAnimEnd(taskRestore),
+          startedTick(tick),
+          progress(0.0f),
+          speed(1.0f){};
```
Comment (botder) [inline Server/mods/deathmatch/logic/CPed.h]: Just terrible to whoever is going to read the code in the future. Remove this constructor and assign the fields directly. You also don't have to assign `progress` and `speed` with the same value.

**Review by botder — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp (hunk 13 above)
Comment (FileEX) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: Would ``CPedSync::DoPulse`` be the appropriate place?

Comment (botder) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: I don't know enough to judge that, if you think it's a good spot then use it. I only have an issue with it when it happens in the packet writing logic.

Comment (FileEX) [reply Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp]: Done and tested

**Review by botder — DISMISSED** [review]

**Review by botder — APPROVED** [review]
