### PR TITLE
Keep console position and size when changing locale

### LINKED ISSUE #1969: Console (F8) set its position when changing MTA:SA language on menu
**Describe the bug**
As the title says, when you change the language, Console is moved to another position and also resized.

**To reproduce**
• Open your MTA;
• Press F8 and adjust the console the way you like (positioning and resizing);
• Change your MTA's language on menus;
• Check your console.

**Expected behaviour**
It should be in the same position and size that you have defined.

**Screenshots**
None

**Version**
Newest

**Additional context**
None

### PR DESCRIPTION
**Pull request by xLuxy**
This PR fixes #1969 by re-applying position and size when language is changed.

### CODE REVIEW

File: Client/core/CGUI.cpp [hunk 1]
```diff
@@ -237,7 +249,7 @@ void CLocalGUI::DoPulse()
                 m_LastSettingsRevision = cvars->GetRevision() - 1;
 
                 if (m_LocaleChangeCounter == 2)
-                    CCore::GetSingleton().ShowMessageBox(_E("CC99"), ("PLEASE WAIT...................."), MB_ICON_INFO);
+                    CCore::GetSingleton().ShowMessageBox(_E("CC99"), ("Changing Language, please wait..."), MB_ICON_INFO);
```
Comment (patrikjuvonen) [inline Client/core/CGUI.cpp]: nit: 
```suggestion
                    CCore::GetSingleton().ShowMessageBox(_E("CC99"), ("Changing language, please wait..."), MB_ICON_INFO);
```

**Review by patrikjuvonen — CHANGES_REQUESTED** [review]

**Comment by xLuxy** [comment]
done

**Review by patrikjuvonen — APPROVED** [review]
Thanks for the PR and change, looks good and light-tested working.
