### PR TITLE
Fixes #3655 - prevent duplicate command registration

### LINKED ISSUE #3655: addCommandHandler should disallow to create commands with duplicated names
### Describe the bug

As in title.

### Steps to reproduce

addCommandHandler("foo", function()end)
addCommandHandler("foo", function()end) -- command is added but it should not, error should be printed

iprint(getCommandHandlers()) -- prints two above commands, commands are registered

### Version

/

### Additional context

It mostly for security reasons as bad actor can create command with duplicated name to avoid detection. It for example can happen in polish gamemode "pystories" where certain commands such a "admins" are excluded from logs. Because often owners of such servers are not aware of danger and they have not trusted resources someone can create mailicious command with the same name to do not raise suspicious.

It is not only good anticheat that provide protection for servers, but also good api that prevent weird behaviours.

I know this is breaking change, but it is very easy to update resources.

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by MohabCodeX**
Fixes #3655 
Edit : read comments for more updated info

This PR makes addCommandHandler reject any duplicate command names whether they're in the same resource or across different ones. So if a command like "test" is already registered in one resource, trying to register it again (even in the same resource) will fail with a warning in debugscript 3. For example, if Resource A registers "kick", Resource B (or even A again) won’t be able to override it. It's a solid security improvement that ensures predictable command behavior and prevents hijacking or conflicts with minimal changes.
⚠️ Heads up: any existing resources with duplicate commands will now fail to register them so devs may need to audit and rename conflicting ones.
image

### CODE REVIEW

File: Server/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 1]
```diff
@@ -35,9 +37,15 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
     assert(pLuaMain);
     assert(szKey);
 
+    if (CommandExists(szKey, NULL))
+    {
+        m_pScriptDebugging->LogWarning(pLuaMain->GetVM(), "addCommandHandler: Attempt to register duplicate command '%s'", szKey);
+        return false;
+    }
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CRegisteredCommands.cpp]: Use `g_pGame->GetScriptDebugging`

File: Client/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 2]
```diff
@@ -27,6 +28,12 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
     assert(pLuaMain);
     assert(szKey);
 
+    if (CommandExists(szKey, NULL))
+    {
+        CLuaDefs::m_pScriptDebugging->LogWarning(pLuaMain->GetVM(), "addCommandHandler: Attempt to register duplicate command '%s'", szKey);
+        return false;
+    }
+
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CRegisteredCommands.cpp]: Use 
```cpp
g_pClientGame->GetScriptDebugging()->LogWarning(pLuaMain->GetVM(), "addCommandHandler: Attempt to register duplicate command '%s'", szKey);
```

**Review by FileEX — CHANGES_REQUESTED** [review]

**Comment by ffsPLASMA** [comment]
I am against this PR, there are valid reasons to bind multiple functions to a single command.

**Comment by MegadreamsBE** [comment]
> I am against this PR, there are valid reasons to bind multiple functions to a single command.

Should be configurable at the very least

**Comment by MohabCodeX** [comment]
I agree that sometimes multiple functions may need to be bound to the same command, but this can be handled better by combining them inside a single handler instead of registering several handlers for the same command which is bad practice in most cases.

Making this configurable per server is a good idea, and I can adjust the PR to support that. 
Also, something like this should at least have a warning when duplicate handlers are added I know it's a breaking change if it refused the duplicated commands, but the warning would be important for catching accidental duplications.

Thanks for the feedback, I’ll make improvements.

**Comment by Fernando-A-Rocha** [comment]
Please make it configurable as this is trying to solve a problem that doesn't exist, imo.

I used to have a chatbox resource that, if I remember correctly, made use of multiple command handlers per command. Also there are cases in which you want the same command to be handled clientside and also serverside (idk if this PR considers this).

**Comment by Fernando-A-Rocha** [comment]
A warning on duplicate command handlers could be useful, I agree.
The config could be:
<allow_multi_command_handlers>
Values: 0, 1, 2
Where 0 is disallow, 1 is allow but with warning, and 2 is allow but no warnings.

**Comment by MohabCodeX** [comment]
Thank you for all the feedback

---

### ✅ **Final Outcome: Configurable Duplicate Command Handler Behavior**

A new server configuration option has been added:

```xml
<allow_multi_command_handlers>1</allow_multi_command_handlers>
```

This option controls how the system handles multiple `addCommandHandler` registrations for the same command.


###  **Available Levels:**

| Value           | Behavior                                  | Debug Output                                                                                      |
| --------------- | ----------------------------------------- | ------------------------------------------------------------------------------------------------- |
| `0`             | ❌ **Disallow** duplicate command handlers | `addCommandHandler: Duplicate command registration blocked for '%s' (multiple handlers disabled)` |
| `1` *(default)* | ⚠️ **Allow with warning**                 | `addCommandHandler: Attempt to register duplicate command '%s'`                                   |
| `2`             | ✅ **Allow silently**                      | *(No debug output)*                                                                               |


###  **Default Behavior:**

* The default value is **`1`**, which **allows** duplicates but emits a **warning**, helping developers identify unexpected duplicate registrations.

Any other feedback would be appreciated.

**Comment by Fernando-A-Rocha** [comment]
Nice
When blocking duplicate command handlers I think it should throw a Lua error instead of a warning

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 3]
```diff
@@ -120,6 +120,7 @@ CClientGame::CClientGame(bool bLocalPlay) : m_ServerInfo(new CServerInfo())
 
     m_bCursorEventsEnabled = false;
     m_bInitiallyFadedOut = true;
+    m_eAllowMultiCommandHandlers = MULTI_COMMAND_ENABLED;
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientGame.cpp]: We no longer use Hungarian notation (not even for enums).

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 4]
```diff
@@ -6137,6 +6138,16 @@ bool CClientGame::GetBirdsEnabled()
...
 
+void CClientGame::SetAllowMultiCommandHandlers(CClientGame::eMultiCommandHandlerPolicy policy)
+{
+    m_eAllowMultiCommandHandlers = policy;
+}
+
+CClientGame::eMultiCommandHandlerPolicy CClientGame::GetAllowMultiCommandHandlers() const
+{
+    return m_eAllowMultiCommandHandlers;
+}
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientGame.cpp]: This can be moved to the header and marked as noexcept

File: Client/mods/deathmatch/logic/CClientGame.h [hunk 5]
```diff
@@ -192,6 +192,12 @@ class CClientGame
         QUIT_CONNECTION_DESYNC,
         QUIT_TIMEOUT,
     };
+    
+    enum eMultiCommandHandlerPolicy
+    {
+        MULTI_COMMAND_DISABLED = 0,
+        MULTI_COMMAND_ENABLED = 1
+    };
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientGame.h]: What do you think about enum class?

File: Client/mods/deathmatch/logic/CPacketHandler.cpp [hunk 6]
```diff
@@ -5567,6 +5575,10 @@ void CPacketHandler::Packet_SyncSettings(NetBitStreamInterface& bitStream)
     if (bitStream.Can(eBitStreamVersion::ShotgunDamageFix))
         bitStream.Read(ucAllowShotgunDamageFix);
 
+    uchar ucAllowMultiCommandHandlers = 1;
+    bitStream.Read(ucAllowMultiCommandHandlers);
+    g_pClientGame->SetAllowMultiCommandHandlers(static_cast<CClientGame::eMultiCommandHandlerPolicy>(ucAllowMultiCommandHandlers));
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CPacketHandler.cpp]: ou need to use BitStream.Can to check whether the client/server is capable of handling this functionality. If a newer client connects to an older server build, it will try to read non-existent data, which may result in a crash or a protocol error

File: Client/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 7]
```diff
@@ -27,6 +28,23 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
     assert(pLuaMain);
     assert(szKey);
 
+    if (CommandExists(szKey, NULL))
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CRegisteredCommands.cpp]: nullptr

File: Client/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 8]
```diff
@@ -27,6 +28,23 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
...
+        if (allowMultiHandlers == CClientGame::MULTI_COMMAND_DISABLED)
+        {
+            g_pClientGame->GetScriptDebugging()->LogWarning(pLuaMain->GetVM(), "addCommandHandler: Duplicate command registration blocked for '%s' (multiple handlers disabled)", szKey);
+            return false;
+        }
+        // If allowing with warning (default), log warning and proceed
+        else if (allowMultiHandlers == CClientGame::MULTI_COMMAND_ENABLED)
+        {
+            g_pClientGame->GetScriptDebugging()->LogWarning(pLuaMain->GetVM(), "addCommandHandler: Attempt to register duplicate command '%s'", szKey);
+        }
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CRegisteredCommands.cpp]: You **can** remove braces (but don't have to)

File: Server/mods/deathmatch/logic/CMainConfig.h [hunk 9]
```diff
@@ -150,6 +150,7 @@ class CMainConfig : public CXMLConfig
 
     int GetPlayerTriggeredEventInterval() const { return m_iPlayerTriggeredEventIntervalMs; }
     int GetMaxPlayerTriggeredEventsPerInterval() const { return m_iMaxPlayerTriggeredEventsPerInterval; }
+    int GetAllowMultiCommandHandlers() const { return m_iAllowMultiCommandHandlers; }
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CMainConfig.h]: noexcept & hungarian notation

File: Server/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 10]
```diff
@@ -35,11 +38,28 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
     assert(pLuaMain);
     assert(szKey);
 
+    if (CommandExists(szKey, NULL))
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CRegisteredCommands.cpp]: nullptr

File: Server/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 11]
```diff
@@ -35,11 +38,28 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
...
+        if (iAllowMultiCommandHandlers == 0)
+        {
+            // Block silently
+            return false;
+        }
+        else if (iAllowMultiCommandHandlers == 1)
+        {
+            // Allow with warning (default behavior)
+            g_pGame->GetScriptDebugging()->LogWarning(pLuaMain->GetVM(), "Attempt to register duplicate command '%s'", szKey);
+        }
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CRegisteredCommands.cpp]: You can remove braces

File: Server/mods/deathmatch/mtaserver.conf [hunk 12]
```diff
@@ -94,6 +94,11 @@
          Available values: special detection (SD) codes ; (e.g. To enable special detection #15 use: 15) -->
     <enablesd></enablesd>
 
+    <!-- This parameter controls how duplicate command handlers are handled.
+         Some resources may need to register multiple handlers for the same command.
+         Values: 0 - disallow duplicate handlers, 1 - allow with warning, 2 - allow silently ; default value: 1 -->
+    <allow_multi_command_handlers>1</allow_multi_command_handlers>
+
```
Comment (FileEX) [inline Server/mods/deathmatch/mtaserver.conf:101]: Also edit `mtaserver.conf.template`

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/mods/deathmatch/logic/CClientGame.h (hunk 5 above)
Comment (MohabCodeX) [reply Client/mods/deathmatch/logic/CClientGame.h]: That makes sense. I'll consider replacing it with enum class and refactor the usages accordingly for better type safety

File: Server/mods/deathmatch/logic/packets/CSyncSettingsPacket.h [hunk 13]
```diff
@@ -36,4 +36,5 @@ class CSyncSettingsPacket final : public CPacket
     uchar                 m_ucAllowFastSprintFix;
     uchar                 m_ucAllowDrivebyAnimationFix;
     uchar                 m_ucAllowShotgunDamageFix;
+    uchar                 m_allowMultiCommandHandlers;
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/packets/CSyncSettingsPacket.h]: std::uint8_t?

File: Client/mods/deathmatch/logic/CClientGame.h [hunk 14]
```diff
@@ -193,6 +193,12 @@ class CClientGame
         QUIT_CONNECTION_DESYNC,
         QUIT_TIMEOUT,
     };
+    
+    enum class MultiCommandHandlerPolicy
+    {
+        DISABLED = 0,
+        ENABLED = 1
+    };
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientGame.h]: I think this enum is unnecessary. Wouldn’t a simple bool be better here?

**Comment by FileEX** [comment]
I’m missing the ability to change this setting via ``setServerConfig``.
Having to stop the server just to change such a minor setting is imo unacceptable

**Comment by MohabCodeX** [comment]
@FileEX 
> I’m missing the ability to change this setting via setServerConfig.
> Having to stop the server just to change such a minor setting is imo unacceptable

Thanks for the heads-up, the suggestion is implemented (also client side doesn't need to reconnect to have the new changes of the server config) and reviews applied, but I’d like opinions on one feature. Currently, it warns on duplicate commands on the same side (client or server), but not if the same command exists on both. I think that’s fine since they’re separate, but if needed we could add it as an optional check (though I don’t think we’ll need it, but I’d like to hear opinions).

File: Server/mods/deathmatch/logic/CRegisteredCommands.cpp [hunk 15]
```diff
@@ -35,6 +38,26 @@ bool CRegisteredCommands::AddCommand(CLuaMain* pLuaMain, const char* szKey, cons
     assert(pLuaMain);
     assert(szKey);
 
+    if (CommandExists(szKey, nullptr))
+    {
+        const auto policy = static_cast<MultiCommandHandlerPolicy>(g_pGame->GetConfig()->GetAllowMultiCommandHandlers());
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CRegisteredCommands.cpp]: const here is unnecessary

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 16]
```diff
@@ -4701,9 +4701,10 @@ void CGame::SendSyncSettings(CPlayer* pPlayer)
     uchar ucAllowFastSprintFix = true;
     uchar ucAllowDrivebyAnimFix = true;
     uchar ucAllowShotgunDamageFix = true;
+    const std::uint8_t multiCommandHandlerPolicy = static_cast<std::uint8_t>(m_pMainConfig->GetAllowMultiCommandHandlers());
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CGame.cpp]: const here is unnecessary

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 17]
```diff
@@ -6139,6 +6140,7 @@ bool CClientGame::GetBirdsEnabled()
     return m_bBirdsEnabled;
 }
 
+
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientGame.cpp]: extra space

**Review by FileEX — CHANGES_REQUESTED** [review]

**Comment by FileEX** [comment]
> @FileEX
> 
> > I’m missing the ability to change this setting via setServerConfig.
> > Having to stop the server just to change such a minor setting is imo unacceptable
> 
> Thanks for the heads-up, the suggestion is implemented (also client side doesn't need to reconnect to have the new changes of the server config) and reviews applied, but I’d like opinions on one feature. Currently, it warns on duplicate commands on the same side (client or server), but not if the same command exists on both. I think that’s fine since they’re separate, but if needed we could add it as an optional check (though I don’t think we’ll need it, but I’d like to hear opinions).

It's fine imo. But i'm still missing the ability to change this setting via `setServerConfig`.

**Comment by MohabCodeX** [comment]
> It's fine imo. But i'm still missing the ability to change this setting via setServerConfig.

I’ve already added this feature and tested it. You can use setServerConfig / getServerConfig.

**Review by FileEX — APPROVED** [review]

**Comment by FileEX** [comment]
Let’s wait for the restoration of #3857, because for now we don’t know what will happen with the mtaserver.conf_template file.

**Comment by MohabCodeX** [comment]
Yeah, I was just about to say that. 👍🏻
