### PR TITLE
Fix unintended behavior for ped control states 

### LINKED ISSUE #3874: GetPedControlState returns true for the other player when using setPedControlState for yourself
### Describe the bug

If you use setPedControlState on yourself, then getPedControlState used on a nearby player will return true, even if the player is not executing any controls

### Steps to reproduce

1. Set yourself a control for example vehicle_left
`setPedControlState(localPlayer, "vehicle_left", true)`
2. Now use getPedControlState on the player next to you with the same control we set for ourselves

```
local player = getPlayerFromName("xyz") 
outputChatBox(inspect(getPedControlState(player, "vehicle_left")))
```

You can now see that the function will return true if the player does not turn left

### Version

Client: 1.6-release-22789
Server: 1.6-release-22789

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3874

### CODE REVIEW

File: Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h [hunk 1]
```diff
@@ -96,7 +96,7 @@ class CLuaPedDefs : public CLuaDefs
     static bool IsPedReloadingWeapon(CClientPed* const ped) noexcept;
     LUA_DECLARE(AddPedClothes);
     LUA_DECLARE(RemovePedClothes);
-    LUA_DECLARE(SetPedControlState);
+    static bool SetPedControlState(CClientEntity* const entity, const std::string_view control, const bool state) noexcept;
```
Comment (tederis) [inline Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h]: `CClientPed*`? I know that `CStaticFunctionDefinitions::SetPedControlState` accepts `CClientEntity&`, but `SetPedControlState` corresponds to `Ped` and we should stick to `CClientPed`. You can change `CStaticFunctionDefinitions::SetPedControlState` if you wish.

Comment (ghost) [reply Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h]: Done

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 2]
```diff
@@ -2366,24 +2363,13 @@ bool CStaticFunctionDefinitions::RemovePedClothes(CClientEntity& Entity, unsigne
...
-    if (IS_PED(&Entity))
-    {
-        CClientPed& Ped = static_cast<CClientPed&>(Entity);
-
-        if (&Ped == GetLocalPlayer())
-        {
-            return SetControlState(szControl, bState);
-        }
+    if (&ped == GetLocalPlayer())
+        return SetControlState(control.data(), state);
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]: Although `std::string_view` is acceptable in CLuaPedDefs, it's not recommended to use it here because `SetPedControlState` can potentially be called from any place and a string isn't guaranteed to be null-terminated. The same for `GetPedControlState`.

Comment (ghost) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]: Thanks!
