### PR TITLE
Fix invincible peds

### LINKED ISSUE #414: Using setElementHealth on a dead ped makes it invincible
**Describe the bug**
The only way to respawn a ped is with setElementHealth, yet after calling setElementHealth on a dead ped, the server returns `true` for `isPedDead`. You can't damage the ped any more even though `ped.health == 100`.

**To Reproduce**
```
crun setElementPosition(localPlayer, 1968, -2033, 13)
srun a = createPed(0, 1967, -2025, 13)
-- Kill the ped
srun isPedDead(a) -- true
srun setElementHealth(a, 100)
srun isPedDead(a) -- true (should be false)
-- Shoot the ped, it won't take damage
```

**Expected behaviour**
@qaisjp said:
> Setting the health of a ped to a `health > 0` should respawn the ped.

**Additional context**
Do this after calling setElementHealth: setElementSyncer(a, true) and the ped will be able to take damage again, but onPedWasted isn't triggered.

From https://bugs.mtasa.com/view.php?id=8790

### PR DESCRIPTION
**Pull request by FileEX**
Fixes #414 

**Bug description**
The only way to respawn a ped is with setElementHealth, yet after calling setElementHealth on a dead ped, the server returns true for isPedDead. You can't damage the ped any more even though ped.health == 100.

**To reproduce**
```lua
crun setElementPosition(localPlayer, 1968, -2033, 13)
srun a = createPed(0, 1967, -2025, 13)
-- Kill the ped
srun isPedDead(a) -- true
srun setElementHealth(a, 100)
srun isPedDead(a) -- true (should be false)
-- Shoot the ped, it won't take damage
```

Now isPedDead returns false after setElementHealth on dead ped. And ped after setElementHealth(ped,100) isn't invicibles, and will got damage.

Fixed also ArranTuna issue from previous PR 

> I've tested this PR and well it works but there's an issue. After killing the ped and doing setElementHealth(a, 100) the ped gets back up again but then falls down dead again 1 second later. It's alive state is correct but it acts dead, streaming out and back in shows it as stood up. However if I call setElementHealth a second time the ped stands up correctly. Strange.

### CODE REVIEW

File: Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 1]
```diff
@@ -1535,6 +1535,13 @@ bool CStaticFunctionDefinitions::SetElementHealth(CElement* pElement, float fHea
                 // This makes sure the health is set to what will get reported
                 unsigned char ucHealth = static_cast<unsigned char>(fHealth * 1.25f);
                 fHealth = static_cast<float>(ucHealth) / 1.25f;
+
+                // update dead state for peds
+                if (fHealth > 0 && pPed->IsDead())
+                {
+                    pPed->SetIsDead(false);
+                }
+                // set new health
```
Comment (qaisjp) [inline Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]:
```suggestion

                // set new health
```

File: Client/mods/deathmatch/logic/CClientPed.cpp [hunk 2]
```diff
@@ -1732,8 +1732,15 @@ void CClientPed::InternalSetHealth(float fHealth)
...
         {
+            // update dead state for peds
+            if (fHealth > 0 && IsDead())
+            {
+                m_bDead = false;
+            }
+
             // Set the new health
             m_pPlayerPed->SetHealth(fHealth);
+            m_pTaskManager->RemoveTask(TASK_SIMPLE_DEAD);
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/CClientPed.cpp]:
```suggestion

            // Recover from dead state to bring the ped back to life
            m_pTaskManager->RemoveTask(TASK_SIMPLE_DEAD);
```

**Comment by qaisjp** [comment]
Thanks for the bugfix. Code looks fine but won't approve as I haven't actually tested it.

This change isn't limited to peds, so in what way does this change affect players?

**Comment by ArranTuna** [comment]
Works.

**Review by ArranTuna — COMMENTED** [review]
Works.

**Comment by FileEX** [comment]
It does not affect players in any way. It only causes that the 'reborn' ped is not indestructible.

**Comment by patrikjuvonen** [comment]
When two or more players are streamed in, this PR crashes the targeted player via `setElementHealth`. Other clients that were streamed in will crash upon unload.

I am trying to get more information about the crash right now.

```
Version = 1.5.6-custom.0.000
Time = Sat Feb 23 16:43:08 2019
Module = F:\Program Files\Steam\steamapps\common\Grand Theft Auto San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x00281B46

EAX=00000000  EBX=00000000  ECX=0000000B  EDX=21704F14  ESI=21704F14
EDI=000000DA  EBP=0177F348  ESP=0177F31C  EIP=00681B46  FLG=00010202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

File: Client/mods/deathmatch/logic/CClientPed.cpp [hunk 3]
```diff
@@ -1732,8 +1731,17 @@ void CClientPed::InternalSetHealth(float fHealth)
...
+            if (fHealth > 0 && IsDead())
+            {
+                m_bDead = false;
+            }
+
             // Set the new health
             m_pPlayerPed->SetHealth(fHealth);
+
+            // Recover from dead state to bring the ped back to life
+            m_pTaskManager->RemoveTask(TASK_SIMPLE_DEAD);
```
Comment (patrikjuvonen) [inline Client/mods/deathmatch/logic/CClientPed.cpp]: When two or more players are streamed in, this PR crashes the targeted player via `setElementHealth` (crash occurs with both client and server-side variant of the function). Other clients that were streamed in will crash upon unload.

I am trying to get more information about the crash right now.

So far:
 - Seems to be a `m_pTaskManager` related crash. You've added `m_pTaskManager->RemoveTask(TASK_SIMPLE_DEAD);` which is likely the source of the crash.

```
Version = 1.5.6-custom.0.000
Time = Sat Feb 23 16:43:08 2019
Module = F:\Program Files\Steam\steamapps\common\Grand Theft Auto San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x00281B46

EAX=00000000  EBX=00000000  ECX=0000000B  EDX=21704F14  ESI=21704F14
EDI=000000DA  EBP=0177F348  ESP=0177F31C  EIP=00681B46  FLG=00010202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```
Used artifact: https://ci.appveyor.com/project/multitheftauto/mtasa-blue/builds/22594951/artifacts

**Review by patrikjuvonen — CHANGES_REQUESTED** [review]

File: Client/mods/deathmatch/logic/CClientPed.cpp (hunk 3 above)
Comment (FileEX) [reply Client/mods/deathmatch/logic/CClientPed.cpp]: I'm not sure, but maybe we should use ```TASK_PRIORITY_PRIMARY``` instead of ```TASK_SIMPLE_DEAD``` and maybe it will work.  I don't know why this crashes game. i can't do investigate :/

**Comment by qaisjp** [comment]
@FileEX what can we do to help you fix this issue? 

(@patrikjuvonen i've removed the WIP prefix because it didn't look like this PR was a draft — feel free to undo my undo)

**Comment by ghost** [comment]
@patrikjuvonen is right. The crash comes from `m_pTaskManager->RemoveTask(TASK_SIMPLE_DEAD);` 
You are passing a task type to `m_pTaskManager->RemoveTask` instead of passing the primary task index. There are only 5 primary tasks. Take a look at this:

```
enum
{
    TASK_PRIORITY_PHYSICAL_RESPONSE = 0,
    TASK_PRIORITY_EVENT_RESPONSE_TEMP,
    TASK_PRIORITY_EVENT_RESPONSE_NONTEMP,
    TASK_PRIORITY_PRIMARY,
    TASK_PRIORITY_DEFAULT,
    TASK_PRIORITY_MAX
};
```
This means the range of primary task index is 0 to 4. The value of `TASK_SIMPLE_DEAD` is 218; hence it causes a crash.

`TASK_SIMPLE_DEAD` is set to `TASK_PRIORITY_EVENT_RESPONSE_NONTEMP`. This means, your code should look like this if you want to remove the task:
```
m_pTaskManager->RemoveTask(TASK_PRIORITY_EVENT_RESPONSE_NONTEMP);
```
Obviously, this requires testing. We'll have to confirm that it doesn't cause any bugs.

**Comment by FileEX** [comment]
Changed

**Comment by qaisjp** [comment]
Reverted in 159d291
