### PR TITLE
Lua API for buildings

### LINKED ISSUE #450: Created objects don't reflect lights / shadows
**Describe the bug**
Created objects (as maps) don't reflect objects light as world objects do, here go some examples:

Vehicle light in a world object:
image

Vehicle light in a created object:
image

Object (that's also created; it proves that the problem is with the object which should reflect the light, not the vehicle/object that produce the light) light in a world object:

image

Object light in a created object:

image

**Additional context**
From https://bugs.mtasa.com/view.php?id=6576

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #450, #2755, #1921

API:
```
element-building createBuilding(number modelId, float x, float, y, float z, float rx, float ry, float rz [,  number interior = 0])
```

### CODE REVIEW

**Comment by TheNormalnij** [comment]
image

**Comment by tederis** [comment]
I think Euler angles should be used instead of quaternions. Quaternions are less intuitive and will be a nightmare for the most of beginners. Or maybe there should be an enbedded function for the Euler <-> Quaternion conversion. In addition, it would be easier to move previously created maps on `createBuilding` without an effort.

**Comment by TheNormalnij** [comment]
> I think Euler angles should be used instead of quaternions. Quaternions are less intuitive and will be a nightmare for the most of beginners. Or maybe there should be an enbedded function for the Euler <-> Quaternion conversion. In addition, it would be easier to move previously created maps on `createBuilding` without an effort.

Yes, i think so. I didn't found  euler to quaternion functions.

File: Shared/mods/deathmatch/logic/Utils.h [hunk 1]
```diff
@@ -246,6 +246,21 @@ inline float GetSmallestWrapUnsigned(float fValue, float fHigh)
...
+    double sy = sin(vecFrom.fZ * 0.5);
+    double cr = cos(vecFrom.fX * 0.5);
+    double sr = sin(vecFrom.fX * 0.5);
+    double cp = cos(vecFrom.fY * 0.5);
+    double sp = sin(vecFrom.fY * 0.5);
+
+    vecTo.fW = cy * cr * cp + sy * sr * sp;
+    vecTo.fX = cy * sr * cp - sy * cr * sp;
+    vecTo.fY = cy * cr * sp + sy * sr * cp;
+    vecTo.fY = sy * cr * cp - cy * sr * sp;
```
Comment (Zangomangu) [inline Shared/mods/deathmatch/logic/Utils.h]: This doesn't look right

File: Client/game_sa/CPoolsSA.cpp [hunk 2]
```diff
@@ -329,6 +332,101 @@ void CPoolsSA::DeleteAllObjects()
...
+inline bool CPoolsSA::AddBuildingToPool(CClientBuilding* pClientBuilding, CBuildingSA* pBuilding)
+{
+    // Grab the new object interface
+    CBuildingSAInterface* pInterface = pBuilding->GetBuildingInterface();
+
+    if (!pInterface)
+    {
+        return false;
+    }
+    else
```
Comment (Zangomangu) [inline Client/game_sa/CPoolsSA.cpp]: can remove `else`

File: Client/game_sa/CFileLoaderSA.cpp [hunk 3]
```diff
@@ -28,6 +28,11 @@ void CFileLoaderSA::StaticSetHooks()
     HookInstall(0x538690, (DWORD)CFileLoader_LoadObjectInstance, 5);
 }
 
+CBuildingSAInterface* CFileLoaderSA::LoadFileObjectInstance(SFileObjectInstance* obj)
```
Comment (Zangomangu) [inline Client/game_sa/CFileLoaderSA.cpp]: LoadObjectInstance?

**Comment by Zangomangu** [comment]
We're going from euler, to quaternion, to matrix now
Could we also please allow skipping euler ?

```
element-building createBuilding(number modelId, float x, float, y, float z, float rx, float ry, float rz, float rw [, number interior = 0])
```
If `rw` is nil interpret as Euler otherwise quaternion

File: Client/game_sa/CFileLoaderSA.cpp (hunk 3 above)
Comment (TheNormalnij) [reply Client/game_sa/CFileLoaderSA.cpp]: This is common name for this function. It is used in gta-reverse-modern and  ida ipb

Comment (Zangomangu) [reply Client/game_sa/CFileLoaderSA.cpp]: yeah i mean it should be LoadObjectInstance instead of LoadFileObjectInstance to match

**Comment by TheNormalnij** [comment]
> Could we also please allow skipping euler ?

We can add quaternion -> euler utility function

**Comment by Zangomangu** [comment]
Well the point would be to get rid of that conversion altogether (where some euler angles are problematic) since the GTA function accepts a quaternion.

But i'm not too steadfast on it, since it can be worked around by setting matrix.
I can see the point where scripters are used to euler angles and we want to keep it similar.

File: Client/game_sa/CFileLoaderSA.cpp (hunk 3 above)
Comment (TheNormalnij) [reply Client/game_sa/CFileLoaderSA.cpp]: It loads SFileObjectInstance object. So function name describes it. idk

File: Client/game_sa/CFileLoaderSA.cpp [hunk 4]
```diff
@@ -201,7 +206,7 @@ RpAtomic* CFileLoader_SetRelatedModelInfoCB(RpAtomic* atomic, SRelatedModelInfo*
     return atomic;
 }
 
-CEntitySAInterface* CFileLoader_LoadObjectInstance(const char* szLine)
+CBuildingSAInterface* CFileLoader_LoadObjectInstance(const char* szLine)
```
Comment (tederis) [inline Client/game_sa/CFileLoaderSA.cpp]: Why do you need this change from **CEntitySAInterface** to **CBuildingSAInterface**? From what I can see this function should return CEntity*(or CEntitySAInterface* in terms of MTA).

File: Client/mods/deathmatch/logic/CClientBuilding.cpp [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+    : ClassInit(this),
+      CClientEntity(ID),
+      m_pBuildingManager(pManager->GetBuildingManager()),
+      m_usModelId(usModelId),
+      m_vPos(pos),
+      m_vRot(rot),
+      m_interior(interior)
+{
+    m_pBuilding = nullptr;
+    m_pManager = pManager;
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuilding.cpp:23]: It's better to move the initialization of these members to the member initializer list.

File: Client/mods/deathmatch/logic/CClientBuilding.cpp [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+
+void CClientBuilding::SetRotationRadians(const CVector& vecRadians)
+{
+    m_vRot = vecRadians;
+    Recreate();
+}
+
+void CClientBuilding::SetInterior(uint8_t ucInterior)
+{
+    m_interior = ucInterior;
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuilding.cpp:78]: The method **Recreate** is heavy and we could avoid it by adding a comparison: `if (m_interior == ucInterior) return;` The same is true for other methods.

File: Client/mods/deathmatch/logic/CClientBuilding.cpp [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+    m_pManager = pManager;
+    SetTypeName("building");
+    m_pBuildingManager->AddToList(this);
+    Create();
+}
+
+CClientBuilding::~CClientBuilding()
+{
+    m_pBuildingManager->RemoveFromList(this);
+    if (m_pBuilding)
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuilding.cpp]: This check is already exists within `Destroy` method. I think double check is unnecessary.

File: Client/mods/deathmatch/logic/CClientBuilding.h [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+
+#include <game/CBuilding.h>
+
+class CClientBuilding : public CClientEntity
+{
+    DECLARE_CLASS(CClientBuilding, CClientEntity)
+    friend class CClientBuildingManager;
+
+public:
+    CClientBuilding(class CClientManager* pManager, ElementID ID, uint16_t usModelId, CVector &pos, CVector &rot, uint8_t interior);
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuilding.h]: I see the lack of `const` qualifiers in front of `&pos` and `&rot`. Was this done intentionally?

File: Client/mods/deathmatch/logic/CClientBuildingManager.cpp [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+    RemoveAll();
+}
+
+void CClientBuildingManager::RemoveAll()
+{
+    // Make sure they don't remove themselves from our list
+    m_bRemoveFromList = false;
+
+    // Run through our list deleting the buildings
+    auto iter = m_List.begin();
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: Is the choice in favor of iterators intentional? Maybe better to use a range based for loop? And I see that after removing all objects the list it is still contains pointers to them. I think `m_List.clear()` chould be called.

File: Client/mods/deathmatch/logic/CClientBuildingManager.cpp [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+        delete *iter;
+    }
+
+    // Allow list removal again
+    m_bRemoveFromList = true;
+}
+
+bool CClientBuildingManager::Exists(CClientBuilding* pBuilding)
+{
+    // Matches given DFF?
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: DFF?

File: Client/mods/deathmatch/logic/CClientBuildingManager.cpp [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+    auto iter = m_List.begin();
+    for (; iter != m_List.end(); iter++)
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: Is the choice in favor of iterators intentional? Maybe better to use a range based for loop? Or even `std::find`?

File: Client/mods/deathmatch/logic/CClientBuildingManager.h [hunk 12]
```diff
@@ -0,0 +1,41 @@
...
+    friend class CClientBuilding;
+
+public:
+    CClientBuildingManager(class CClientManager* pManager);
+    ~CClientBuildingManager();
+
+    void RemoveAll();
+    bool Exists(CClientBuilding* pBuilding);
+
+    std::list<CClientBuilding*>::const_iterator IterBegin() { return m_List.begin(); }
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuildingManager.h]: Maybe better to just return a const ref to a list?

File: Shared/mods/deathmatch/logic/Utils.h [hunk 13]
```diff
@@ -246,6 +246,21 @@ inline float GetSmallestWrapUnsigned(float fValue, float fHigh)
 
 void RotateVector(CVector& vecLine, const CVector& vecRotation);
 
+inline void ConvertEulersToQuaternion(const CVector& vecFrom, CVector4D vecTo)
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.h]: Looks like `vecTo` is expected to be passed by reference.

File: Client/game_sa/CPoolsSA.cpp [hunk 14]
```diff
@@ -703,6 +805,18 @@ DWORD CPoolsSA::GetObjectPoolIndex(std::uint8_t* pInterface)
     return ((pInterface - pTheObjects) / dwAlignedSize);
 }
 
+DWORD CPoolsSA::GetBuildingPoolIndex(std::uint8_t* pInterface)
+{
+    DWORD         dwAlignedSize = 412;
```
Comment (tederis) [inline Client/game_sa/CPoolsSA.cpp]: It should be 56 bytes

File: Client/mods/deathmatch/logic/CClientManager.h [hunk 15]
```diff
@@ -96,6 +97,7 @@ class CClientManager
     CClientEffectManager*        GetEffectManager() { return m_pEffectManager; }
     CClientPointLightsManager*   GetPointLightsManager() { return m_pPointLightsManager; }
     CClientIMGManager*           GetIMGManager() { return m_pImgManager; }
+    CClientBuildingManager*      GetBuildingManager() { return m_pBuildingManager; }
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientManager.h]: I think **const** qualifier should be added for this method.

File: Shared/mods/deathmatch/logic/Utils.h [hunk 16]
```diff
@@ -246,6 +246,21 @@ inline float GetSmallestWrapUnsigned(float fValue, float fHigh)
...
+{
+    double cy = cos(vecFrom.fZ * 0.5);
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.h]: Trigonometric functions accept radians. But from what I can see `vecFrom` contains degrees.

**Comment by tederis** [comment]
**createBuilding** function must check if **modelId** argument is actually a building model. It can be done by looking at **usDynamicIndex** field: `auto modelInfo = pGame->GetModelInfo(modelId);
if (modelInfo->GetInterface()->usDynamicIndex != 0xffff)
    return nullptr;`

Otherwise GTA will create a dummy object instead of a building and this type of object will never be deleted. You can check what will happened if create a building with model ID 3797.

**Comment by tederis** [comment]
I also noticed that shadows and grass are still on the map even after a resource restart. But they disappear after the respawn(I guess shadows and grass are spawned once after the building creation).

**Comment by tederis** [comment]
There also a problem with the rotation. When you spawn an object and a building with the same coordinates and the same rotation, their actual transformation differs.

mta-screen_2023-12-25_16-05-51

File: Client/mods/deathmatch/logic/CClientBuilding.cpp (hunk 5 above)
Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientBuilding.cpp:23]: m_pManager is member of parent class

File: Shared/mods/deathmatch/logic/Utils.h (hunk 16 above)
Comment (TheNormalnij) [reply Shared/mods/deathmatch/logic/Utils.h]: Oh, yes. This is a mess

File: Client/mods/deathmatch/logic/CClientBuilding.cpp (hunk 5 above)
Comment (tederis) [reply Client/mods/deathmatch/logic/CClientBuilding.cpp:23]: Oh, ok. Didn't notice that.

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientBuilding.cpp:23]: But i moved m_pBuilding. It was useful

File: Client/game_sa/CFileLoaderSA.cpp (hunk 4 above)
Comment (TheNormalnij) [reply Client/game_sa/CFileLoaderSA.cpp]: I think current variant describes this function better. CFileLoader_LoadObjectInstance always returns a building object and not a another class object inherited from CEntitySAInterface

File: Client/mods/deathmatch/logic/CClientBuildingManager.cpp (hunk 10 above)
Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: Yep :p

File: Client/game_sa/CFileLoaderSA.cpp (hunk 4 above)
Comment (tederis) [reply Client/game_sa/CFileLoaderSA.cpp]: LoadObjectInstance can return either CBuilding or CDummyObject as can be verified by looking at reversed SA. You can pass model 3797 into this function and it will return CDummyObject which is not a building.

**Comment by TheNormalnij** [comment]
> also noticed that shadows and grass are still on the map even after a resource restart. But they disappear after the respawn(I guess shadows and grass are spawned once after the building creation).

This can be fixed manually via `setWorldSpecialPropertyEnabled('randomfoliage', false)`.

**Comment by TheNormalnij** [comment]
> There also a problem with the rotation. When you spawn an object and a building with the same coordinates and the same rotation, their actual transformation differs.

Fixed

**Comment by tederis** [comment]
> > also noticed that shadows and grass are still on the map even after a resource restart. But they disappear after the respawn(I guess shadows and grass are spawned once after the building creation).
> 
> This can be fixed manually via `setWorldSpecialPropertyEnabled('randomfoliage', false)`.

This disables the grass no doubt. But what if I want to keep grass on the default SA objects? And what about the shadows?
mta-screen_2023-12-25_19-29-14

**Comment by tederis** [comment]
> > > also noticed that shadows and grass are still on the map even after a resource restart. But they disappear after the respawn(I guess shadows and grass are spawned once after the building creation).
> > 
> > 
> > This can be fixed manually via `setWorldSpecialPropertyEnabled('randomfoliage', false)`.
> 
> This disables the grass no doubt. But what if I want to keep grass on the default SA objects? And what about the shadows? mta-screen_2023-12-25_19-29-14

My opinion is that we should restream(reload or recreate) grass and shadows somehow at each change in the buildings. Or even better leave a mark that grass(and shadows) should be recreated and do it in the next frame to eliminate tons of excessive calculations.

**Comment by TheNormalnij** [comment]
> My opinion is we should restream grass and shadows somehow at each change in the buildings.

It causes performance degradation when you have significant amount of buildings. I prefer additional `restreamShadows` function.

**Comment by tederis** [comment]
> > My opinion is we should restream grass and shadows somehow at each change in the buildings.
> 
> It causes performance degradation when you have significant amount of buildings. I prefer additional `restreamShadows` function.

See my additions to the comment: `Or even better leave a mark that grass(and shadows) should be recreated and do it in the next frame to eliminate tons of excessive calculations.` In my opinion a deletion procedure should leave the game as it was before the building creation. It should be by default. But function `restreamShadows` can be added as well.

**Comment by TheNormalnij** [comment]
> **createBuilding** function must check if **modelId** argument is actually a building model. It can be done by looking at **usDynamicIndex** field: `auto modelInfo = pGame->GetModelInfo(modelId); if (modelInfo->GetInterface()->usDynamicIndex != 0xffff) return nullptr;`

Fixed too

**Comment by TheNormalnij** [comment]
> In my opinion a deletion procedure should leave the game as it was before the building creation.

Yes. This is right. But i'd rather have manual control in API to prevent unnecessary glass or shadows flickering.

I think this is not a big deal for now. Glass and shadows disappear itself after some distance

File: Client/game_sa/CFileLoaderSA.cpp (hunk 3 above)
Comment (TheNormalnij) [reply Client/game_sa/CFileLoaderSA.cpp]: Ah... I see

File: Client/game_sa/CPoolsSA.cpp [hunk 17]
```diff
@@ -329,6 +332,105 @@ void CPoolsSA::DeleteAllObjects()
...
+    instance.lod = -1;
+    instance.interiorID = interior;
+    instance.position = *vPos;
+    instance.rotation = *vRot;
+
+    // Fix strange SA rotation 
+    instance.rotation.fW = -instance.rotation.fW;
+
+    CFileLoaderSA loader{};
+    auto pBuilding = static_cast<CBuildingSAInterface*>(loader.LoadObjectInstance(&instance));
```
Comment (tederis) [inline Client/game_sa/CPoolsSA.cpp]: What is the reason for using a non-static **LoadObjectInstance** method? Isn't it better to make it static and just `CFileLoaderSA::LoadObjectInstance(&instance)`? From what I can see, this method is static in SA(see reversed SA or IDA).

File: Client/game_sa/CFileLoaderSA.cpp [hunk 18]
```diff
@@ -28,6 +28,11 @@ void CFileLoaderSA::StaticSetHooks()
     HookInstall(0x538690, (DWORD)CFileLoader_LoadObjectInstance, 5);
 }
 
+CEntitySAInterface* CFileLoaderSA::LoadObjectInstance(SFileObjectInstance* obj)
+{
+    return ((CEntitySAInterface * (__cdecl*)(SFileObjectInstance*))0x538090)(obj);
```
Comment (tederis) [inline Client/game_sa/CFileLoaderSA.cpp]: This function (0x538090) is expecting a second `const char`* argument. See the function's prologue:
modelName

Comment (tederis) [reply Client/game_sa/CFileLoaderSA.cpp]: If fact, this argument is no actually used. So you can just rewrite it the following way: `return ((CEntitySAInterface * (__cdecl*)(SFileObjectInstance*, const char*))0x538090)(obj, nullptr);`

File: Client/game_sa/CPoolsSA.cpp (hunk 17 above)
Comment (TheNormalnij) [reply Client/game_sa/CPoolsSA.cpp]: For some architectural reasons i prefer loader classes over functions.
I can make it simpler with using static function, because we don't have DI / tests for this code

File: Client/game_sa/CFileLoaderSA.cpp (hunk 18 above)
Comment (TheNormalnij) [reply Client/game_sa/CFileLoaderSA.cpp]: Didn't notice that

File: Client/game_sa/CPoolsSA.cpp (hunk 17 above)
Comment (tederis) [reply Client/game_sa/CPoolsSA.cpp]: This is OK. But I prefer to keep the code as close to SA as possible (within the bounds of game_sa module).

**Comment by Zangomangu** [comment]
Nice work on this pr
Getting 30 % less cpu usage with createBuilding over createObject

**Comment by Zangomangu** [comment]
#1921 is also fixed with this PR

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Comment (Zangomangu) [inline Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:1]: Missing getElementModel
I think you should go through the getter/setters here related to CClientObject and determine which should also work for CClientBuilding.

E.g.
- get/setElementCollisionsEnabled
- getElementBoundingBox
- getElementRadius
- getElementDistanceFromCentreOfMassToBaseOfModel
- get/setElementAlpha
- "CollidableWith" functions

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:1]: getElementModel is fixed
All another functions will be added later. I keep this PR small to make review and testing much easier.

**Comment by tederis** [comment]
There are still problems with the rotation(it doesn't match the rotation that objects created via createObject have). I believe that this is an important point because most of the players will use buildings as a substitute for objects.
mta-screen_2023-12-28_12-02-21

**Comment by TheNormalnij** [comment]
Oh. rx between 90 and 270 is broken

**Comment by TheNormalnij** [comment]
I think there is no more issues with rotation

File: Shared/mods/deathmatch/logic/Utils.h [hunk 19]
```diff
@@ -246,19 +246,20 @@ inline float GetSmallestWrapUnsigned(float fValue, float fHigh)
...
-    double cr = cos(vecFrom.fX * 0.5);
-    double sr = sin(vecFrom.fX * 0.5);
-    double cp = cos(vecFrom.fY * 0.5);
-    double sp = sin(vecFrom.fY * 0.5);
-
-    vecTo.fW = cy * cr * cp + sy * sr * sp;
-    vecTo.fX = cy * sr * cp - sy * cr * sp;
-    vecTo.fY = cy * cr * sp + sy * sr * cp;
-    vecTo.fZ = sy * cr * cp - cy * sr * sp;
+    const float c1 = cos(vecFrom.fX / 2.0f);
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.h]: I suggest you use a multiplication instead of the division due to the performance issues.

Comment (TheNormalnij) [reply Shared/mods/deathmatch/logic/Utils.h]: fixed

File: Client/mods/deathmatch/logic/CClientBuildingManager.cpp [hunk 20]
```diff
@@ -0,0 +1,84 @@
...
+        return false;
+    }
+
+    eModelInfoType eType = pModelInfo->GetModelType();
+    return (eType == eModelInfoType::CLUMP || eType == eModelInfoType::ATOMIC || eType == eModelInfoType::WEAPON || eType == eModelInfoType::TIME);
+}
+
+bool CClientBuildingManager::IsValidPosition(const CVector& pos) noexcept
+{
+    return (pos.fX >- -3000.0f && pos.fX <= 3000.0f && pos.fY >= -3000.0f && pos.fY <= 3000.0f);
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: `pos.fX >- -3000.0f` misprint

Comment (tederis) [reply Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: Aside of it, I would use a constexpr variable here.

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientBuildingManager.cpp]: fixed

**Comment by tederis** [comment]
The PR is mature enough to be merged I think. Problems related to glass and shadows(see my comments above) can be addressed in the next PRs. LODs can be also implemented in future commits.

**Review by tederis — APPROVED** [review]
The PR is mature enough to be merged I think. Problems related to grass and shadows(see my comments above) can be addressed in the next PRs. LODs can also be implemented in future commits.

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Comment (tederis) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:1]: I propose to move it to the next commits and merge the PR as is. I hope @TheNormalnij will be able to address proposed changes shortly after the merge.

**Review by Zangomangu — APPROVED** [review]
agree with tederis

**Comment by BenhurPaz** [comment]
Merge this!

**Comment by MrSol0** [comment]
I come here to add my voice with the previous people and say please merge this ASAP as we need it in our upcoming project.

**Comment by Einheit-101** [comment]
What about:
-LOD Distance (How far can we see buildings? Infinite draw distance like in MTA:Eir?)
-Shaders - should we be able to restrict shaders to buildings?
-Can buildings be altered with setElementPosition and other functions?

**Comment by TheNormalnij** [comment]
> -LOD Distance (How far can we see buildings? (Infinite draw distance, like in MTA:Eir?)

Draw distance is limited by GTA SA only. Buildings have equal draw distance with SA world world elements.

> -Shaders - should we be able to restrict shaders to buildings?

I think only global shaders  work. Personally, i don't prioritize shaders over dynamic pool size / LODs  / dynamic map box.

> -Can buildings be altered with setElementPosition and other functions?

setPostion / setRotation / setMatrix functions  work, but they are expensive. I suggest not use them

**Comment by Dutchman101** [comment]
@TheNormalnij [https://wiki.multitheftauto.com/wiki/CreateBuilding](https://wiki.multitheftauto.com/wiki/CreateBuilding) doesn't exist 2 weeks after merge, please add it
