### PR TITLE
Fixed element health issues

### LINKED ISSUE #486: getElementHealth sometimes returns incorrect values for players
**Describe the bug**
Using the code below (serverside) will set the players health to various values then output getElementHealth both immediately after, and after a 200ms delay. Sometimes, the value returned from getElementHealth does not match the value set 200ms before.

Example output: http://pastebin.com/raw/9VkFAieL
When the player health is set to 83, getElementHealth returns 82 both times. This happens sporadically all through 1-100.

This is a problem is you want to (for example) heal a player 1 health every second, because it will get stuck in a loop doing 82 + 1 forever (example: http://pastebin.com/b103yd0p )

**To Reproduce**
```lua
addCommandHandler("healthcheck", 
	function(player)
		local i = 80

		setElementHealth(player, i)
		outputConsole(string.format("set %.1f", i))
		outputConsole(string.format("get instant %.3f (ceil: %.3f)", getElementHealth(player), math.ceil(getElementHealth(player))))
			
		setTimer(
			function()
				outputConsole(string.format("get delayed %.3f (ceil: %.3f)", getElementHealth(player), math.ceil(getElementHealth(player))))

				i = i + 1

				setElementHealth(player, i)
				outputConsole(string.format("set %.1f", i))
				outputConsole(string.format("get instant %.3f (ceil: %.3f)", getElementHealth(player), math.ceil(getElementHealth(player))))
			end, 
		200, 10)
	end
)
```

If you run the same code clientside, getElementHealth seems to return the correct values. It also appears to work correctly for vehicles.

**Expected behavior**

**Screenshots**

**MTA Client (please complete the following information):**
MTA v1.5.3-release-10835

**MTA Server (please complete the following information):**
MTA v1.5.3-release-10835

**Additional context**
Using the pastebin code, I found that health wouldn't even increase from 10 up to 11 using v1.5.3-release-10835. Though as it works fine with an increment of 2+ and I doubt many people want to increase health by just 1 and that it can be avoided by using client side setElementHealth, this is a low priority.

BTW you shouldn't be using setElementHealth server side on players as it's so inefficient (it sends a message to every play on the server) instead you triggerClientEvent to that player and have them set their health client side which then updates with other players next pure sync update which is going to be around 100 to 300ms which is fine because remote players don't even need to know exact health of remote players instantly.

From https://bugs.mtasa.com/view.php?id=9492

### LINKED ISSUE #3626: setElementHealth working incorrectly.
### Describe the bug

When adding or subtracting **1** to the player's health, incorrect values are assigned or in the case of increasing health, sometimes not increasing at all. 

### Steps to reproduce

1. Create a server-sided script with this code:
```lua

addCommandHandler('emptyhealth', -- When testing increasehealth
    function(player)
        setElementHealth(player, 1)
        outputChatBox("Health is now empty", player)
    end
)


addCommandHandler('fullhealth', -- When testing decreasehealth
    function(player)
        setElementHealth(player, 100)
        outputChatBox("Health is now full again", player)
    end
)

addCommandHandler('decreasehealth',
    function(player)
        setElementHealth(player, getElementHealth(player) - 1)
        outputChatBox("Health decreased to "..getElementHealth(player), player)
    end
)

addCommandHandler('increasehealth',
    function(player)
        setElementHealth(player, getElementHealth(player) + 1)
        outputChatBox("Health increased to "..getElementHealth(player), player)
    end
)
```
2. Use command /emptyhealth and then constantly try /increasehealth
3. Use command /fullhealth and then constantly try /decreasehealth

### Version

Client & Server: 1.6-release-22650

### Additional context

Alone in my local server, I did additional testing with **runcode**

Subtracting -1 (Starting from 100):
```lua
justn executed command: setElementHealth(getRandomPlayer(), 100)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 100 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 98 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 97 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 96 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 94 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 93 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 92 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) - 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 90 [number]
```

Adding +1 (Starting from 1):
```lua
justn executed command: setElementHealth(getRandomPlayer(), 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 1 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) + 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 2 [number]
justn executed command: setElementHealth(getRandomPlayer(), getElementHealth(getRandomPlayer()) + 1)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 2 [number]
justn executed command: setElementHealth(getRandomPlayer(), 3)
Command results: true [boolean]
justn executed command: getElementHealth(getRandomPlayer())
Command results: 2 [number]
```

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TracerDS**
Resolves #486
Resolves #3626

### CODE REVIEW

**Review by TheNormalnij — APPROVED** [review]

File: Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 1]
```diff
@@ -1654,27 +1654,15 @@ bool CStaticFunctionDefinitions::SetElementHealth(CElement* pElement, float fHea
...
 
-                // Do not set the health below zero
-                if (fHealth < 0.0f)
-                    fHealth = 0.0f;
+            fHealth = Clamp(0.0f, fHealth, pPed->GetMaxHealth());
+            pPed->SetHealth(fHealth);
 
-                // This makes sure the health is set to what will get reported
-                unsigned char ucHealth = static_cast<unsigned char>(fHealth * 1.25f);
-                fHealth = static_cast<float>(ucHealth) / 1.25f;
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:1670]: Why did you remove `1.25f` coefficient?

Comment (TracerDS) [reply Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:1670]: Because it was completely pointless and caused this issue to happen
