### PR TITLE
Fix crash when player dies on fire

### LINKED ISSUE #4037: Crash when player is on fire
### Describe the bug

My players report massive issue since recent mta updates, causing crash when player is on fire and dying.

[client_1_6_release_22977_0_000_gtasa_00171a00_5_DNM_C269DE53_55F3.dmp.zip](https://github.com/user-attachments/files/18863263/client_1_6_release_22977_0_000_gtasa_00171a00_5_DNM_C269DE53_55F3.dmp.zip)
[client_1_6_release_22977_0_000_gtasa_00139405_5_DNM_5874DE53_55F3.dmp.zip](https://github.com/user-attachments/files/18863262/client_1_6_release_22977_0_000_gtasa_00139405_5_DNM_5874DE53_55F3.dmp.zip)

### Steps to reproduce

Ignite your-self till death

### Version

_No response_

### Additional context

** -- Unhandled exception -- **

Version = 1.6-release-22977.0.000
Time = Wed Feb 19 10:55:54 2025
Module = C:\ProgramData\MTA San Andreas All\1.6\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x00171A00

EAX=00B9BAF0  EBX=0044215C  ECX=00000000  EDX=00B9BAE8  ESI=246FA018
EDI=246FA5A4  EBP=00B7CD98  ESP=0177F3C0  EIP=00571A00  FLG=00010293
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by FileEX**
Fixes #4037 

The crash was introduced in https://github.com/multitheftauto/mtasa-blue/commit/e09b85fd4fc424f5258cc20aa8e9a385bfc6524c

The function CPed::RestorePlayerStuffDuringResurrection calls Fire::Extinguish, and then executes a cmp instruction with the ebx register, which got overwritten inside CFire::Extinguish during the call to our hook. That’s why the condition always evaluated as true—even when the value was actually nullptr.

### CODE REVIEW

File: Client/game_sa/CFireSA.cpp [hunk 1]
```diff
@@ -242,13 +242,16 @@ static void _declspec(naked) HOOK_CFire_Extinguish()
     _asm
     {
         mov [eax+730h], edi
+
+        push ebx
         mov ebx, [esp+8]
```
Comment (botder) [inline Client/game_sa/CFireSA.cpp]: Since you modify `esp` with the `push ebx` above now, don't you have to fix the `+8` offset here?

Comment (FileEX) [reply Client/game_sa/CFireSA.cpp]: Yeah, you're right i forgot about it.
