### PR TITLE
Fix #2872: Add ability to restream LOD models

### LINKED ISSUE #2872: engineRestreamWorld not working with LOD models
### Describe the bug

Currently `engineRestreamWorld` has no effect on world LOD models and using `engineStreamingFreeUpMemory` is not always working with LODs.

### Steps to reproduce

1. Replace for example model 17858.
2. Execute `engineRestreamWorld`.
3. Result = model in world is not replaced.

### Version

ALL

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TFP-dev**
This PR updates `engineRestreamWorld` function. It adds optional `includeLODs` argument which gives you abbility to restream world LOD models.
```lua
bool engineRestreamWorld ( [bool includeLODs = false] )
```
Fixes #2872

### CODE REVIEW

File: Client/game_sa/CStreamingSA.cpp [hunk 1]
```diff
@@ -171,3 +171,11 @@ std::uint32_t CStreamingSA::GetMemoryUsed() const
...
     return *reinterpret_cast<std::uint32_t*>(0x8E4CB4);
 }
+
+void CStreamingSA::RemoveBigBuildings()
+{
+    using Function_RemoveBigBuildings = void(__cdecl*)();
+    auto removeBigBuildings = reinterpret_cast<Function_RemoveBigBuildings>(0x4093B0);
+
+    removeBigBuildings();
+}
```
Comment (TheNormalnij) [inline Client/game_sa/CStreamingSA.cpp]: I think, it's bad class for this method

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 2]
```diff
@@ -6555,6 +6555,9 @@ void CClientGame::RestreamWorld()
     m_pManager->GetPedManager()->RestreamAllPeds();
     m_pManager->GetPickupManager()->RestreamAllPickups();
 
+    if (bRemoveBigBuildings == true)
+        g_pGame->GetStreaming()->RemoveBigBuildings();
+
```
Comment (TheNormalnij) [inline Client/mods/deathmatch/logic/CClientGame.cpp]: Is there any reason to make this operation optional?

File: Client/game_sa/CStreamingSA.cpp (hunk 1 above)
Comment (TFP-dev) [reply Client/game_sa/CStreamingSA.cpp]: According to https://github.com/gta-reversed/gta-reversed-modern/blob/8416b041a0e96f0df5c9d6915d0ca93ce2dfeaf2/source/game_sa/Streaming.cpp#L2187-L2198 this class should be good.

File: Client/mods/deathmatch/logic/CClientGame.cpp (hunk 2 above)
Comment (TFP-dev) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: Restreaming LOD models looks ugly and that's why I make it optional.

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: Can you show, please?

Comment (TFP-dev) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: [Here](https://youtu.be/14HhpsBaxYU)

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: Looks ok for me

Comment (TFP-dev) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: It is also worth noting that restreaming world including LODs is longer than normal restream, but if this is necessary then I can change restreaming LODs to be default behaviour of ```engineRestreamWorld()```.

Comment (TFP-dev) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: > ... but if this is necessary then I can change restreaming LODs to be default behaviour of `engineRestreamWorld()`.

I changed my mind, restreaming LODs should be optional because for example there is no need to restream whole world including LODs when you replace only normal model or pickup model.

File: Client/mods/deathmatch/logic/CClientGame.h [hunk 3]
```diff
@@ -439,7 +439,7 @@ class CClientGame
 
     bool TriggerBrowserRequestResultEvent(const std::unordered_set<SString>& newPages);
     void RestreamModel(unsigned short usModel);
-    void RestreamWorld();
+    void RestreamWorld(bool bRemoveBigBuildings);
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientGame.h]:
```suggestion
    void RestreamWorld(bool removeBigBuildings);
```

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 4]
```diff
@@ -6546,7 +6546,7 @@ void CClientGame::RestreamModel(unsigned short usModel)
         m_pManager->GetVehicleManager()->RestreamVehicleUpgrades(usModel);
 }
 
-void CClientGame::RestreamWorld()
+void CClientGame::RestreamWorld(bool bRemoveBigBuildings)
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientGame.cpp]:
```suggestion
void CClientGame::RestreamWorld(bool removeBigBuildings)
```

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 5]
```diff
@@ -6559,6 +6559,9 @@ void CClientGame::RestreamWorld()
     m_pManager->GetPedManager()->RestreamAllPeds();
     m_pManager->GetPickupManager()->RestreamAllPickups();
 
+    if (bRemoveBigBuildings == true)
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientGame.cpp]:
```suggestion
    if (removeBigBuildings)
```

File: Client/game_sa/CStreamingSA.h [hunk 6]
```diff
@@ -57,6 +57,7 @@ class CStreamingSA final : public CStreaming
     bool HasModelLoaded(DWORD dwModelID);
     void RequestSpecialModel(DWORD model, const char* szTexture, DWORD channel);
     void ReinitStreaming();
+    void RemoveBigBuildings();
```
Comment (botder) [inline Client/game_sa/CStreamingSA.h]:
```suggestion
    void RemoveBigBuildings() override;
```

File: Client/game_sa/CStreamingSA.cpp [hunk 7]
```diff
@@ -306,3 +306,11 @@ std::uint32_t CStreamingSA::GetMemoryUsed() const
 {
     return *reinterpret_cast<std::uint32_t*>(0x8E4CB4);
 }
+
+void CStreamingSA::RemoveBigBuildings()
+{
+    using Function_RemoveBigBuildings = void(__cdecl*)();
+    auto removeBigBuildings = reinterpret_cast<Function_RemoveBigBuildings>(0x4093B0);
+
+    removeBigBuildings();
```
Comment (botder) [inline Client/game_sa/CStreamingSA.cpp]:
```suggestion
    (reinterpret_cast<void(__cdecl*)()>(0x4093B0))();
```

File: Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp [hunk 8]
```diff
@@ -2311,8 +2311,13 @@ bool CLuaEngineDefs::EngineResetModelFlags(uint uiModelID)
...
-bool CLuaEngineDefs::EngineRestreamWorld()
+bool CLuaEngineDefs::EngineRestreamWorld(lua_State* const luaVM)
 {
-    g_pClientGame->RestreamWorld();
+    bool bRestreamLODs;
+
+    CScriptArgReader argStream(luaVM);
+    argStream.ReadBool(bRestreamLODs, false);
+
+    g_pClientGame->RestreamWorld(bRestreamLODs);
```
Comment (botder) [inline Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp]:
```suggestion
    bool restreamLODs{};

    CScriptArgReader argStream(luaVM);
    argStream.ReadBool(restreamLODs, false);

    g_pClientGame->RestreamWorld(restreamLODs);
```

**Review by botder — CHANGES_REQUESTED** [review]
