### PR TITLE
Fix client side debugscript level filtering (#3498)

### LINKED ISSUE #3498: debugscript behavior needs tweaking
### Describe the bug

Currently debugscript doesn't behave accordingly to it's description:
```
debugscript: Modes available are 0 (None), 1 (Errors), 2 (Errors + Warnings), 3 (All)
```
As of now it checks whether debug level of player is equal or higher than debug level of message. Do note that outputDebugString makes use of levels from 0 to 4. Moreover, client seems to miss relevant checks; by having /debugscript set to 1 all of client-side debug messages would be displayed, but it should display errors only.

### Steps to reproduce

Play around with `outputDebugString` and /debugscript

### Version

_No response_

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by MohabCodeX**
Fixes #3498

you can test using this script which has a lot of test options
[dbgtest.zip](https://github.com/user-attachments/files/21519251/dbgtest.zip)

### CODE REVIEW

File: Client/mods/deathmatch/logic/CScriptDebugging.cpp [hunk 1]
```diff
@@ -102,38 +102,63 @@ bool CScriptDebugging::SetLogfile(const char* szFilename, unsigned int uiLevel)
...
         // Create a timer
-        ::CreateTimerQueueTimer(&m_flushTimerHandle, NULL, TimerProc, NULL, 50, 50, WT_EXECUTEINTIMERTHREAD);
+        ::CreateTimerQueueTimer(&m_flushTimerHandle, nullptr, TimerProc, nullptr, 50, 50, WT_EXECUTEINTIMERTHREAD);
         return true;
     }
 
     return false;
 }
 
+enum DebugScriptLevels : std::uint8_t
```
Comment (MegadreamsBE) [inline Client/mods/deathmatch/logic/CScriptDebugging.cpp]: This is already defined in Shared/mods/deathmatch/logic/CScriptDebugging.cpp. Please make use of that one

File: Shared/mods/deathmatch/logic/CScriptDebugging.cpp [hunk 2]
```diff
@@ -70,24 +70,31 @@ void CScriptDebugging::LogPCallError(lua_State* luaVM, const SString& strRes, bo
...
         case MESSAGE_TYPE_INFO:
         case MESSAGE_TYPE_CUSTOM:
         case MESSAGE_TYPE_DEBUG:
-            sufficientDebugLevel = (playerDebugLevel == ALL);
-            break;
+            return playerDebugLevel == ALL;
+        default:
+            switch (messageDebugLevel)
+            {
+                case 1:
```
Comment (MegadreamsBE) [inline Shared/mods/deathmatch/logic/CScriptDebugging.cpp]: We should make use of the enum, instead of magic numbers.

**Review by MegadreamsBE — CHANGES_REQUESTED** [review]

**Review by ghost — APPROVED** [review]
Looks good

**Review by MegadreamsBE — APPROVED** [review]

File: Client/mods/deathmatch/logic/CScriptDebugging.cpp [hunk 3]
```diff
@@ -33,13 +33,13 @@ CScriptDebugging::~CScriptDebugging()
         fprintf(m_pLogFile, "INFO: Logging to this file ended\n");
 
         // if we have a flush timer
-        if (m_flushTimerHandle != NULL)
+        if (m_flushTimerHandle != nullptr)
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CScriptDebugging.cpp]: Can be reduced: `if (m_flushTimerHandle)`

File: Client/mods/deathmatch/logic/CScriptDebugging.cpp [hunk 4]
```diff
@@ -52,7 +52,7 @@ void CScriptDebugging::LogBadLevel(lua_State* luaVM, unsigned int uiRequiredLeve
 void CALLBACK TimerProc(void* lpParametar, BOOLEAN TimerOrWaitFired)
 {
     // Got a logfile?
-    if (CScriptDebugging::m_pLogFile != NULL)
+    if (CScriptDebugging::m_pLogFile != nullptr)
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CScriptDebugging.cpp]: Can be reduced: `if (CScriptDebugging::m_pLogFile)`

**Review by tederis — CHANGES_REQUESTED** [review]

File: Client/mods/deathmatch/logic/CScriptDebugging.cpp [hunk 5]
```diff
@@ -102,38 +102,46 @@ bool CScriptDebugging::SetLogfile(const char* szFilename, unsigned int uiLevel)
...
         }
+        
     #ifdef MTA_DEBUG
         if (!g_pCore->IsDebugVisible())
             return;
     #endif
-        g_pCore->DebugEchoColor(line.strText, line.ucRed, line.ucGreen, line.ucBlue);
+        
+        std::uint8_t clientDebugLevel = 0;
+        auto* pLocalPlayer = g_pClientGame->GetPlayerManager()->GetLocalPlayer();
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CScriptDebugging.cpp]: pLocalPlayer -> localPlayer

**Review by FileEX — CHANGES_REQUESTED** [review]

**Review by FileEX — APPROVED** [review]
