### PR TITLE
Appendum #3585 - shakeCamera

### LINKED ISSUE #3608: Impossible to disable shakeCamera
### Describe the bug

shakeCamera will run infinite, doesn't matter what u do - respawn or die - it won't reset

https://streamable.com/uyknty

### Steps to reproduce

shakeCamera(100)

### Version

22634

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TracerDS**
Resolves #3608 

Using `shakeCamera(0 or less)`, `resetShakeCamera()` will reset the effect

### CODE REVIEW

File: Client/game_sa/CCameraSA.cpp [hunk 1]
```diff
@@ -446,8 +446,14 @@ float CCameraSA::GetShakeForce()
 
 void CCameraSA::ShakeCamera(float radius, float x, float y, float z) noexcept
 {
-    DWORD               dwFunc = FUNC_ShakeCam;
-    CCameraSAInterface* cameraInterface = GetInterface();
+    static CCameraSAInterface* cameraInterface = GetInterface();
+    if (radius <= 0.0f)
+    {
+        cameraInterface->m_fCamShakeForce = 0;
```
Comment (FileEX) [inline Client/game_sa/CCameraSA.cpp]: 0.0f?

**Review by FileEX — APPROVED** [review]
If tested and works, then lgtm

File: Client/game_sa/CCameraSA.cpp (hunk 1 above)
Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp]: you mean `radius <= 0.0f` or `m_fCamShakeForce = 0`?

Comment (FileEX) [reply Client/game_sa/CCameraSA.cpp]: To keep literals consistent
```cpp
cameraInterface->m_fCamShakeForce = 0.0f;
```

File: Client/game_sa/CCameraSA.cpp [hunk 2]
```diff
@@ -446,8 +446,14 @@ float CCameraSA::GetShakeForce()
 
 void CCameraSA::ShakeCamera(float radius, float x, float y, float z) noexcept
 {
-    DWORD               dwFunc = FUNC_ShakeCam;
-    CCameraSAInterface* cameraInterface = GetInterface();
+    static CCameraSAInterface* cameraInterface = GetInterface();
```
Comment (TheNormalnij) [inline Client/game_sa/CCameraSA.cpp:449]: You don't need `static` here

File: Client/game_sa/CCameraSA.cpp [hunk 3]
```diff
@@ -446,8 +446,14 @@ float CCameraSA::GetShakeForce()
...
+    if (radius <= 0.0f)
+    {
+        cameraInterface->m_fCamShakeForce = 0.0f;
```
Comment (TheNormalnij) [inline Client/game_sa/CCameraSA.cpp]:
```suggestion
        GetInterface()->m_fCamShakeForce = 0.0f;
```

**Comment by AlexTMjugador** [comment]
Just my two cents for whoever reviews this: I've outlined a different approach to tackle this issue at https://github.com/multitheftauto/mtasa-blue/issues/3608#issuecomment-2255573894 and the following comments.

File: Client/game_sa/CCameraSA.cpp (hunk 2 above)
Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: it can be static so the variable wouldnt be allocated again

File: Client/game_sa/CCameraSA.cpp (hunk 3 above)
Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp]: I pass `cameraInterface` later in the inline assembly

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp]: ah, you can avoid it.
```c++
    CCameraSAInterface* cameraInterface = GetInterface();
    if (radius <= 0.0f)
    {
         // Remove shake effect
         cameraInterface->m_fCamShakeForce = 0.0f;
     }
    ((void(__thiscall*)(CCameraSAInterface*,  float radius, float x, float y, float z))0x50A9F0)(cameraInterface, radius, x, y, z);

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp]: This is less readable and conflicts with current SA definitions.
Its better to leave it as inline assembly for now

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp]: We are trying to avoid inline assembly for simple function calls.

- C++ is more readable and maintainable than assembly
- It's much easier to write c++ definition than assembly for developers
- It generates better code. Compiler cannot optimize functions with inline assembly
- You can avoid hacks with static variables

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp]: Technically, You should make `resetCameraShake` function to be consistent with current API.
+You should reset this effect when a player join a server

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp]: sure

File: Client/game_sa/CCameraSA.cpp (hunk 2 above)
Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: If this will not be static, the variable won't be allocated at all

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: it will be. It will live throughout the whole program.

> Block variables with static or thread(since C++11) storage duration are initialized the first time control passes through their declaration (unless their initialization is [zero-](https://en.cppreference.com/w/cpp/language/zero_initialization) or [constant-initialization](https://en.cppreference.com/w/cpp/language/constant_initialization), which can be performed before the block is first entered). On all further calls, the declaration is skipped. ([1](https://en.cppreference.com/w/cpp/language/storage_duration))

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: > If this will **not be static,**

This is what i mean. With out `static` it will be [esp+41C] or something

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: its still being allocated nonetheless. Static just makes one definition for all calls instead of one definition per call.

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: It won't be allocated, because compiler knows memory position for `internalInterface` at compile time

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: > It won't be allocated, because compiler knows memory position for `internalInterface` at compile time

but the allocation happens at runtime, not compile time. The definition is not evaluated at compile time.
The compiler still needs to allocate memory for the variable. It being static doesnt make much of a difference other than perseverance between calls

Comment (Merlin) [reply Client/game_sa/CCameraSA.cpp:449]: There is no memory allocation happening. GetInterface() just returns a pointer to the interface. 
Adding static will check TLS to see if camInterface is already initialized every time the function is called.
The function should not be noexcept since it calls a game function.

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: It doesnt matter what GetInterface returns.
The compiler needs to allocated memory on the stack for the `camInterface` variable. No need to do that X amount of times if `&GetInterface()` doesnt change.

Comment (Merlin) [reply Client/game_sa/CCameraSA.cpp:449]: The return value will be in eax and then moved into ecx to call the function. The compiler is unlikely to move this onto the stack.

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: It needs to be on the stack/somewhere in memory because the class member is modified from that exact variable.

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: It doesn't use an additional memory or stack. Maybe only one additional register will be used, but it's better than an additional branching from static variable

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: > it's better than an additional branching from static variable

what do you mean?

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: > Adding static will check TLS to see if camInterface is already initialized every time the function is called.

Comment (TracerDS) [reply Client/game_sa/CCameraSA.cpp:449]: Not adding static will define it each time the function runs.
When static is added, a new label in assembly is created for that variable so it can be referenced without allocating it on the stack each time. It is still allocated in memory

In any case cant do anything now. Static will stay

Comment (TheNormalnij) [reply Client/game_sa/CCameraSA.cpp:449]: > Not adding static will define it each time the function runs.

In this case a compiler is clever enough to replace variable allocation with direct memory access by offset. You didn't optimize here anything.
