### PR TITLE
Make engineRestreamWorld more aggressive

### LINKED ISSUE #3604: Latest nightly randomly crashes
### Describe the bug

https://mega.nz/file/0BwzSCoJ#zw7VyD0TvvWBWO3P7g_UW5JkZRgeaColCgcNLFpcjnE
Multi Theft Auto v1.6-release-22633

22628 works fine

### Steps to reproduce

maybe createBuilding or something cause it

### Version

Multi Theft Auto v1.6-release-22633

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #3604

Restores #3605 with fixes

### CODE REVIEW

File: Client/game_sa/CTxdPoolSA.cpp [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+    return (*m_ppTxdPoolInterface)->GetObjectIndex(pTxd);
+}
+
+void CTxdPoolSA::RemoveTextureDictonarySlot(std::uint32_t uiTxdId)
+{
+    if (!(*m_ppTxdPoolInterface)->IsContains(uiTxdId))
+        return;
+
+    typedef std::uint32_t(__cdecl * Function_TxdReleaseSlot)(std::uint32_t uiTxdId);
```
Comment (TracerDS) [inline Client/game_sa/CTxdPoolSA.cpp]: `using` instead of `typedef`:
```cpp
using Function_TxdReleaseSlot = std::uint32_t(__cdecl*)(std::uint32_t uiTxdId);
```

File: Client/game_sa/CTxdPoolSA.h [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+{
+public:
+    CTxdPoolSA();
+    ~CTxdPoolSA() = default;
+
+    std::uint32_t AllocateTextureDictonarySlot(std::uint32_t uiSlotID, std::string& strTxdName);
+    void          RemoveTextureDictonarySlot(std::uint32_t uiTxdId);
+    bool          IsFreeTextureDictonarySlot(std::uint32_t uiTxdId);
+
+    std::uint16_t GetFreeTextureDictonarySlot();
```
Comment (TracerDS) [inline Client/game_sa/CTxdPoolSA.h:27]: const?

File: Client/mods/deathmatch/logic/CClientModel.cpp [hunk 3]
```diff
@@ -216,7 +216,7 @@ void CClientModel::RestoreDFF(CModelInfo* pModelInfo)
 
 bool CClientModel::AllocateTXD(std::string &strTxdName)
 {
-    uint uiSlotID = g_pGame->GetPools()->AllocateTextureDictonarySlot(m_iModelID - MAX_MODEL_DFF_ID, strTxdName);
+    uint uiSlotID = g_pGame->GetPools()->GetTxdPool().AllocateTextureDictonarySlot(m_iModelID - MAX_MODEL_DFF_ID, strTxdName);
```
Comment (TracerDS) [inline Client/mods/deathmatch/logic/CClientModel.cpp]: `std::uint32_t`

File: Client/mods/deathmatch/logic/CClientModelManager.cpp [hunk 4]
```diff
@@ -73,7 +73,7 @@ int CClientModelManager::GetFirstFreeModelID(void)
 
 int CClientModelManager::GetFreeTxdModelID()
 {
-    ushort usTxdId = g_pGame->GetPools()->GetFreeTextureDictonarySlot();
+    ushort usTxdId = g_pGame->GetPools()->GetTxdPool().GetFreeTextureDictonarySlot();
```
Comment (TracerDS) [inline Client/mods/deathmatch/logic/CClientModelManager.cpp]: `std::uint16_t`

File: Client/sdk/game/CPools.h [hunk 5]
```diff
@@ -107,12 +108,7 @@ class CPools
...
-    virtual uint AllocateTextureDictonarySlot(uint uiSlotID, std::string& strTxdName) = 0;
-    virtual void RemoveTextureDictonarySlot(uint uiTxdID) = 0;
-    virtual bool IsFreeTextureDictonarySlot(uint uiTxdID) = 0;
-
-    virtual ushort GetFreeTextureDictonarySlot() = 0;
-
     virtual CBuildingsPool& GetBuildingsPool() noexcept = 0;
-    virtual CDummyPool&   GetDummyPool() noexcept = 0;
+    virtual CDummyPool&     GetDummyPool() noexcept = 0;
+    virtual CTxdPool&       GetTxdPool() noexcept = 0;
```
Comment (TracerDS) [inline Client/sdk/game/CPools.h]: Can you add const reference functions too?

File: Client/game_sa/CTxdPoolSA.cpp [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+    m_ppTxdPoolInterface = (CPoolSAInterface<CTextureDictonarySAInterface>**)0xC8800C;
+}
+
+std::uint32_t CTxdPoolSA::AllocateTextureDictonarySlot(std::uint32_t uiSlotId, std::string& strTxdName)
+{
+    CTextureDictonarySAInterface* pTxd = (*m_ppTxdPoolInterface)->AllocateAt(uiSlotId);
+    if (!pTxd)
+        return -1;
+
+    strTxdName.resize(24);
```
Comment (TracerDS) [inline Client/game_sa/CTxdPoolSA.cpp]: why 24?

**Review by TracerDS — CHANGES_REQUESTED** [review]

File: Client/game_sa/CTxdPoolSA.h (hunk 2 above)
Comment (TheNormalnij) [reply Client/game_sa/CTxdPoolSA.h:27]: GetFreeSlot is optimized in the pool template. it can't be const

File: Client/game_sa/CTxdPoolSA.cpp (hunk 1 above)
Comment (TheNormalnij) [reply Client/game_sa/CTxdPoolSA.cpp]: Refactor is unrelated to this PR. Im resolving all conversation related to CTxdPoolSA

**Review by botder — APPROVED** [review]
