### PR TITLE
Fix #1337 engineReplaceModel kicks the player out of the vehicle 

### LINKED ISSUE #1337: engineReplaceModel kicks the player out of the vehicle
**Describe the bug**
If you use engineReplaceModel() to model ID while you are on a vehicle with the same model ID, you will be warped out the vehicle.

**To reproduce**
Get inside a Perennial (404)

Run [this resource](https://github.com/multitheftauto/mtasa-blue/files/4409556/enginereplacebug.zip)
```lua
--clientside
function onStart()
        local txd,dff
	txd = engineLoadTXD("vehiculos/fiatuno.txd", 404) 
	engineImportTXD(txd, 404)
	dff = engineLoadDFF("vehiculos/fiatuno.dff", 404)
	engineReplaceModel(dff, 404)
end
addEventHandler("onClientResourceStart", resourceRoot, onStart)
```

**Expected behaviour**
The vehicle shouldn't kick you out

**Version**
Clientside: Windows 10 - v1.5.7-release-20462
Serverside: Windows 10 - v1.5.7-release-20462

**Additional context**
This also happens when using engineRestoreModel()

l33t

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1337 and adds a new property to setGlitchEnabled "kickoutofvehicle_onmodelreplace" to avoid breaking existing scripts. 

~~P.S Yeah, the git history is a mess, fixing it.~~

### CODE REVIEW

File: Client/mods/deathmatch/logic/CClientVehicle.cpp [hunk 1]
```diff
@@ -2981,14 +2981,19 @@ void CClientVehicle::Destroy()
...
         // Remove all the passengers physically
         for (unsigned int i = 0; i < 8; i++)
         {
-            if (m_pPassengers[i])
+            CClientPed* pPassenger = m_pPassengers[i];
+            if (pPassenger)
             {
-                m_pPassengers[i]->InternalRemoveFromVehicle(m_pVehicle);
+                pPassenger->InternalRemoveFromVehicle(m_pVehicle);
+                if (!g_pClientGame->IsGlitchEnabled(CClientGame::GLITCH_KICKOUTOFVEHICLE_ONMODELREPLACE))
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/CClientVehicle.cpp]: Does the compiler optimise this call and only call it once?

Comment (ghost) [reply Client/mods/deathmatch/logic/CClientVehicle.cpp]: Good catch. This needs to be fixed.

File: Client/mods/deathmatch/logic/CClientVehicle.cpp [hunk 2]
```diff
@@ -2981,14 +2981,19 @@ void CClientVehicle::Destroy()
...
+        bool bWarpInToVehicleRequired = !g_pClientGame->IsGlitchEnabled(CClientGame::GLITCH_KICKOUTOFVEHICLE_ONMODELREPLACE);
         for (unsigned int i = 0; i < 8; i++)
         {
-            if (m_pPassengers[i])
+            CClientPed* pPassenger = m_pPassengers[i];
+            if (pPassenger)
             {
-                m_pPassengers[i]->InternalRemoveFromVehicle(m_pVehicle);
+                pPassenger->InternalRemoveFromVehicle(m_pVehicle);
+                pPassenger->SetWarpInToVehicleRequired(bWarpInToVehicleRequired);
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/CClientVehicle.cpp:2996]: Should this be forced false?

**Review by qaisjp — APPROVED** [review]

File: Client/mods/deathmatch/logic/CClientVehicle.cpp (hunk 2 above)
Comment (ghost) [reply Client/mods/deathmatch/logic/CClientVehicle.cpp:2996]: No, it's not forced to false. I removed the check because I added a logical NOT  `!` 
Capture
If IsGlitchEnabled returns true, then bWarpInToVehicleRequired is false, and if it returns false, then bWarpInToVehicleRequired is true.

Comment (qaisjp) [reply Client/mods/deathmatch/logic/CClientVehicle.cpp:2996]: I mean, before the most recent commit, it would ONLY set true if the glitch was enabled. Now it sets it sets to true or false, depending on whether glitch was enabled. Wasn't sure if that was 100% intended / has side effects. I don't know the big picture of the vehicle entry process

Comment (ghost) [reply Client/mods/deathmatch/logic/CClientVehicle.cpp:2996]: You're right, but it still won't make any difference because when `InternalRemoveFromVehicle` is called, it will set m_bWarpInToVehicleRequired to false for the ped. 
https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CClientPed.cpp#L4186

And in this case, we're calling InternalRemoveFromVehicle before SetWarpInToVehicleRequired. Btw, SetWarpInToVehicleRequired only affects the bugged part of code that was causing issues with engineReplaceModel. It has no effect on other ped warping code.
