### PR TITLE
 Fix #1840: engineRequestModel crash on disconnect 

### LINKED ISSUE #1840: Crash on disconnect
**Describe the bug**
Crash.

**To reproduce**
1. Run this code
```lua
local id = engineRequestModel( "object" )

local object = Object( id, 0, 0, 5 )

addEventHandler( "onClientResourceStop", resourceRoot, function()
	object:destroy()
end )
localPlayer:setPosition( 0, 0, 4 )
```
2. Disconnect

**Version**
r20716 <=

**Additional context**
Only event onClientResourceStop will cause crash

### PR DESCRIPTION
**Pull request by ghost**
There is an issue with entity deletion order when using `engineRequestModel`. Every model in GTA SA has its own "model info" struct in `CModelInfo::ms_modelInfoPtrs`. When a resource is being unloaded, the custom model info struct gets deleted while it's still in use by peds, vehicles, or objects, and this causes a crash. This also fixes the memory leak problem with CClientModel. When memory for CClientModel is allocated using engineRequestModel, it is never freed.

### CODE REVIEW

File: Client/mods/deathmatch/logic/CClientModel.cpp [hunk 1]
```diff
@@ -67,13 +61,16 @@ bool CClientModel::Deallocate(void)
...
     if (!m_bAllocatedByUs)
         return false;
-
     CModelInfo* pModelInfo = g_pGame->GetModelInfo(m_iModelID, true);
-
-    // ModelInfo must be valid
     if (!pModelInfo->IsValid())
         return false;
+    pModelInfo->DeallocateModel();
+    this->SetParentResource(nullptr);
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientModel.cpp]: `SetParentResource`

File: Client/mods/deathmatch/logic/CClientModelManager.cpp [hunk 2]
```diff
@@ -77,14 +70,14 @@ CClientModel* CClientModelManager::FindModelByID(int iModelID)
     return nullptr;
 }
 
-std::vector<CClientModel*> CClientModelManager::GetModelsByType(const eClientModelType type, const unsigned int minModelID)
+std::vector<std::shared_ptr<CClientModel>> CClientModelManager::GetModelsByType(eClientModelType type, const unsigned int minModelID)
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientModelManager.cpp:73]: Nitpicky, but I'd say using a `ModeList_t` would be a better option here.
Or just move the return type to the rhs.

File: Client/mods/deathmatch/logic/CClientModelManager.cpp [hunk 3]
```diff
@@ -77,14 +70,14 @@ CClientModel* CClientModelManager::FindModelByID(int iModelID)
...
+    std::vector<std::shared_ptr<CClientModel>> found;
     found.reserve(m_modelCount);
 
     for (int i = minModelID; i < MAX_MODEL_ID; i++)
     {
-        CClientModel* model = m_Models[i];
+        std::shared_ptr<CClientModel> model = m_Models[i];
         if (model && model->GetModelType() == type)
         {
             found.push_back(model);
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientModelManager.cpp]: I think this loop can be refactored to be a range based for loop.
I didnt do it for whatever reason back then.
If you decide to keep it this way, make sure `std::shared_ptr<CClientModel> model` is a `const std::shared_ptr<CClientModel>&` or even better `const auto& model` here, because theres no need (yet) to copy the shared ptr (as it's not as cheap as copying a pointer).

File: Client/mods/deathmatch/logic/CClientModelManager.h [hunk 4]
```diff
@@ -23,24 +24,23 @@ class CClientModelManager
     friend class CClientModel;
 
 public:
-    CClientModelManager(class CClientManager* pManager);
+    CClientModelManager(class CClientManager* pManager) {}
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientModelManager.h]: `= default`

File: Client/mods/deathmatch/logic/CClientModelManager.h [hunk 5]
```diff
@@ -23,24 +24,23 @@ class CClientModelManager
...
+    std::shared_ptr<CClientModel> FindModelByID(int iModelID);
 
+    std::vector<std::shared_ptr<CClientModel>> GetModelsByType(eClientModelType type, const unsigned int minModelID = 0);
 
     void DeallocateModelsAllocatedByResource(CResource* pResource);
 
 private:
-    CClientModel* m_Models[MAX_MODEL_ID];
-    unsigned int m_modelCount = 0;
+    std::shared_ptr<CClientModel> m_Models[MAX_MODEL_ID];
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientModelManager.h:44]: Perhaps we could use `std::array` instead?
All of it's elements are default initalized, so we woudn't need to null it out in the ctor.

File: Client/mods/deathmatch/logic/CClientPed.h [hunk 6]
```diff
@@ -737,4 +738,5 @@ class CClientPed : public CClientStreamElement, public CAntiCheatModule
     bool              m_bTaskToBeRestoredOnAnimEnd;
     eTaskType         m_eTaskTypeToBeRestoredOnAnimEnd;
     bool              m_bWarpInToVehicleRequired = false;
+    std::shared_ptr<CClientModel> m_clientModel;
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/CClientPed.h:741]: Indentation.

File: Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp [hunk 7]
```diff
@@ -28,7 +28,7 @@ int CLuaFunctionDefs::GetValidPedModels(lua_State* luaVM)
 
     // Gather our custom skin model IDs allocated with engineRequestModel
     // (there might be some < 313 as well, and since we don't want duplicates, we start at 313, others are already included by the loop above)
-    for (const CClientModel* model : m_pManager->GetModelManager()->GetModelsByType(eClientModelType::PED, 313)) 
+    for (auto model : m_pManager->GetModelManager()->GetModelsByType(eClientModelType::PED, 313))
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp]: `const auto&`, again, no need to copy the shared ptr, as its locked already by the vector.

File: Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp [hunk 8]
```diff
@@ -582,10 +582,10 @@ int CLuaEngineDefs::EngineRequestModel(lua_State* luaVM)
             {
                 int iModelID = m_pManager->GetModelManager()->GetFirstFreeModelID();
                 if (iModelID != INVALID_MODEL_ID) {
-                    CClientModel* pModel = m_pManager->GetModelManager()->FindModelByID(iModelID);
+                    std::shared_ptr<CClientModel> pModel = m_pManager->GetModelManager()->FindModelByID(iModelID);
                     if (pModel == nullptr)
-                        pModel = new CClientModel(m_pManager, iModelID, eModelType);
-
+                        pModel = std::make_shared<CClientModel>(m_pManager, iModelID, eModelType);
+                    m_pManager->GetModelManager()->Add(pModel);
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp:588]: Let's move this to `CClientModelManager` instead, this doesnt belong to the API code.

File: Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp [hunk 9]
```diff
@@ -631,9 +631,9 @@ int CLuaEngineDefs::EngineFreeModel(lua_State* luaVM)
 
     if (!argStream.HasErrors())
     {
-        CClientModel* pModel = m_pManager->GetModelManager()->FindModelByID(iModelID);
-
-        if (pModel && pModel->Deallocate())
+        auto modelManager = m_pManager->GetModelManager();
+        std::shared_ptr<CClientModel> pModel = modelManager->FindModelByID(iModelID);
+        if (pModel && modelManager->Remove(pModel))
```
Comment (Pirulax) [inline Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp:636]: I'd argue that adding a function to remove a model by ID would be a better solution.

**Review by Pirulax — COMMENTED** [review]
If you want I can commit the suggestions.

**Comment by Dutchman101** [comment]
We should try to merge this ASAP, because together with PR #1847 it will make nightlies stable again.

**Comment by Pirulax** [comment]
In that case merge it asap, we can do the suggested changes later.

**Comment by Dutchman101** [comment]
> In that case merge it asap, we can do the suggested changes later.

It can easily wait until saml1er checked out the review, he doesn't take that long. I meant we should ideally merge it within a few days

File: Client/mods/deathmatch/logic/CClientModelManager.cpp [hunk 10]
```diff
@@ -10,45 +10,38 @@
...
-bool CClientModelManager::Remove(CClientModel* pModel)
+bool CClientModelManager::Remove(const std::shared_ptr<CClientModel>& pModel)
 {
-    if (pModel && m_Models[pModel->GetModelID()] != nullptr)
+    int modelId = pModel ? pModel->GetModelID() : 0;
+    if (pModel && m_Models[modelId] != nullptr)
     {
-        m_Models[pModel->GetModelID()] = nullptr;
+        m_Models[modelId]->RestoreEntitiesUsingThisModel();
+        m_Models[modelId] = nullptr;
```
Comment (qaisjp) [inline Client/mods/deathmatch/logic/CClientModelManager.cpp]: Something looks weird here. Should this just return false if pModel is null?

**Review by qaisjp — COMMENTED** [review]
mostly looks good. pirulax has some good comments.

File: Client/mods/deathmatch/logic/CClientModelManager.cpp (hunk 10 above)
Comment (Pirulax) [reply Client/mods/deathmatch/logic/CClientModelManager.cpp]: Ah yes, indeed

Comment (ghost) [reply Client/mods/deathmatch/logic/CClientModelManager.cpp]: We shouldn't be verifying a reference in the first place. I'll remove the check.

File: Client/mods/deathmatch/logic/CClientModelManager.h (hunk 5 above)
Comment (ghost) [reply Client/mods/deathmatch/logic/CClientModelManager.h:44]: An array of shared_ptr is initialized to nullptr by default. The standard guarantees it.

File: Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp (hunk 9 above)
Comment (ghost) [reply Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp:636]: `CClientModelManager::Remove` will use the model id to free the reference. It really doesn't matter if we get the model id outside the function or inside the function.

**Comment by ghost** [comment]
Some of the suggestions by Pirulax requires me to refactor the old code. This PR is more of a crash fix rather than a refactor. I think it would be better to do this in a separate PR (which I probably won't do).

About `shared_ptr<T> const&` there are discussions online against using const& for shared_ptr mainly due to safety. Some suggest that it affects performance. The performance penalty is really not much of a problem, it depends on the situation. Effect C++ book states `Item 20: Prefer pass-by-reference-to-const to pass-by-value` There's a [good article](https://medium.com/@vgasparyan1995/pass-by-value-vs-pass-by-reference-to-const-c-f8944171e3ce) that suggests shared_ptr is an exception to this rule because it can be unsafe in some situations, and it's easy to make a mistake.

**Review by qaisjp — APPROVED** [review]
I agree, and that makes sense. This looks good. :shipit:

File: Client/mods/deathmatch/logic/CClientModelManager.h (hunk 5 above)
Comment (Pirulax) [reply Client/mods/deathmatch/logic/CClientModelManager.h:44]: Ah, I thought we still have a `memset` for the array. My bad.

File: Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp (hunk 9 above)
Comment (Pirulax) [reply Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp:636]: Yes, but `Remove` could do this mess, instead of us.
(Also, its a little slower because of the shared ptr copy, but its negligible)

**Comment by Pirulax** [comment]
Yeah, but in the case of the `vector` loop the `const&` still stands, as the vector won't be deallocated (thus the `shared_ptr` references released) until the loop is done.
Anyways, this is only a fix, not a refactor, so you're right in the end.
