### PR TITLE
Fix #2545: isElementInWater in vehicles (client)

### LINKED ISSUE #2545: isElementInWater in vehicles
**Describe the bug**
isElementInWater returns false if ped or player is in vehicle - Returns true only for the vehicle. 
**This bug occurs only on client side**

**To reproduce**
1. Get vehicle
2. Drive into the water 
3. 
```lua
print(isElementInWater(me)) -- false
print(isElementInWater(me.vehicle)) -- true
```

**Expected behaviour**
isElementInWater should returns true also for peds/players which are in vehicle in water

**Screenshots**

**Version**
1.5.9

**Additional context**

### PR DESCRIPTION
**Pull request by matheustkn**
Fixed issue #2545

### CODE REVIEW

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 1]
```diff
@@ -766,8 +766,16 @@ bool CStaticFunctionDefinitions::IsElementInWater(CClientEntity& Entity, bool& b
...
+            if (Ped.GetOccupiedVehicle())
+            {
+                bInWater = Ped.GetOccupiedVehicle()->IsInWater();
+                break;
+            }
+            else
+            {
+                bInWater = Ped.IsInWater();
+                break;
+            }
```
Comment (r12750) [inline Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:778]: Have you tried to put the 'break' down here? What would you put your case there?

Comment (androksi) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:778]: This is the pattern that this repository uses. I don't think that changing it would be a good choice. Clone this repo. to see how things work - it's an important decision to make when it comes to reviewing a PR.

**Review by patrikjuvonen — APPROVED** [review]

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp (hunk 1 above)
Comment (Lpsd) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp:778]: not sure if this was the point being made - but it would be cleaner with a single break, infact the whole condition is perfectly readable as two lines:

```cpp
bInWater = Ped.GetOccupiedVehicle() ? Ped.GetOccupiedVehicle()->IsInWater() : Ped.IsInWater();
break;
```

down to preference I guess
