### PR TITLE
 Fix HUD size when playing on widescreen

### LINKED ISSUE #848: Widescreen Hud Placement
On MTA the original HUD takes too much of your screen, even if you turn on the option in settings that should adjust the proportions of it. It's just way too big, you can see in this thread how the HUD looks like on singleplayer or samp with widescreen fix made by thirteenag. https://forum.mtasa.com/topic/103042-widescreen-fix-for-mta/?_fromLogin=1

### LINKED ISSUE #2753: Ultrawidescreen (32:9) HUD and FOV issue
### Describe the bug

Camera FOV seems to be based off screen width instead of screen height, thus cropping view on the top and bottom when using a wider screen instead of extending the view on the sides.
HUD is also based off width to control the scaling, instead so instead of "extending" the HUD on the left and right of the screen while preserving the scaling of the height, it gets twice as big on a 32:9 compared to a 16:9.
Single player with ThirteenAG's wide screen fix doesn't have this issue. 
Using the FOV slider doesn't improve the situation, as it is clamped to 90° (horizontal), so to have a the same 59° of vertical FOV (for a 90° horizontal FOV on 16:9), it would need to be set at 127° (horizontal) on a 32:9.

Comparison:
GTA SA solo ultrawidescreen
MTA SA ultrawidescreen

### Steps to reproduce

1. Launch the game
2. Set the video resolution to a 32:9 aspect
3. Reboot the game to apply the resolution change
4. Launch a server or map editor
5. Observe the low FOV and big HUD.

### Version

Client: version 1.5.9-release-21324

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by henrymarques**
Fix #848, maybe fix #2753
There's nothing new, most part of the code is from ThirteenAG's widescreen fix (thanks).

This is a draft pull request because it needs more testing. If you can test it, please, send me feedback.
I need feedback about the code too.

### CODE REVIEW

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 1]
```diff
@@ -0,0 +1,1111 @@
...
+ *  LICENSE:     See LICENSE in the top level directory
+ *  FILE:        multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp
+ *
+ *  Multi Theft Auto is available from https://www.multitheftauto.com/
+ *
+ *****************************************************************************/
+
+#include "StdInc.h"
+
+struct RsGlobal
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: In the context of this PR, some fields are not used (frameLimit, quit, ps). In addition, this structure is incomplete relative to the SA code. If we do not need the remaining fields, use only those that are necessary.

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 2]
```diff
@@ -0,0 +1,1111 @@
...
+        0x582DC1,            // 14 Legend
+        0x582ED3,            // 15 Legend
+        0x582FA3,            // 16 Legend
+        0x582FF5,            // 17 Legend
+        0x583079,            // 18 Legend
+        0x5830F6,            // 19 Legend
+        0x58317B,            // 20 Legend
+        0x576119,            // 21 Legend
+        0x575EB7,            // 22 Map zones
+        NULL,                // 23
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: What is the purpose of these empty indexes in arrays?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 3]
```diff
@@ -0,0 +1,1111 @@
...
+        0x719C58,            // 23 Font fixes
+        0x728864,            // 24 BarChart fixes
+        0x7288A9,            // 25 BarChart fixes
+        0x573F7D,            // 26 DrawWindow header
+        0x573FD6,            // 27 DrawWindow header
+    };
+
+    for (int i = 0; i < sizeof(m_dwMiscWidth) / sizeof(const void*); i++)
+    {
+        if (m_dwMiscWidth[i] != NULL)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Why are there NULLs in the array that are checked here?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 4]
```diff
@@ -0,0 +1,1111 @@
...
+float fHUDWidth[120], fHUDHeight[120];
+float fCameraWidth[2], fCameraHeight[2];
+
+float fWideScreenWidthScale = 1.0f;
+float fWideScreenHeightScale = 1.0f;
+
+static const float fHudHeightScale = 1.0f;
+static const float fHudWidthScale = 1.0f;
+static const float fRadarWidthScale = 1.0f;
+static const float fRadarHeightScale = 1.0f;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: constexpr will be better imo

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 5]
```diff
@@ -0,0 +1,1111 @@
...
+    fHUDHeight[16] /= 1.125f;
+}
+
+void UpdateScreenAspectRatio()
+{
+    fWideScreenWidthScale = 640.0f / (*(pfScreenAspectRatio) * 448.0f);
+    fWideScreenHeightScale = 448.0 / 448.0f;
+    fWideScreenWidthProperScale = static_cast<float>(pRsGlobal->width) / (*pfScreenAspectRatio * 448.0f);
+    fWideScreenHeightProperScale = static_cast<float>(pRsGlobal->height) / 448.0f;
+    fDefaultWidth = (4.0f / 3.0f);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: This variable can be defined at the top as a constant

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 6]
```diff
@@ -0,0 +1,1111 @@
...
+    fMiscHeight[28] = 0.002232143f * fWideScreenHeightScale * fHudHeightScale;
+}
+
+void UpdateScriptFixes()
+{
+    float w;
+    if (*pfScreenAspectRatio < fDefaultWidth)
+        w = static_cast<float>(pRsGlobal->width);
+    else
+        w = pRsGlobal->width * fDefaultWidth / *pfScreenAspectRatio;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: You can use the conditional operator (? :) here for better readability and make "w" as constant

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 7]
```diff
@@ -0,0 +1,1111 @@
...
+    fRadarWidth[1] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[2] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[3] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[4] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[5] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[6] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[7] = 0.0015625f * fWideScreenWidthScale * fRadarWidthScale;
+    fRadarWidth[8] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fRadarWidth[9] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fRadarWidth[10] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: You can declare these magic numbers (0.0015625f, 0.0015625f, 0.002232143f) etc. as a constant variable

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 8]
```diff
@@ -0,0 +1,1111 @@
...
+        return (float)pRsGlobal->width * fValue * 0.0015625f;
+}
+
+float __stdcall StretchYHook(float fValue)
+{
+    if (pRsGlobal->height == 448)
+        return fValue;
+    else
+        return (float)pRsGlobal->height * fValue * 0.002232143f;
+}
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: You can use the conditional operator (? :) here for better readability. What do you think about static_cast here?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 9]
```diff
@@ -0,0 +1,1111 @@
...
+        NULL,                // 33
+        NULL,                // 34
+        NULL,                // 35
+        NULL,                // 36
+        NULL,                // 37
+        0x5849FA,            // 38 DrawYouAreHereSprite
+        0x574096,            // 39 Message screen
+    };
+
+    for (int i = 0; i < sizeof(m_dwFrontendWidth) / sizeof(const void*); i++)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: size_t and you can use std::size. instead of sizeof. You also don't need sizeof(const void*)

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 10]
```diff
@@ -0,0 +1,1111 @@
...
+    {
+        if (m_dwFrontendWidth[i] != NULL)
+            MemPut<const void*>(m_dwFrontendWidth[i] + 0x2, &fFrontendWidth[i]);
+    }
+
+    for (int i = 0; i < sizeof(m_dwFrontendHeight) / sizeof(const void*); i++)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Above

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 11]
```diff
@@ -0,0 +1,1111 @@
...
+        NULL,                // 36
+        NULL,                // 37
+        0x5849FA,            // 38 DrawYouAreHereSprite
+        0x574096,            // 39 Message screen
+    };
+
+    for (int i = 0; i < sizeof(m_dwFrontendWidth) / sizeof(const void*); i++)
+    {
+        if (m_dwFrontendWidth[i] != NULL)
+            MemPut<const void*>(m_dwFrontendWidth[i] + 0x2, &fFrontendWidth[i]);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:680]: The pointer type here should be float because the values ​​at these addresses are of type float. In addition, why do you pass the address of the value to memory, instead of the values ​​themselves?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 12]
```diff
@@ -0,0 +1,1111 @@
...
+        if (m_dwFrontendHeight[i] != NULL)
+            MemPut<const void*>(m_dwFrontendHeight[i] + 0x2, &fFrontendHeight[i]);
+    }
+
+    // StretchXY Restoration
+    int m_dwCallWidth[] = {
+        0x57E3A5, 0x577CB7, 0x577CD0, 0x577D6F, 0x577D99, 0x577DAB, 0x577FA6, 0x578031, 0x578052, 0x5780E1, 0x5788DF, 0x5788FB,
+    };
+
+    int m_dwCallHeight[] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: If the array size is constant, it is worth specifying it

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 13]
```diff
@@ -0,0 +1,1111 @@
...
+    }
+
+    for (int i = 0; i < sizeof(m_dwFrontendHeight) / sizeof(const void*); i++)
+    {
+        if (m_dwFrontendHeight[i] != NULL)
+            MemPut<const void*>(m_dwFrontendHeight[i] + 0x2, &fFrontendHeight[i]);
+    }
+
+    // StretchXY Restoration
+    int m_dwCallWidth[] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: uintptr_t?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 14]
```diff
@@ -0,0 +1,1111 @@
...
+    {
+        if (m_dwCrosshairWidth[i] != NULL)
+            MemPut<const void*>(m_dwCrosshairWidth[i] + 0x2, &fMiscWidth[0]);
+    }
+
+    for (int i = 0; i < sizeof(m_dwCrosshairHeight) / sizeof(const void*); i++)
+    {
+        if (m_dwCrosshairHeight[i] != NULL)
+            MemPut<const void*>(m_dwCrosshairHeight[i] + 0x2, &fMiscHeight[0]);
+    }
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Same as above

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 15]
```diff
@@ -0,0 +1,1111 @@
...
+    {
+        if (m_dwRadarWidth[i] != NULL)
+            MemPut<const void*>(m_dwRadarWidth[i] + 0x2, &fRadarWidth[i]);
+    }
+
+    for (int i = 0; i < sizeof(m_dwRadarHeight) / sizeof(const void*); i++)
+    {
+        if (m_dwRadarHeight[i] != NULL)
+            MemPut<const void*>(m_dwRadarHeight[i] + 0x2, &fRadarHeight[i]);
+    }
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Same

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 16]
```diff
@@ -0,0 +1,1111 @@
...
+    // Lock Subtitles Width
+    static float fSubtitlesMult = 1.0f;
+    MemPut<const void*>(0x58C4E8 + 0x2, &fSubtitlesMult);
+    */
+
+    // Second player fix.
+    MemPut<const void*>(0x58F9A0 + 0x2, &fHUDWidth[110]);            // Weapon icon X
+    MemPut<const void*>(0x58F993 + 0x2, &fHUDWidth[16]);             // Weapon icon X
+    MemPut<const void*>(0x58F972 + 0x2, &fHUDHeight[16]);            // Weapon icon Y
+    MemPut<const void*>(0x58FA8E + 0x2, &fHUDWidth[17]);             // Ammo x
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:1100]: Use type float. Why do you put the addresses of the values ​​in memory instead of the values ​​themselves directly?

**Review by FileEX — CHANGES_REQUESTED** [review]
It's nice that you are willing to do it. There are still a lot of things to improve, better readability, etc. Personally, I don't like these huge address tables. 

Keep it up!

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 5 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I mean fDefaultWidth

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 17]
```diff
@@ -0,0 +1,1111 @@
...
+        0x57A3EB,            // 13 Menu text
+        0x582DDB,            // 14 Legend
+        0x582E0D,            // 15 Legend
+        0x582EB0,            // 16 Legend
+        0x583019,            // 17 Legend
+        0x58309C,            // 18 Legend
+        0x582F82,            // 19 Legend
+        0x583128,            // 20 Legend
+        0x5831AD,            // 21 Legend
+        0x57613B,            // 22 Legend
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I don't think we need to apply the fix for menu, legend, subtitles, wasted, busted etc

**Review by FileEX — CHANGES_REQUESTED** [review]

**Comment by henrymarques** [comment]
I've read all the reviews, I will reply and work on the changes when I have a break

**Comment by Fernando-A-Rocha** [comment]
thank you for your work, i hope this is finished :D 

hud looks like this without your PR, stretched and too big 😔 
image

**Comment by Fernando-A-Rocha** [comment]
vs on samp with widescreen hud fix

image

**Comment by DomenicF** [comment]
Thanks for working on this!

Just curious if this fix also covers FoV issues (reported in #2753) or if the fix would be a totally separate thing?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 1 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: honestly, I've kept this because I was not sure if it would work without this fields, I took it off and it works

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 13 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: changed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 2 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: removed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 3 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: removed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 4 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: changed and removed static

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 5 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: accepted

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 8 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: it will be not used anymore, static cast would be better tho

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 17 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: removed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 7 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: These magic numbers are also magic to me, I will try but there's a lot through the code

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 6 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: reviewing the code I realize this function is not used

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 7 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Therefore, you do not need to document them. Just list the ones that are repeated many times as variables like "RadarWidth_Mult" etc

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 4 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Static here makes sense, so don't remove it. Just change const to constexpr

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 12 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: agreed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 9 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: changed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 18]
```diff
@@ -0,0 +1,1111 @@
...
+void UpdateMiscFixes();
+void UpdateHUDFixes();
+void UpdateScriptFixes();
+
+float AdjustFOV(float f, float ar)
+{
+    return std::round((2.0f * atan(((ar) / (4.0f / 3.0f)) * tan(f / 2.0f * ((float)M_PI / 180.0f)))) * (180.0f / (float)M_PI) * 100.0f) / 100.0f;
+}
+
+void __declspec(naked) CalculateAimingPoint()
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Unused

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 19]
```diff
@@ -0,0 +1,1111 @@
...
+
+void InstallAspectRatioFixes();
+void InstallFrontendFixes();
+void InstallMiscFixes();
+void InstallHUDFixes();
+
+void UpdateFrontendFixes();
+void UpdateMiscFixes();
+void UpdateHUDFixes();
+void UpdateScriptFixes();
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: These definitions can be removed because the functions are declared below

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 20]
```diff
@@ -0,0 +1,1111 @@
...
+    fHUDWidth[12] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[13] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[14] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[15] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[16] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[17] = 0.17343046f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[18] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[19] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[20] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
+    fHUDWidth[21] = 0.0015625f * fWideScreenWidthScale * fHudWidthScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: According to the coding guidelines, we no longer use Hungarian notation

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 4 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I just put it back. Could you say more about `static`? it's lifecycle thing, I guess, but I don't get it

Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: The static keyword restricts the visibility of a variable or function to the source file and ensures that the variable is allocated at program start and remains in memory for the program's entire duration

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 7 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: those that repeated many times became two variables, WidthMult and HeightMult, the remaining still being a magic number on the code because they do not repeat more than twice

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 4 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: thanks

**Comment by henrymarques** [comment]
> Just curious if this fix also covers FoV issues [...] or if the fix would be a totally separate thing?

Not yet, it's not totally separate thing but I think I will open another pull request to this

**Comment by henrymarques** [comment]
Everything seems to work correctly, but I would like if another dev could test this

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 21]
```diff
@@ -0,0 +1,730 @@
...
+        0x589D61,            // 45 Stats box
+        0x589E49,            // 46 Stats box
+        0x589F31,            // 47 Stats box
+        0x58A013,            // 48 Stats box
+        0x58A090,            // 49 Stats box
+        0x58A134,            // 50 Stats box
+        0x58C863,            // 51 SuccessFailed text
+        0x58D2DB,            // 52 MissionTitle text
+        0x58D459,            // 53 MissionTitle text
+        0x58CBC1,            // 54 WastedBusted text
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Stats box, mission title, wasted, busted, helptext are unused in MTA. Probably things like timers, menu system, OddJob, TripleSkip, CDarkel, CGarages are also unused in MTA. You should go through these addresses and leave only what makes sense for the MTA

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 22]
```diff
@@ -0,0 +1,730 @@
...
+        0x5810EF,            // 74
+        0x581158,            // 75
+        0x5811CD,            // 76
+        0x58148A,            // 77
+        0x5814F7,            // 78
+        0x5815B1,            // 79
+        0x5815EB,            // 80
+        0x581633,            // 81
+        0x47AD2A,            // 82
+        0x5818CF,            // 83
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Undocumented

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 23]
```diff
@@ -0,0 +1,730 @@
...
+        0x58BFCB,            // 64 Help text
+        0x580E11,            // 65 Menu system
+        0x580F85,            // 66
+        0x5810CC,            // 67
+        0x581132,            // 68
+        0x5811A1,            // 69
+        0x58147A,            // 70
+        0x5814E7,            // 71
+        0x581699,            // 72
+        0x581889,            // 73
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Undocumented

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 24]
```diff
@@ -0,0 +1,730 @@
...
+        0x58B263,            // 56 Timers
+        0x58B5DE,            // 57 Timers
+        0x58B7BD,            // 58 Help text
+        0x58BA4C,            // 59 Help text
+        0x58BBA7,            // 60 Help text
+        0x58BD19,            // 61 Help text
+        0x58BE2B,            // 62 Help text
+        0x58BF1C,            // 63 Help text
+        0x58BFCB,            // 64 Help text
+        0x580E11,            // 65 Menu system
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Same as above

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 25]
```diff
@@ -0,0 +1,730 @@
...
+        0x58A9BD,            // Radar point
+        0x5834EC,            // Radar point
+        0x586058,            // Radar centre
+        0x584346,            // Radar Trace 0
+        0x58440C,            // Radar Trace 0
+        0x58412B,            // Radar Trace 2
+        0x5841B0,            // Radar Trace 2
+        0x584207,            // Radar Trace 1
+        0x5842C6,            // Radar Trace 1
+        0x5876BC, 0x587733, 0x587916, 0x587A02, 0x587A92,
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Uncodumented

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 26]
```diff
@@ -0,0 +1,730 @@
...
+        0x5834BA,                      // Radar point
+        0x58603F,                      // Radar point
+        0x5886CC,                      // Radar centre
+        0x58439C,                      // Radar Trace 0
+        0x584434,                      // Radar Trace 0
+        0x58410B,                      // Radar Trace 2
+        0x584190,                      // Radar Trace 2
+        0x584249,                      // Radar Trace 1
+        0x5842E6,                      // Radar Trace 1
+        0x5876D4, 0x58774B, 0x58780A, 0x58788F, 0x58792E, 0x587A1A, 0x587AAA,
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Uncodumented

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 27]
```diff
@@ -0,0 +1,730 @@
...
+static constexpr float HudWidthScale = 1.0f;
+static constexpr float HudHeightScale = 1.0f;
+static constexpr float RadarWidthScale = 1.0f;
+static constexpr float RadarHeightScale = 1.0f;
+
+constexpr float WidthMult = 0.0015625f;
+constexpr float HeightMult = 0.002232143f;
+
+float* ScreenAspectRatio;
+float* ScreenFieldOfView;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Unused variable - float* ScreenFieldOfView;

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 27 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: removed

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 26 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: added

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 25 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: added

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 24 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: unused

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 23 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: unused

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 22 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: unused

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 21 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: changed

**Comment by henrymarques** [comment]
At this point, HUD size can be changed back switching aspect ratio to 4:3 on video settings, I don't know if this setting change could have side effects elsewhere than HUD. If this happen, please tell me, so I will think how to solve with "HUD match aspect ratio" setting checkbox. I will work on fov fix now

EDIT:
> [...] I don't know if this setting change could have side effects elsewhere than HUD.

It has, but I found a way to solve using "HUD match aspect ratio" checkbox. I don't think it's the better way but it works, also, unfortunetly the game needs to restart to apply changes. I can commit it as is to this PR if someone thinks it is needed

**Comment by Fernando-A-Rocha** [comment]
Related to #3582 ?

**Comment by henrymarques** [comment]
> Related to #3582 ?

You can see the changes [here](https://github.com/henrymarques/mtasa-blue/commit/4254ce23faccf7ea85fcc094b0573699465ee329), I don't think it's the better way to do this, so I didn't include in this PR

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 28]
```diff
@@ -0,0 +1,416 @@
...
+static constexpr float ScreenHeightScale = 1.0f;
+
+static constexpr float HudWidthScale = 1.0f;
+static constexpr float HudHeightScale = 1.0f;
+static constexpr float RadarWidthScale = 1.0f;
+static constexpr float RadarHeightScale = 1.0f;
+/* NOTE: Changing hud and radar scales may misalign elements */
+
+constexpr float WidthMult = 0.0015625f;
+constexpr float HeightMult = 0.002232143f;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: static?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 29]
```diff
@@ -0,0 +1,416 @@
...
+#ifndef M_PI
+    #define M_PI 3.14159265358979323846
+#endif
+
+float MiscWidth[30], MiscHeight[30];
+float RadarWidth[23], RadarHeight[23];
+float HUDWidth[39], HUDHeight[34];
+float CameraWidth[1];
+
+float                  ScreenWidthScale = 1.0f;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: static?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 30]
```diff
@@ -0,0 +1,416 @@
...
+#include "StdInc.h"
+
+#ifndef M_PI
+    #define M_PI 3.14159265358979323846
+#endif
+
+float MiscWidth[30], MiscHeight[30];
+float RadarWidth[23], RadarHeight[23];
+float HUDWidth[39], HUDHeight[34];
+float CameraWidth[1];
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: static?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 31]
```diff
@@ -0,0 +1,416 @@
...
+    RadarWidth[13] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[14] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[15] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[16] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[17] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[18] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[19] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[20] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[21] = WidthMult * ScreenWidthScale * HudWidthScale;
+    RadarWidth[22] = WidthMult * ScreenWidthScale * HudWidthScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]:
```cpp
for (std::size_t i = 0; i < std::size(RadarWidth); i++)
    RadarWidth[i] = (i == 6 ? 0.0015000f : WidthMult) * ScreenWidthScale * HudWidthScale
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 32]
```diff
@@ -0,0 +1,416 @@
...
+    RadarHeight[12] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[13] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[14] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[15] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[16] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[17] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[18] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[19] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[20] = HeightMult * ScreenHeightScale * HudHeightScale;
+    RadarHeight[21] = HeightMult * ScreenHeightScale * HudHeightScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]:
```cpp
for (std::size_t i = 0; i < std::size(RadarHeight); i++)
    RadarHeight[i] = HeightMult * ScreenHeightScale * HudHeightScale;
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 33]
```diff
@@ -0,0 +1,416 @@
...
+    HUDWidth[30] = 0.0019350f * ScreenWidthScale;
+    HUDWidth[31] = WidthMult * ScreenWidthScale * HudWidthScale;
+    HUDWidth[32] = WidthMult * ScreenWidthScale * HudWidthScale;
+    HUDWidth[33] = 0.0019500f * ScreenWidthScale;
+    HUDWidth[34] = WidthMult * ScreenWidthScale * HudWidthScale;
+    HUDWidth[35] = WidthMult * ScreenWidthScale * HudWidthScale;
+    HUDWidth[36] = WidthMult * ScreenWidthScale * HudWidthScale;
+    HUDWidth[37] = WidthMult * ScreenWidthScale * HudWidthScale;
+
+    HUDWidth[38] = 1920.0f * 0.17343046f * ScreenWidthScale * HudWidthScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]:
```cpp
for (std::size_t i = 0; i < std::size(HUDWidth); i++)
{
    if (i < 38)
    {
        float mult = (i == 17 || i == 22) ? 0.17343046f : ((i == 30 || i == 33) ? 0.0019500f : WidthMult);
        HUDWidth[i] = mult * ScreenWidthScale * HudWidthScale;
    }
    else
        HUDWidth[i] = 1920.0f * 0.17343046f * ScreenWidthScale * HudWidthScale;
}
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 34]
```diff
@@ -0,0 +1,416 @@
...
+    HUDHeight[24] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[25] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[26] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[27] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[28] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[29] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[30] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[31] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[32] = HeightMult * ScreenHeightScale * HudHeightScale;
+    HUDHeight[33] = HeightMult * ScreenHeightScale * HudHeightScale;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]:
```cpp
for (std::size_t i = 0; i < std::size(HUDHeight); i++)
    HUDHeight[i] = (i == 18 ? 0.002f : HeightMult) * ScreenHeightScale * HudHeightScale;
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 35]
```diff
@@ -0,0 +1,416 @@
...
+    MemPut<BYTE>(0x713B6D, 0x38);
+    MemPut<BYTE>(0x713CFB, 0x38);
+    MemPut<BYTE>(0x713EFC, 0x30);
+    MemPut<BYTE>(0x714004, 0x38);
+
+    HookInstallCall(0x0053D695 - 0x1, (DWORD)UpdateScreenAspectRatio);
+    HookInstallCall(0x0053D7B2 - 0x1, (DWORD)UpdateScreenAspectRatio);
+    HookInstallCall(0x0053D967 - 0x1, (DWORD)UpdateScreenAspectRatio);
+    HookInstallCall(0x0053E771 - 0x1, (DWORD)UpdateScreenAspectRatio);
+    HookInstallCall(0x0053EB1A - 0x1, (DWORD)UpdateScreenAspectRatio);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]:
```cpp
    DWORD callFunc = reinterpret_cast<DWORD>(UpdateScreenAspectRatio);

    HookInstallCall(0x0053D694, callFunc);
    HookInstallCall(0x0053D7B1, callFunc);
    HookInstallCall(0x0053D966, callFunc);
    HookInstallCall(0x0053E770, callFunc);
    HookInstallCall(0x0053EB19, callFunc);
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 36]
```diff
@@ -0,0 +1,416 @@
...
+}
+
+void InstallHUDFixes()
+{
+    uintptr_t crosshairWidthAddresses[10] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 37]
```diff
@@ -0,0 +1,416 @@
...
+        0x58E7CE, 0x58E7F8, 0x58E2FA, 0x58E4ED, 0x58E75B, 0x58E28B, 0x58E2AC, 0x58E2BA, 0x53E472, 0x53E4AE,
+    };
+
+    uintptr_t crosshairHeightAddresses[7] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 38]
```diff
@@ -0,0 +1,416 @@
...
+    {
+        MemPut<float*>(crosshairWidthAddresses[i] + 0x2, &MiscWidth[0]);
+    }
+
+    for (size_t i = 0; i < std::size(crosshairHeightAddresses); i++)
+    {
+        MemPut<float*>(crosshairHeightAddresses[i] + 0x2, &MiscHeight[0]);
+    }
+
+    uintptr_t radarWidthAddresses[23] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 39]
```diff
@@ -0,0 +1,416 @@
...
+        0x58439C,                                                                        // Radar Trace 0
+        0x584434,                                                                        // Radar Trace 0
+        0x58410B,                                                                        // Radar Trace 2
+        0x584190,                                                                        // Radar Trace 2
+        0x584249,                                                                        // Radar Trace 1
+        0x5842E6,                                                                        // Radar Trace 1
+        0x5876D4, 0x58774B, 0x58780A, 0x58788F, 0x58792E, 0x587A1A, 0x587AAA,            // Radar blips
+    };
+
+    uintptr_t radarHeightAddresses[21] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 40]
```diff
@@ -0,0 +1,416 @@
...
+    {
+        MemPut<float*>(radarWidthAddresses[i] + 0x2, &RadarWidth[i]);
+    }
+
+    for (size_t i = 0; i < std::size(radarHeightAddresses); i++)
+    {
+        MemPut<float*>(radarHeightAddresses[i] + 0x2, &RadarHeight[i]);
+    }
+
+    uintptr_t hudWidthAddresses[38] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 41]
```diff
@@ -0,0 +1,416 @@
...
+        0x58AD3A,            // 31 Area names scale
+        0x58AD65,            // 32 Area names ?
+        0x58AE4A,            // 33 Area names x pos
+        0x58C395,            // 34 Subs
+        0x58C41D,            // 35 Subs
+        0x58C4DC,            // 36 Subs
+        0x4E9F30,            // 37 RadioStation
+    };
+
+    uintptr_t hudHeightAddresses[34] = {
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: std::uintptr_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 42]
```diff
@@ -0,0 +1,416 @@
...
+        0x58C4C6,            // 32 Subs
+        0x4E9F1A,            // 33 RadioStation
+    };
+
+    for (size_t i = 0; i < std::size(hudWidthAddresses); i++)
+    {
+        MemPut<float*>(hudWidthAddresses[i] + 0x2, &HUDWidth[i]);
+    }
+
+    for (size_t i = 0; i < std::size(hudHeightAddresses); i++)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: size_t -> std::size_t

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 43]
```diff
@@ -0,0 +1,416 @@
...
+    MemSet((void*)0x50AD79, 0x90, 6);
+    MemPut<float*>(0x50AD59 + 0x2, &CameraWidth[0]);
+    MemPut<float*>(0x51498D + 0x2, &CameraWidth[0]);
+}
+
+void GetMemoryAddresses()
+{
+    ScreenAspectRatio = (float*)0xC3EFA4;
+    ScreenFieldOfView = (float*)0x8D5038;
+}
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: You can remove this function and set the values ​​at the top of the file as static

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 44]
```diff
@@ -0,0 +1,416 @@
...
+    // Second player fix.
+    MemPut<float*>(0x58F9A0 + 0x2, &HUDWidth[38]);             // Weapon icon X
+    MemPut<float*>(0x58F993 + 0x2, &HUDWidth[16]);             // Weapon icon X
+    MemPut<float*>(0x58F972 + 0x2, &HUDHeight[16]);            // Weapon icon Y
+    MemPut<float*>(0x58FA8E + 0x2, &HUDWidth[17]);             // Ammo x
+}
+
+void InstallFieldOfViewFixes()
+{
+    HookInstall(0x6FF410, (DWORD)SetFOV, 5);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Use reinterpret_cast

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 45]
```diff
@@ -0,0 +1,416 @@
...
+    // Aiming point
+    HookInstall(0x51499E, (DWORD)CalculateAimingPoint, 5);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Use reinterpret_cast

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 46]
```diff
@@ -0,0 +1,416 @@
...
+    MemSet((void*)0x50AD79, 0x90, 6);
+    MemPut<float*>(0x50AD59 + 0x2, &CameraWidth[0]);
+    MemPut<float*>(0x51498D + 0x2, &CameraWidth[0]);
+}
+
+void GetMemoryAddresses()
+{
+    ScreenAspectRatio = (float*)0xC3EFA4;
+    ScreenFieldOfView = (float*)0x8D5038;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Use reinterpret_cast

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 47]
```diff
@@ -0,0 +1,416 @@
...
+}
+
+void CMultiplayerSA::InitHooks_WidescreenFix()
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:84]: static?

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 48]
```diff
@@ -0,0 +1,416 @@
...
+}
+
+void InstallFieldOfViewFixes()
+{
+    HookInstall(0x6FF410, (DWORD)SetFOV, 5);
+    // Aiming point
+    HookInstall(0x51499E, (DWORD)CalculateAimingPoint, 5);
+    MemSet((void*)0x50AD79, 0x90, 6);
+    MemPut<float*>(0x50AD59 + 0x2, &CameraWidth[0]);
+    MemPut<float*>(0x51498D + 0x2, &CameraWidth[0]);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: 0x50AD59 + 0x2 = 0x50AD5B
0x51498D + 0x2 = 0x51498F

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 49]
```diff
@@ -0,0 +1,416 @@
...
+    MemPut<float*>(0x58FA8E + 0x2, &HUDWidth[17]);             // Ammo x
+}
+
+void InstallFieldOfViewFixes()
+{
+    HookInstall(0x6FF410, (DWORD)SetFOV, 5);
+    // Aiming point
+    HookInstall(0x51499E, (DWORD)CalculateAimingPoint, 5);
+    MemSet((void*)0x50AD79, 0x90, 6);
+    MemPut<float*>(0x50AD59 + 0x2, &CameraWidth[0]);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Add a comment what address this is. 
``CCamera::Find3rdPersonQuickAimPitch``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 48 above)
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Add a comment what address this is.
``CCamera::Find3rdPersonCamTargetVector``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 50]
```diff
@@ -0,0 +1,416 @@
...
+    MemPut<float*>(0x58F972 + 0x2, &HUDHeight[16]);            // Weapon icon Y
+    MemPut<float*>(0x58FA8E + 0x2, &HUDWidth[17]);             // Ammo x
+}
+
+void InstallFieldOfViewFixes()
+{
+    HookInstall(0x6FF410, (DWORD)SetFOV, 5);
+    // Aiming point
+    HookInstall(0x51499E, (DWORD)CalculateAimingPoint, 5);
+    MemSet((void*)0x50AD79, 0x90, 6);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:79]: Add a comment that skip division by ``CDraw::ms_fAspectRatio``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 51]
```diff
@@ -0,0 +1,416 @@
...
+    for (size_t i = 0; i < std::size(hudHeightAddresses); i++)
+    {
+        MemPut<float*>(hudHeightAddresses[i] + 0x2, &HUDHeight[i]);
+    }
+
+    // Second player fix.
+    MemPut<float*>(0x58F9A0 + 0x2, &HUDWidth[38]);             // Weapon icon X
+    MemPut<float*>(0x58F993 + 0x2, &HUDWidth[16]);             // Weapon icon X
+    MemPut<float*>(0x58F972 + 0x2, &HUDHeight[16]);            // Weapon icon Y
+    MemPut<float*>(0x58FA8E + 0x2, &HUDWidth[17]);             // Ammo x
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Add a comment that these addresses point to ``CHud::DrawPlayerInfo``

0x58F9A0 + 0x2 = 0x58F9A2
0x58F993 + 0x2 = 0x58F995
0x58F972 + 0x2 = 0x58F974
0x58FA8E + 0x2 = 0x58FA90

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 52]
```diff
@@ -0,0 +1,416 @@
...
+    ScreenWidthScale = 640.0f / (*(ScreenAspectRatio) * 448.0f);
+
+    UpdateMiscFixes();
+    UpdateHUDFixes();
+}
+
+void InstallAspectRatioFixes()
+{
+    MemPut<BYTE>(0x745BD1, 0x7D);
+    MemPut<BYTE>(0x745BD9, 0x7C);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Instead of put invalid instructions it is better to use MemSet and set these 2 bytes to 0x90 if you want to avoid the jumps.
image

Also add a comment that it disables jump instructions in ``GetVideoModeList``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 53]
```diff
@@ -0,0 +1,416 @@
...
+
+    // Proportional coronas
+    MemSet((void*)0x6FB2C9, 0x90, 4);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:57]: Add a comment that it skips multiplication by ScreenY in ``CCoronas::Render``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 54]
```diff
@@ -0,0 +1,416 @@
...
+
+    MemPut<BYTE>(0x6FB2BD, 0x6C);
+    MemPut<BYTE>(0x6FB2DC, 0x78);
+    MemPut<BYTE>(0x713BE5, 0x20);
+    MemPut<BYTE>(0x713B6D, 0x38);
+    MemPut<BYTE>(0x713CFB, 0x38);
+    MemPut<BYTE>(0x713EFC, 0x30);
+    MemPut<BYTE>(0x714004, 0x38);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Add comments on what's going on here
```cpp
// Load ScreenY value from the stack
MemPut<BYTE>(0x6FB2BD, 0x6C); // CCoronas::Render
MemPut<BYTE>(0x6FB2DC, 0x78); // CCoronas::Render
MemPut<BYTE>(0x713BE5, 0x20); // CClouds::Render
MemPut<BYTE>(0x713B6D, 0x38); // CClouds::Render
MemPut<BYTE>(0x713CFB, 0x38); // CClouds::Render
MemPut<BYTE>(0x713EFC, 0x30); // CClouds::Render
MemPut<BYTE>(0x714004, 0x38); // CClouds::Render
```

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 30 above)
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: It doesn't have to be an array, it can just be a float

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 45 above)
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: This may cause a crash because the JMP instruction takes 5 bytes, there are only 4 bytes at the specified address, which means that the next instruction will be partially replaced with a random opcode (last byte of the offset)
image

The hook size should be 6 here

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 55]
```diff
@@ -0,0 +1,416 @@
...
+{
+    _asm
+    {
+        fstp    st
+        mov     edx, [ScreenAspectRatio]
+        fmul[edx]
+        mov     edi, [esp + 1Ch + 14h]
+        mov     edx, edi
+        mov     ebx, 5149A6h
+        jmp     ebx
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Replace these instructions with jmp

```cpp
static constexpr std::uintptr_t RETURN_CCamera_Find3rdPersonCamTargetVector = 0x5149A6;
```

```cpp
jmp RETURN_CCamera_Find3rdPersonCamTargetVector
```

Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Additionally, are you sure that this hook works properly? It seems to me that the value at the top of the FPU register may be random here after doing fstp st, unless I missed something

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 56]
```diff
@@ -0,0 +1,416 @@
...
+{
+    return std::round((2.0f * atan(((ar) / (4.0f / 3.0f)) * tan(f / 2.0f * ((float)M_PI / 180.0f)))) * (180.0f / (float)M_PI) * 100.0f) / 100.0f;
+}
+
+void SetFOV(float factor)
+{
+    *ScreenFieldOfView = AdjustFOV(factor, *ScreenAspectRatio);
+}
+
+void __declspec(naked) CalculateAimingPoint()
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: static

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 57]
```diff
@@ -0,0 +1,416 @@
...
+{
+    _asm
+    {
+        fstp    st
+        mov     edx, [ScreenAspectRatio]
+        fmul[edx]
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: space

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 30 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I mean CameraWidth

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 45 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: 0x6FF410 - hook size should be 9
Now this hook breaks the second mov instruction
image

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 49 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I mean aboxe memset

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 48 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: above memset

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 50 above)
Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:79]: above memset

**Comment by ghost** [comment]
Any updates on this? This is a long awaited feature, actually the issue is in the 1.6.1 milestone

**Comment by ghost** [comment]
It would be very interesting if this pull returned

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 28 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: I can make it static

**Comment by ghost** [comment]
I personally like the current "big" hud for 1080p (bad eyes) but I understand that it gets too big on 4k screens. An option where you could scale the hud is impossible?

**Comment by henrymarques** [comment]
Hello! I was very sick last 4 months but I can continue this pr now, I do not remember what I was doing but I got issues with memory addresses as FileEX mentioned, maybe we could separate this into 2 pr since hud changes is ready (at least was before FileEX hud customizations but it seems easy to make it work again)

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 55 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Rendering does not work properly if we ignore the value, I could be wrong, but I guess the value is a (partial?) tan, that is used to calculate where to position crosshair on screen. Without this hook crosshair does not stay in the right place
image

**Comment by henrymarques** [comment]
> I personally like the current "big" hud for 1080p (bad eyes) but I understand that it gets too big on 4k screens. An option where you could scale the hud is impossible?

HUD match aspect ratio option will be kept, so you can use the big HUD simply unchecking that option, isn't the best solution but implementing HUD scale without making things weird needs more thinking

**Comment by Fernando-A-Rocha** [comment]
Nice!
Will you add a client setting to keep the old hud? It should be disabled by default because your fixed version is nicer, imo

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 58]
```diff
@@ -0,0 +1,88 @@
...
+ *****************************************************************************/
+
+#include "StdInc.h"
+
+#ifndef M_PI
+    #define M_PI 3.14159265358979323846
+#endif
+
+// NOTE: This code is based on ThirteenAG's fix, which is licensed under the MIT license.
+static float           CameraWidth = 0.01403292f;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: ``constexpr``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 59]
```diff
@@ -0,0 +1,88 @@
...
+static constexpr float WidthMult = 0.0015625f;
+static constexpr float HeightMult = 0.002232143f;
+static constexpr float SkyMultiFix = 10.0f;
+
+static float* ScreenAspectRatio = reinterpret_cast<float*>(0xC3EFA4);
+static float* ScreenFieldOfView = reinterpret_cast<float*>(0x8D5038);
+
+float AdjustFOV(float f, float ar)
+{
+    return std::round((2.0f * atan(((ar) / (4.0f / 3.0f)) * tan(f / 2.0f * ((float)M_PI / 180.0f)))) * (180.0f / (float)M_PI) * 100.0f) / 100.0f;
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: ``std::atan``, ``std::tan``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 60]
```diff
@@ -0,0 +1,88 @@
...
+    HookInstall(0x6FF410, reinterpret_cast<DWORD>(SetFOV), 9);
+    HookInstall(0x51499E, reinterpret_cast<DWORD>(CalculateAimingPoint), 6);
+
+    // Skips division by CDraw::ms_fAspectRatio
+    MemSet((void*)0x50AD79, 0x90, 6);
+    MemPut<float*>(0x50AD5B, &CameraWidth); // CCamera::Find3rdPersonQuickAimPitch
+    MemPut<float*>(0x51498F, &CameraWidth); // CCamera::Find3rdPersonCamTargetVector
+}
+
+void CMultiplayerSA::InitHooks_WidescreenFix()
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:84]: Mark all functions as ``static``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 61]
```diff
@@ -0,0 +1,88 @@
...
+    MemPut<BYTE>(0x713CFB, 0x38);            // CClouds::Render
+    MemPut<BYTE>(0x713EFC, 0x30);            // CClouds::Render
+    MemPut<BYTE>(0x714004, 0x38);            // CClouds::Render
+}
+
+void InstallFieldOfViewFixes()
+{
+    // Fix sky blurring white in ultrawide screens
+    MemPut<const float*>(0x714843, &SkyMultiFix);
+    MemPut<const float*>(0x714860, &SkyMultiFix);
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:73]: You can change ``const float*`` to ``float*``

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 62]
```diff
@@ -0,0 +1,88 @@
...
+// NOTE: This code is based on ThirteenAG's fix, which is licensed under the MIT license.
+static float           CameraWidth = 0.01403292f;
+static constexpr float WidthMult = 0.0015625f;
+static constexpr float HeightMult = 0.002232143f;
+static constexpr float SkyMultiFix = 10.0f;
+
+static float* ScreenAspectRatio = reinterpret_cast<float*>(0xC3EFA4);
+static float* ScreenFieldOfView = reinterpret_cast<float*>(0x8D5038);
+
+float AdjustFOV(float f, float ar)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: Could you use more user-friendly names instead of 'f' and 'ar'?

File: Client/game_sa/CHudSA.cpp [hunk 63]
```diff
@@ -19,8 +19,8 @@
 
 extern CGameSA* pGame;
 
-char szVehicleName[50] = {'\0'};
-char szZoneName[50] = {'\0'};
+static float radarAltimeterFix = 0.0014625f;                            // Changes altimeter width (and maybe x pos)
+static float aspectRatioMultiplicatorUntouched = 0.0015625f;            // (1 / 640)
```
Comment (FileEX) [inline Client/game_sa/CHudSA.cpp]: ``constexpr``

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/game_sa/CHudSA.cpp (hunk 63 above)
Comment (henrymarques) [reply Client/game_sa/CHudSA.cpp]: forgotten that, thanks for remembering

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 61 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:73]: Changing to `float*` give me a compilation error since `SkyMultiFix` is a constexpr, am I missing something?

Comment (FileEX) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp:73]: You're right, I didn't notice that. In that case, leave it as it is.

**Comment by henrymarques** [comment]
> Nice! Will you add a client setting to keep the old hud? It should be disabled by default because your fixed version is nicer, imo

Yes, just uncheck "HUD match aspect ratio" checkbox on video options, it's checked by default (which means that will be using fixed hud)

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 64]
```diff
@@ -0,0 +1,89 @@
...
+
+// NOTE: This code is based on ThirteenAG's fix, which is licensed under the MIT license.
+
+static constexpr float CameraWidth = 0.01403292f;
+static constexpr float SkyMultiFix = 10.0f;
+
+static float* ScreenAspectRatio = reinterpret_cast<float*>(0xC3EFA4);
+static float* ScreenFieldOfView = reinterpret_cast<float*>(0x8D5038);
+
+static float AdjustFOV(float factor, float aspectRatio)
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: noexcept

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp [hunk 65]
```diff
@@ -0,0 +1,89 @@
...
+ *
+ *****************************************************************************/
+
+#include "StdInc.h"
+
+#ifndef M_PI
+    #define M_PI 3.14159265358979323846
+#endif
+
+// NOTE: This code is based on ThirteenAG's fix, which is licensed under the MIT license.
```
Comment (FileEX) [inline Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: This comment, imo, should be added to the comment section at the top of the file

File: Client/game_sa/CHudSA.cpp [hunk 66]
```diff
@@ -56,23 +56,18 @@ CHudSA::CHudSA()
 {
     InitComponentList();
 
-    // Set the default values
-    m_fSniperCrosshairScale = 210.0f;
+    m_pfAspectRatioMultiplicatorX = (float*)VAR_AspectRatioMultX;
+    m_pfAspectRatioMultiplicatorY = (float*)VAR_AspectRatioMult;
```
Comment (FileEX) [inline Client/game_sa/CHudSA.cpp]: ``reinterpret_cast``

File: Client/game_sa/CHudSA.cpp [hunk 67]
```diff
@@ -19,8 +19,8 @@
 
 extern CGameSA* pGame;
 
-char szVehicleName[50] = {'\0'};
-char szZoneName[50] = {'\0'};
+static float           radarAltimeterFix = 0.0014625f;                            // Changes altimeter width (and maybe x pos)
```
Comment (FileEX) [inline Client/game_sa/CHudSA.cpp:22]: ``constexpr``

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp (hunk 65 above)
Comment (henrymarques) [reply Client/multiplayer_sa/CMultiplayerSA_WidescreenFix.cpp]: yeah I was thinking about that before making the comment

**Review by FileEX — APPROVED** [review]

**Review by Fernando-A-Rocha — APPROVED** [review]
:shipit:

**Review by botder — APPROVED** [review]
