### PR TITLE
Fix onVehicleExit doesn't trigger if pulled out 

### LINKED ISSUE #476: onVehicleExit doesn't trigger if only pulled out of vehicle
**Describe the bug**
If you're being jacked and the player cancels the jack after throwing you out so you've now exited the vehicle however `onVehicleExit` doesn't get triggered.

**To Reproduce**
- Have 2 clients connected.
- `run addEventHandler("onVehicleExit", root, function() outputChatBox("exited") end)`
- Have 1 client pull the other out of car but then press forwards key before entering the vehicle.
- Notice lack of "exited".

**Expected behaviour**
For the event to be triggered.

**MTA Client (please complete the following information):**
unstated

**MTA Server (please complete the following information):**
unstated

**Additional context**
https://bugs.mtasa.com/view.php?id=6494

### PR DESCRIPTION
**Pull request by Proxy-99**
Fixes #476
on case VEHICLE_NOTIFY_JACK_ABORT:
`  if (Packet.GetStartedJacking() == 1)`
call the events

### CODE REVIEW

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 1]
```diff
@@ -3692,6 +3693,23 @@ void CGame::Packet_Vehicle_InOut(CVehicleInOutPacket& Packet)
                                         CVehicleInOutPacket JackedReply(pJacked->GetID(), VehicleID, 0, VEHICLE_NOTIFY_OUT_RETURN);
                                         m_pPlayerManager->BroadcastOnlyJoined(JackedReply);
 
+                                        CLuaArguments Arguments;
+                                        Arguments.PushElement(pPed);                     // player / ped
+                                        Arguments.PushNumber(ucOccupiedSeat);            // seat
+                                        Arguments.PushElement(pJacked);                  // jacked
```
Comment (bum8hj) [inline Server/mods/deathmatch/logic/CGame.cpp]: Arg 1 should be the vehicle the player left (`pVehicle`?)
Arg 3 should be the player who pulled the occupant out of the vehicle (i.e. the jacker `pPed`?)

Comment (bum8hj) [reply Server/mods/deathmatch/logic/CGame.cpp]: Also, I guess that means arg 1 should be `pJacked` when calling `"onVehicleExit"`

Comment (Proxy-99) [reply Server/mods/deathmatch/logic/CGame.cpp]: Fixed

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 2]
```diff
@@ -3692,6 +3693,23 @@ void CGame::Packet_Vehicle_InOut(CVehicleInOutPacket& Packet)
                                         CVehicleInOutPacket JackedReply(pJacked->GetID(), VehicleID, 0, VEHICLE_NOTIFY_OUT_RETURN);
                                         m_pPlayerManager->BroadcastOnlyJoined(JackedReply);
 
+                                        CLuaArguments Arguments;
+                                        Arguments.PushElement(pJacked);                  // player / ped
```
Comment (bum8hj) [inline Server/mods/deathmatch/logic/CGame.cpp]: Since `onPlayerVehicleExit` & `onPedVehicleExit` are being called first, this arg should be `pVehicle`

Sorry, I got confused as well, which is why I edited my last comment.

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 3]
```diff
@@ -3692,6 +3693,23 @@ void CGame::Packet_Vehicle_InOut(CVehicleInOutPacket& Packet)
...
+                                        if (pJacked->IsPlayer())
+                                        {
+                                         pJacked->CallEvent("onPlayerVehicleExit", Arguments);
+                                        }
+                                        else
+                                        {
+                                         pJacked->CallEvent("onPedVehicleExit", Arguments);
+                                        }
+    
+                                        pVehicle->CallEvent("onVehicleExit", Arguments);
```
Comment (bum8hj) [inline Server/mods/deathmatch/logic/CGame.cpp]: Here you probably need to set up new Arguments, with arg 1 being `pJacked`.

**Review by bum8hj — COMMENTED** [review]
Thought I'd try reviewing for the first time since this seemed familiar to me.
I didn't test any of this in-game though.

**Comment by Proxy-99** [comment]
> Thought I'd try reviewing for the first time since this seemed familiar to me. I didn't test any of this in-game though.

you can create a ped then warp it to vehicle to test
```
 local Ped = createPed ( 252, -2410.63159, -598.80121, 132.64844 )
local Vehicle = createVehicle ( 411, -2418.98706, -605.08325, 132.56250 )  

function warpPad()
warpPedIntoVehicle (Ped, Vehicle,0)  
end

addCommandHandler ('warp', warpPad )

addEventHandler ( "onVehicleExit", getRootElement(), function(driver, leftSeat, jackerPlayer)
		 print(getPlayerName(jackerPlayer))			
end)

addEventHandler ( "onPedVehicleExit", getRootElement(), function(theVehicle, leftSeat, jacker)
	print(getPlayerName(jacker))			
end)
```

**Review by bum8hj — APPROVED** [review]
Thanks for the script. I tested it before and after your changes.
**Seems good to me!**

**Review by ghost — APPROVED** [review]
Looks good :shipit:

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 4]
```diff
@@ -3692,6 +3693,29 @@ void CGame::Packet_Vehicle_InOut(CVehicleInOutPacket& Packet)
...
 
+                                        CLuaArguments Arguments;
+                                        Arguments.PushElement(pVehicle);                 // vehicle 
+                                        Arguments.PushNumber(ucOccupiedSeat);            // seat
+                                        Arguments.PushElement(pPed);                     // jacker                                    
+                                        Arguments.PushBoolean(false);                    // forcedByScript
+
+                                        if (pJacked->IsPlayer())
+                                        {
+                                         pJacked->CallEvent("onPlayerVehicleExit", Arguments);
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CGame.cpp]: Please, use the correct indentation here

File: Server/mods/deathmatch/logic/CGame.cpp [hunk 5]
```diff
@@ -3692,6 +3693,29 @@ void CGame::Packet_Vehicle_InOut(CVehicleInOutPacket& Packet)
...
+                                        }
+                                        else
+                                        {
+                                         pJacked->CallEvent("onPedVehicleExit", Arguments);
```
Comment (tederis) [inline Server/mods/deathmatch/logic/CGame.cpp]: Please, use the correct indentation here

**Review by tederis — CHANGES_REQUESTED** [review]
