### PR TITLE
Fix Unicode file path passed in CClientIMG

### LINKED ISSUE #3166: IMG Containers not loading when install directory has special characters
### Describe the bug

IMG Containers not loading when install directory has special characters
Eg:
```
"C:\Játékok\GTA San Andreas"
"D:\Játékok\MTA San Andreas"
```

### Steps to reproduce

Load img container
```
modloader_c.lua:85: Error loading IMG
```

### Version

21190

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #3166

### CODE REVIEW

File: Client/game_sa/CStreamingSA.cpp [hunk 1]
```diff
@@ -402,7 +402,7 @@ unsigned char CStreamingSA::AddArchive(const char* szFilePath)
 
     // Create new stream handler
     const auto streamCreateFlags = *(DWORD*)0x8E3FE0;
-    HANDLE     hFile = CreateFileA(szFilePath, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
+    HANDLE     hFile = CreateFileW(szFilePath, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
```
Comment (botder) [inline Client/game_sa/CStreamingSA.cpp:405]: A `FromUTF8` would have been enough here.

Comment (TheNormalnij) [reply Client/game_sa/CStreamingSA.cpp:405]: Doesn't work for me here:

```c++
unsigned char CStreamingSA::AddArchive(const char* szFilePath) {
//...
CreateFileW(FromUTF8(szFilePath), ...)
//...
}
```

Comment (botder) [reply Client/game_sa/CStreamingSA.cpp:405]: Maybe because FromUTF8 returns a SString and you need a pointer to wchar_t there? Try `*FromUTF8(...)`.

Comment (TheNormalnij) [reply Client/game_sa/CStreamingSA.cpp:405]: FromUTF8 returns a WString

Comment (TheNormalnij) [reply Client/game_sa/CStreamingSA.cpp:405]: Code compiles but FromUTF8 returns a string trimmed to first utf-8 character.

Comment (TheNormalnij) [reply Client/game_sa/CStreamingSA.cpp:405]: btw, i didn't remove `std::wstring utf8Path = SharedUtil::MbUTF8ToUTF16(strFullPath);`
because it breaks std::filesystem api

Comment (botder) [reply Client/game_sa/CStreamingSA.cpp:405]: My point was, that you could probably reduce this pull request just to

image

Comment (TheNormalnij) [reply Client/game_sa/CStreamingSA.cpp:405]: i thought so. But this doesn't work

**Review by Dutchman101 — APPROVED** [review]
We should just merge this as it has quite an impact for a bunch of foreign Windows users not to be able to load with new image functions. We're preparing the next main build, so i want to get this in.

It has been repeatedly code reviewed, and nothing more serious than something to do with style (which has also been sort of dismissed with feedback in the past 24hrs) has come out for objections, so i can merge it and any later improvements could be done in future PR's.
