### PR TITLE
Fix #1596: getBoundKeys still returning table

### LINKED ISSUE #1596: getBoundKeys() doesnt react for unbindKey()
**Describe the bug**
`getBoundKeys()` after calling `unbindKey()` returns outdated value

**To reproduce**
Client-side:
```lua
iprint(1, getBoundKeys("aaaa")) -- 1, false
bindKey("x", "down", "aaaa")
iprint(2, getBoundKeys("aaaa")) -- 2, { x = "down" }
unbindKey("x", "down", "aaaa")
iprint(3, getBoundKeys("aaaa")) -- 3, { x = "down" }
```

**Expected behaviour**
It should return `false` in the last call

**Version**
- server/client version: MTA:SA Server v1.5.7-release-18957 / Multi Theft Auto v1.5.7-release-20582

### PR DESCRIPTION
**Pull request by TeteX1**
Fixed getBoundKeys still returns a table when an unbound command is passed to it.

### CODE REVIEW

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 1]
```diff
@@ -6996,17 +6999,33 @@ bool CStaticFunctionDefinitions::UnbindKey(const char* szKey, const char* szHitS
...
+
         if ((!stricmp(szHitState, "down") || !stricmp(szHitState, "both")) &&
             pKeyBinds->SetCommandActive(szKey, szCommandName, bHitState, NULL, szResource, false, true, true))
         {
             pKeyBinds->SetAllCommandsActive(szResource, false, szCommandName, bHitState, NULL, true, szKey);
+
+            if (pBind)
+            {
+                pKeyBinds->Remove(pBind);
+            }
```
Comment (Lpsd) [inline Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]: Please change formatting to:
```cpp
if (pBind)
    pKeyBinds->Remove(pBind);
```

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp [hunk 2]
```diff
@@ -6996,17 +6999,33 @@ bool CStaticFunctionDefinitions::UnbindKey(const char* szKey, const char* szHitS
...
         bHitState = false;
         if ((!stricmp(szHitState, "up") || !stricmp(szHitState, "both")) &&
             pKeyBinds->SetCommandActive(szKey, szCommandName, bHitState, NULL, szResource, false, true, true))
         {
             pKeyBinds->SetAllCommandsActive(szResource, false, szCommandName, bHitState, NULL, true, szKey);
+
+            if (pBind)
+            {
+                pKeyBinds->Remove(pBind);
+            }
```
Comment (Lpsd) [inline Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]: Same here

**Review by Lpsd — CHANGES_REQUESTED** [review]
Looks good. Please see requested changes on formatting.

File: Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp (hunk 2 above)
Comment (TeteX1) [reply Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp]: Done

**Review by Lpsd — APPROVED** [review]
lgtm
