### PR TITLE
Fix #1357: discord crashes from a4f447ae8047b6d2d65077f093adff69

### LINKED ISSUE #1357: discord crash
**Describe the bug**
Discord crashed the mta

**To reproduce**
i just started mta, release build to test my feature

**Expected behaviour**
Bluescreen

**Screenshots**
image

**Version**
Multi Theft Auto v1.5.7-custom, sources pulled today

**Additional context**
hello

### PR DESCRIPTION
**Pull request by 0x416c69**
This fixes https://github.com/multitheftauto/mtasa-blue/issues/1357
and
https://github.com/multitheftauto/mtasa-blue/issues/1349#issuecomment-610178080

I still need feedback on this @Dutchman101 but I'm guessing this is totally bug-free now because I spent hours evaluating this crashy part and I actually forgot them because my PR was large and merged with a huge delay, this mess up was caused by not having the free time to actually test the code and just fixed it as quick as I could, now I've spent a lot of time reading everything. Hope this addresses all the crashes now.

### CODE REVIEW

File: Client/core/CDiscordManager.cpp [hunk 1]
```diff
@@ -16,7 +16,7 @@
 #define DISCORD_CLIENT_ID 468493322583801867
 #endif
 
-CDiscordManager::CDiscordManager() : m_DiscordCore(nullptr), m_Suicide(false), m_WaitingForServerName(false), m_StoredActivity{}, m_Initialized(false)
+CDiscordManager::CDiscordManager() : m_DiscordCore(nullptr), m_Suicide(false), m_WaitingForServerName(false), m_StoredActivity{}, m_Initialized(false), m_Thread(nullptr)
```
Comment (qaisjp) [inline Client/core/CDiscordManager.cpp]: Please can you put all the defaults in the class declaration?
