### PR TITLE
Fix changing handling max gear to lower than current one crashing client

### LINKED ISSUE #731: setVehicleHandling crash when setting numberOfGears property
**Describe the bug**
When setting the numberOfGears lower than the current gear of the vehicle, Multi Theft Auto crashes. When done server-side, this also seems to crash other players in stream-range of the vehicle.

**To reproduce**
Steps to reproduce the behaviour:
1. [Download hedit](https://community.multitheftauto.com/index.php?p=resources&s=details&id=3716).
2. Start the resource.
3. Get in a car.
4. While driving, press B on your keyboard and quickly adjust the "Number of Gears" option to be lower than your current gear.
5. Game crash.

**Expected behaviour**
I expected the vehicle to downshift to the new maximum gear.

**Version**
Client: 1.5.6
Server: 1.5.6

### PR DESCRIPTION
**Pull request by forkerer**
Fixes #731
Changing vehicle max gear in handling to lower than current gear used by vehicle resulted in infinite loop in CTransmission:CalculateDriveAcceleration (0x6D05E0), i added a simple check to the beginning of the function, that lowers the gear if it's above maximum limit. The game doesn't freeze anymore.
This snippet helps with testing it:
```lua
function veh(client)
	setVehicleHandling(getPedOccupiedVehicle(client), "numberOfGears", 1)
end
addCommandHandler( "veh", veh )
```

### CODE REVIEW

**Comment by Einheit-101** [comment]
This never happened to me and i changed many max gears on my server, strange.

File: Client/multiplayer_sa/CMultiplayerSA.cpp [hunk 1]
```diff
@@ -4069,6 +4074,40 @@ void                        GetVehicleDriveType()
     ucDriveType = static_cast<unsigned char>(pHandlingDriveTypeVeh->m_pVehicle->GetHandlingData()->GetCarDriveType());
 }
 
+static CTransmission* pCurTrasmision = nullptr;
```
Comment (qaisjp) [inline Client/multiplayer_sa/CMultiplayerSA.cpp]:
```suggestion
static CTransmission* pCurTransmission = nullptr;
```

File: Client/multiplayer_sa/CMultiplayerSA.cpp [hunk 2]
```diff
@@ -4069,6 +4074,40 @@ void                        GetVehicleDriveType()
...
+static byte*          pCurGear = nullptr;
+
+void CheckVehicleMaxGear()
+{
+    if (*pCurGear > pCurTrasmision->numOfGears)
```
Comment (qaisjp) [inline Client/multiplayer_sa/CMultiplayerSA.cpp]:
```suggestion
    if (*pCurGear > pCurTransmission->numOfGears)
```

File: Client/multiplayer_sa/CMultiplayerSA.cpp [hunk 3]
```diff
@@ -4069,6 +4074,40 @@ void                        GetVehicleDriveType()
...
+    {
+        *pCurGear = pCurTrasmision->numOfGears;
```
Comment (qaisjp) [inline Client/multiplayer_sa/CMultiplayerSA.cpp]:
```suggestion
        *pCurGear = pCurTransmission->numOfGears;
```

File: Client/multiplayer_sa/CMultiplayerSA.cpp [hunk 4]
```diff
@@ -4069,6 +4074,40 @@ void                        GetVehicleDriveType()
...
+    }
+}
+
+void _declspec(naked) HOOK_Transmission_CalculateDriveAcceleration()
+{
+    _asm
+    {
+        push eax
+        mov pCurTrasmision, ecx
```
Comment (qaisjp) [inline Client/multiplayer_sa/CMultiplayerSA.cpp]:
```suggestion
        mov pCurTransmission, ecx
```

File: Client/game_sa/CVehicleSA.h [hunk 5]
```diff
@@ -315,6 +315,29 @@ struct CTrainFlags
...
+};
+
+struct CTransmission
+{
+    CTransmissionGear gears[6];
+    byte              driveType;
+    byte              engineType;
+    byte              numOfGears;
+    byte              pad;
+    DWORD             flags;
```
Comment (qaisjp) [inline Client/game_sa/CVehicleSA.h]:
```suggestion
    DWORD             handlingFlags;
```

File: Client/game_sa/CVehicleSA.h [hunk 6]
```diff
@@ -315,6 +315,29 @@ struct CTrainFlags
...
+    float             engineAcceleration;
+    float             engineInertia;
+    float             maxVelocity;
+    byte              pad2[4];
+    float             minVelocity;
+    float             curVelocity;
```
Comment (qaisjp) [inline Client/game_sa/CVehicleSA.h]:
```suggestion
    float             curSpeed;
```

Do you know why gta_sa defines this as "speed" rather than "velocity"?

File: Client/game_sa/CVehicleSA.h [hunk 7]
```diff
@@ -315,6 +315,29 @@ struct CTrainFlags
...
+    byte              driveType;
+    byte              engineType;
+    byte              numOfGears;
+    byte              pad;
+    DWORD             flags;
+    float             engineAcceleration;
+    float             engineInertia;
+    float             maxVelocity;
+    byte              pad2[4];
+    float             minVelocity;
```
Comment (qaisjp) [inline Client/game_sa/CVehicleSA.h]:
```suggestion
    float             minGearVelocity;
```

File: Client/game_sa/CVehicleSA.h (hunk 6 above)
Comment (qaisjp) [inline Client/game_sa/CVehicleSA.h]:
```suggestion
    float             curGearVelocity;
```

File: Client/game_sa/CVehicleSA.h [hunk 8]
```diff
@@ -315,6 +315,29 @@ struct CTrainFlags
...
+{
+    CTransmissionGear gears[6];
+    byte              driveType;
+    byte              engineType;
+    byte              numOfGears;
+    byte              pad;
+    DWORD             flags;
+    float             engineAcceleration;
+    float             engineInertia;
+    float             maxVelocity;
```
Comment (qaisjp) [inline Client/game_sa/CVehicleSA.h]:
```suggestion
    float             maxGearVelocity;
```

**Review by qaisjp — APPROVED** [review]
:shipit:
