### PR TITLE
Fix Console (F8) not maintaining position & size when GUI Skin changed

### LINKED ISSUE #2138: Console (F8) set its position when changing MTA: SA Theme (Skin)
Describe the bug
Same in #1969 (which is already fixed)

To reproduce
• Open your MTA;
• Press F8 and adjust the console the way you like (positioning and resizing);
• Change your MTA's theme;
• Check your console.

Expected behaviour
It should be in the same position and size that you have defined.

Screenshots
None

Version
v1.5.8-release-20833

Additional context
None

### PR DESCRIPTION
**Pull request by Fernando-A-Rocha**
Fixes #2138

### CODE REVIEW

File: Client/core/CGUI.cpp [hunk 1]
```diff
@@ -119,12 +129,8 @@ void CLocalGUI::ChangeLocale(const char* szName)
...
         CreateWindows(guiWasLoaded);
-
-        if (m_pConsole != nullptr)
-        {
-            m_pConsole->SetPosition(vPos);
-            m_pConsole->SetSize(vSize);
-        }
+        m_pConsole->SetPosition(consolePos);
+        m_pConsole->SetSize(consoleSize);
     }
```
Comment (TheNormalnij) [inline Client/core/CGUI.cpp:134]: Is it possible that `m_pConsole` is `nullptr` here?

Comment (TracerDS) [reply Client/core/CGUI.cpp:134]: If you call `DestroyWindows` prior then yes

Comment (Fernando-A-Rocha) [reply Client/core/CGUI.cpp:134]: > Is it possible that `m_pConsole` is `nullptr` here?

No because it is created just before.

**Review by TheNormalnij — APPROVED** [review]

**Review by FileEX — APPROVED** [review]

**Review by TracerDS — APPROVED** [review]

**Review by TheNormalnij — APPROVED** [review]
