### PR TITLE
Make kickPlayer accept the Console element

### LINKED ISSUE #1301: kickPlayer does not accept server console as responsiblePlayer parameter
**Describe the bug**
Using kickPlayer with the server console as the responsiblePlayer parameter will return a bad argument warning and will not work. After talking to qaisjp we came to the conclusion that it seems reasonable to accept the server console.

**To reproduce**
Easiest way to reproduce it is using the admin panels run code feature, because it already has acl access:
1. Open admin panel
2. Navigate to Resources -> Execute command
3. Type in or copy `kickPlayer(getPlayerFromName(""),getElementByIndex("console", 0))`
4. Type your in-game name in getPlayerFromName("")
5. Click to run server-sided
5. See error

**Expected behaviour**
The function should accept the server console as the responsiblePlayer argument instead of returning a bad argument warning and the player should be kicked.

**Version**
(343, 474, MTA:SA Server, 1.5.7-9.20358.0, 1.5.7, Release, Windows, 1.5.7-release-20358)

**Additional context**
This error currently stops the votemanager resource from kicking players after a successful kick vote.

### PR DESCRIPTION
**Pull request by qaisjp**
Fixes #1301 

Tested with:

- `run kickPlayer(me)`
- `run kickPlayer(me, getElementByIndex("console", 0))`
- `run kickPlayer(me, "reason")`
- `run kickPlayer(me, "someone", "reason")`
- `run kickPlayer(me, me)`

**Please review only - needs merge commit**

### CODE REVIEW

**Comment by qaisjp** [comment]
[Hm.](https://github.com/multitheftauto/mtasa-blue/runs/646449571?check_suite_focus=true#step:5:1320)

```clang
In file included from ../Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h:15:
../Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h:457:19: error: static_cast from 'CElement *' to 'CConsoleClient *', which are not related by inheritance, is not allowed
        pClient = static_cast<CConsoleClient*>(pElement);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Server/mods/deathmatch/logic/packets/../CGame.h:70:7: note: 'CConsoleClient' is incomplete
class CConsoleClient;
      ^
```

I don't understand. `CConsoleClient.h` has this:

```cpp
class CConsoleClient : public CElement, public CClient
```

Do I need to use `dynamic_cast`? Or is the problem related to the "incomplete type"?

**Comment by qaisjp** [comment]
[Another error now](https://github.com/multitheftauto/mtasa-blue/runs/647870659#step:5:1320)

```
../Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h:457:19: error: assigning to 'CClient *' from incompatible type 'CConsoleClient *'
        pClient = reinterpret_cast<CConsoleClient*>(pElement);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Because I'm doing:

```cpp
CClient* pClient = nullptr;
if (cond)
    pClient = reinterpret_cast<CConsoleClient*>(pElement);
```

where

```cpp
class CConsoleClient : public CElement, public CClient
```

~~Next push will attempt to resolve this by just doing:~~

```cpp
return reinterpret_cast<CClient*>(pElement);
```

That caused a crash (when giving a player or console element).

Next solution is chaining, which is what I wanted to avoid all along:

```cpp
CClient* pClient = nullptr;
if (pElement->GetType() == CElement::PLAYER)
    pClient = static_cast<CClient*>(reinterpret_cast<CPlayer*>(pElement));
else if (pElement->GetType() == CElement::CONSOLE)
    pClient = static_cast<CClient*>(reinterpret_cast<CConsoleClient*>(pElement));

return pClient;
```

**Comment by qaisjp** [comment]
[fuck you clang](https://github.com/multitheftauto/mtasa-blue/runs/647929734?check_suite_focus=true#step:5:1320)

```
../Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h:457:19: error: static_cast from 'CConsoleClient *' to 'CClient *', which are not related by inheritance, is not allowed
        pClient = static_cast<CClient*>(reinterpret_cast<CConsoleClient*>(pElement));
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by qaisjp** [comment]
Ready for review!

File: Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h [hunk 1]
```diff
@@ -437,6 +441,24 @@ CPlayer* UserDataCast(CPlayer*, void* ptr, lua_State*)
...
+CClient* UserDataCast(CClient*, void* ptr, lua_State*)
+{
+    ElementID ID = TO_ELEMENTID(ptr);
+    CElement* pElement = CElementIDs::GetElement(ID);
+    if (!pElement || pElement->IsBeingDeleted() || (pElement->GetType() != CElement::PLAYER && pElement->GetType() != CElement::CONSOLE))
+        return nullptr;
+
+    CClient* pClient = nullptr;
+    if (pElement->GetType() == CElement::PLAYER)
+        pClient = (CClient*)reinterpret_cast<CPlayer*>(pElement);
```
Comment (sbx320) [inline Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h]: The `(CClient*)` cast shouldn't be neccessary, since `CPlayer` inherits from `CClient`

File: Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h [hunk 2]
```diff
@@ -437,6 +441,24 @@ CPlayer* UserDataCast(CPlayer*, void* ptr, lua_State*)
     return (CPlayer*)pElement;
 }
 
+// CClient from CConsoleClient or a CPlayer
+template <class T>
+CClient* UserDataCast(CClient*, void* ptr, lua_State*)
+{
+    ElementID ID = TO_ELEMENTID(ptr);
+    CElement* pElement = CElementIDs::GetElement(ID);
+    if (!pElement || pElement->IsBeingDeleted() || (pElement->GetType() != CElement::PLAYER && pElement->GetType() != CElement::CONSOLE))
```
Comment (sbx320) [inline Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h]: The type check is also handled by the below code

**Review by sbx320 — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h (hunk 1 above)
Comment (qaisjp) [reply Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h]: clang is being a beetch https://github.com/multitheftauto/mtasa-blue/pull/1427#issuecomment-624366147

**Comment by qaisjp** [comment]
[From discord discussion](https://discordapp.com/channels/278474088903606273/366384007535001612/707790106395934750), the CClient type is incomplete, so this push includes that and the solution that failed [here](https://github.com/multitheftauto/mtasa-blue/pull/1427#issuecomment-624366147) no longer fails

**Review by sbx320 — APPROVED** [review]
