### PR TITLE
Fix #472 setElementHealth in onClientPedDamage can cause crash

### LINKED ISSUE #472: setElementHealth in onClientPedDamage can cause crash
**Describe the bug**
setElementHealth inside onClientPedDamage can cause crash.

**To Reproduce**
```lua
function handleDamage(attacker,weapon,bodypart,loss)
    setElementHealth(source,1)
end
addEventHandler("onClientPedDamage",root,handleDamage)
```

**Expected behavior**
No crash.

**MTA Client (please complete the following information):**
v1.5.5-release-13192

**Additional context**
[client_1.5.5-release-13192.0.000_gtasa_00332b2a_5_QPrMb_0100007F_55F3_178_4564C_20180722_2146.dmp](https://bugs.mtasa.com/file_download.php?file_id=1423&type=bug)

From https://bugs.mtasa.com/view.php?id=8926

### PR DESCRIPTION
**Pull request by FileEX**
Fix #472 

This is my next attempt to fix this issue.

- Fixed the crash.
- Fixed the bug where the ped would still die.

The hook in ``CRenderer::RenderEverythingBarRoads`` is necessary because when an entity is frequently re-created, a crash occurs due to ``m_pRwObject`` being **nullptr**. This happens, for example, when shooting a ped with a minigun. In my opinion, this should not cause any synchronization or desynchronization issues, but this will become clear during testing if this PR gets merged.

```lua
function handleDamage(attacker,weapon,bodypart,loss)
    setElementHealth(source,1)
end
addEventHandler("onClientPedDamage",root,handleDamage)
```

I believe this is my last attempt to resolve this issue, as I have run out of ideas for fixing it.

### CODE REVIEW

**Comment by botder** [comment]
I did similiar crash fixes before, but if you're looking for a cleaner solution, using a queue for entity re-creation (caused for example by changing model or respawning) and processing it after the game update, should fix all of these crashes.

**Comment by FileEX** [comment]
> I did similiar crash fixes before, but if you're looking for a cleaner solution, using a queue for entity re-creation (caused for example by changing model or respawning) and processing it after the game update, should fix all of these crashes.

What do you mean by ``processing it after the game update``? These crashes are usually caused by the entity pointer becoming invalid during code execution, so it still needs to be replaced with the correct one using hooks, right?

**Comment by botder** [comment]
> > I did similiar crash fixes before, but if you're looking for a cleaner solution, using a queue for entity re-creation (caused for example by changing model or respawning) and processing it after the game update, should fix all of these crashes.
> 
> What do you mean by `processing it after the game update`? These crashes are usually caused by the entity pointer becoming invalid during code execution, so it still needs to be replaced with the correct one using hooks, right?

Usually these crashes are caused by a hook that triggers an event, which then calls to functions that cause the invalidation. My suggestion is to delay whatever actions these "invalidating" functions do after the game update, where no chunk of code holds a pointer to an invalidated entity.

**Comment by FileEX** [comment]
> > > I did similiar crash fixes before, but if you're looking for a cleaner solution, using a queue for entity re-creation (caused for example by changing model or respawning) and processing it after the game update, should fix all of these crashes.
> > 
> > 
> > What do you mean by `processing it after the game update`? These crashes are usually caused by the entity pointer becoming invalid during code execution, so it still needs to be replaced with the correct one using hooks, right?
> 
> Usually these crashes are caused by a hook that triggers an event, which then calls to functions that cause the invalidation. My suggestion is to delay whatever actions these "invalidating" functions do after the game update, where no chunk of code holds a pointer to an invalidated entity.

I understand what you mean now, but I’m not entirely sure how this could be achieved. The event needs to be triggered at the appropriate moment, as it is now, to allow it to be canceled correctly. So, how could this be done while still preserving the ability to cancel the event? Additionally, how would it even be possible to delay the code executed in a event function?

**Comment by botder** [comment]
> I understand what you mean now, but I’m not entirely sure how this could be achieved. The event needs to be triggered at the appropriate moment, as it is now, to allow it to be canceled correctly. So, how could this be done while still preserving the ability to cancel the event? Additionally, how would it even be possible to delay the code executed in a event function?

I didn't talk about the event callback function, but whatever function the user decides to call (setElementHealth that respawns dead peds), that cause this effect: entity invalidation. And I don't mean we should delay setting the health, but rather the ped recreation.

**Comment by FileEX** [comment]
> > I understand what you mean now, but I’m not entirely sure how this could be achieved. The event needs to be triggered at the appropriate moment, as it is now, to allow it to be canceled correctly. So, how could this be done while still preserving the ability to cancel the event? Additionally, how would it even be possible to delay the code executed in a event function?
> 
> I didn't talk about the event callback function, but whatever function the user decides to call (setElementHealth that respawns dead peds), that cause this effect: entity invalidation. And I don't mean we should delay setting the health, but rather the ped recreation.

Done

**Comment by botder** [comment]
Did you test the code/crash?

**Comment by FileEX** [comment]
> Did you test the code/crash?

Yeah, multiple times even with minigun.

**Comment by botder** [comment]
If this works as intended, then we should use this approach for vehicles and other things too.

File: Client/mods/deathmatch/logic/CClientPed.cpp [hunk 1]
```diff
@@ -4026,6 +4022,20 @@ void CClientPed::ReCreateModel()
     }
 }
 
+void CClientPed::ReCreateGameEntity()
+{
+    if (!m_shouldRecreate)
```
Comment (botder) [inline Client/mods/deathmatch/logic/CClientPed.cpp]: Should we check if `m_pPlayerPed` is non-null here?

**Comment by FileEX** [comment]
> If this works as intended, then we should use this approach for vehicles and other things too.

You're right, but since this PR also touches the ped damage logic, it would be better to do it in a separate PR soon, so that if a revert is needed due to potential synchronization issues, it won't undo other changes.

File: Client/mods/deathmatch/logic/CClientPed.cpp (hunk 1 above)
Comment (FileEX) [reply Client/mods/deathmatch/logic/CClientPed.cpp]: Done

**Review by botder — APPROVED** [review]
