### PR TITLE
Fix isPedOnGround

### LINKED ISSUE #534: isPedOnGround issues
**Describe the bug**
Current isPedOnGround function is very unstable and sometimes doesn't even show the ped is on ground while he is.

**To reproduce**
```lua
function checkDistanceBetweenPlayerAndGround()
local x, y, z = getElementPosition(localPlayer)
local z2 = getGroundPosition(x, y, z)
local dist = getDistanceBetweenPoints3D(x, y, z, x, y, z2)
local ground = tostring(isPedOnGround(localPlayer))
outputChatBox("Distance: "..dist.." IsOnGround: "..ground)
end

crun setTimer(checkDistanceBetweenPlayerAndGround, 1000, 60)

-- Some where I found that returns false when it shouldn't:
crun setElementPosition(localPlayer, -230.175, -1107.408, 16.42)
-- If you don't get it there just move around in that area and eventually you'll see it return false.
```

**Expected behaviour**
Return true when on ground.

**Screenshots**
Here's the video illustrating the problem: http://youtu.be/-qMeC5M4pks

**MTA Client:** 
Unstated.

**MTA Server:** 
Unstated.

**Additional context**
I'm stood in the road and `crun isPedOnGround(localPlayer)` returns false.
If you don't get it first time, keep moving and it will eventually return false when it shouldn't.

Edit: It seems that isPedOnGround fails if your feet aren't actually touching the floor because you're stood on a slope and your feet are slightly off the ground but you're still on the ground though so this function shouldn't be returning false.

From https://bugs.mtasa.com/view.php?id=8378

### PR DESCRIPTION
**Pull request by FileEX**
Fixed #534

Original author: #1603

In addition to fixing the precision of `IsOnGround`, this PR adds a `checkVehicles` argument that allows specifying whether the function should return true if the ped is standing on a vehicle (by default it returns false, as before).

### CODE REVIEW

File: Shared/mods/deathmatch/logic/Utils.cpp
Comment (botder) [inline Shared/mods/deathmatch/logic/Utils.cpp:1]: Don't we already have functions that do these operations?

Comment (FileEX) [reply Shared/mods/deathmatch/logic/Utils.cpp:1]: I didn't find any

File: Shared/mods/deathmatch/logic/Utils.h [hunk 1]
```diff
@@ -336,3 +336,9 @@ void DeletePointersAndClearList(T& elementList)
         delete *iter;
     }
 }
+
+// Comparing floating point numbers
+bool approximatelyEqual(float a, float b, float epsilon = FLOAT_EPSILON);
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.h]: Why do these names start with lower case letters?

File: Shared/mods/deathmatch/logic/Utils.cpp [hunk 2]
```diff
@@ -1102,3 +1102,23 @@ CVector ConvertEulerRotationOrder(const CVector& a_vRotation, eEulerRotationOrde
         return a_vRotation;
     }
 }
+
+bool approximatelyEqual(float a, float b, float epsilon)
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.cpp]: I think they should be marked `noexcept` and `inline`.

File: Shared/mods/deathmatch/logic/Utils.h (hunk 1 above)
Comment (tederis) [inline Shared/mods/deathmatch/logic/Utils.h]: `std::numeric_limits<float>().epsilon()`?

**Comment by ArranTuna** [comment]
I have tested this PR and confirms it fixes isPedOnGround being unreliable, when you were moving on a slope isPedOnGround would flicker between true/false now it stays on true.

This might not seem like an important fix, but it might be the reason why there is significant player movement desync where players can be seen moving forwards and then snapping back when the next puresync packet arrives because IsOnGround is used in puresync so if 1 puresync update sends you as not on ground it can cause this: "they’re flagged as airborne. While flagged airborne, puresync enables velocity-based prediction with little or no friction, so the remote player keeps sliding forward even after their real movement stops"

This desync is brought up a lot by players, so if this does fix it, they'd be very happy. And at the very least it'd fix this function which is also itself quite a useful fix.

File: Shared/mods/deathmatch/logic/Utils.cpp
Comment (botder) [reply Shared/mods/deathmatch/logic/Utils.cpp:1]: I found one function in SharedUtil.Math.h named `IsNearlyEqual`

Comment (FileEX) [reply Shared/mods/deathmatch/logic/Utils.cpp:1]: Yes, but as you can see, this function works differently from those.

File: Shared/mods/deathmatch/logic/Utils.h (hunk 1 above)
Comment (FileEX) [reply Shared/mods/deathmatch/logic/Utils.h]: I copied it from the mentioned PR and didn’t pay attention

**Comment by Dutchman101** [comment]
Nice, this will likely be backported to the next 1.6.0 build that'll also be circulated, so it can be of use before the release of 1.7
