### PR TITLE
Temporary textures cleanup

### LINKED ISSUE #3977: Memory leak, temporary textures not deleting
### Describe the bug

Currently the MTA, when we use the dxDrawImage or dxDrawImageSection functions it will create a temporary texture, however this texture is not being deleted when it is not in use. This results in high memory consumption.

A solution that I believe is viable for this system would be to create a timer that will validate if that texture has not been used for X amount of time. If it is unused, the system will automatically delete the texture, freeing up memory.

### Steps to reproduce

Create an image render using the dxDrawImage or dxDrawImageSection functions. Then disable the render, using the getElementsByType function you can see that the total number of textures has increased, but even if you don't use it, it won't go down. Below is the example code:

```lua
local tick = 0

function render()
    local now = getTickCount()

    if (now - tick >= 1000) then
        return removeEventHandler("onClientRender", root, render)
    end

    dxDrawImage(0, 0, 100, 100, "assets/image.png", 0, 0, 0, tocolor(255, 255, 255, 255))
end

addCommandHandler("textures", function()
    print("Total textures:", #getElementsByType("texture", resourceRoot))
end)

addEventHandler("onClientRender", root, render)
```

### Version

Client: v1.6-release-22894 (Windows 11, 64-bit)
Server: v1.6-release-22894 (Windows 11, 64-bit)

### Additional context

_No response_

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by tederis**
Resolves #3977

### CODE REVIEW

**Review by Fernando-A-Rocha — APPROVED** [review]
Nice system of automatic memory cleaning.

File: Client/mods/deathmatch/logic/CElementDeleter.cpp [hunk 1]
```diff
@@ -19,14 +19,17 @@ CElementDeleter::CElementDeleter()
...
     if (pElement && !IsBeingDeleted(pElement))
     {
         // Before we do anything, fire the on-destroy event
-        CLuaArguments Arguments;
-        pElement->CallEvent("onClientElementDestroy", Arguments, true);
+        if (!silent)
+        {
+            CLuaArguments Arguments;
+            pElement->CallEvent("onClientElementDestroy", Arguments, true);
+        }
```
Comment (TheNormalnij) [inline Client/mods/deathmatch/logic/CElementDeleter.cpp]: We can keep the event trigger to track deleted textures

File: Client/mods/deathmatch/logic/CClientRenderElementManager.cpp [hunk 2]
```diff
@@ -11,6 +11,12 @@
 #include "StdInc.h"
 #include "CClientVectorGraphic.h"
 
+namespace
+{
+    const std::int64_t TEMPORARY_TEXTURES_CLEANUP_THRESHOLD = 10000ll;
+    const std::size_t TEMPORARY_TEXTURES_DELETE_THRESHOLD = 10u;
+}
+
```
Comment (TheNormalnij) [inline Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: Does `namespace` have any effect here?
+ `constexpr`

Comment (tederis) [reply Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: The unnamed namespace in this context is the equivalent to `static` specifier to keep these variables inside a translation unit. Just the modern way of doing it. https://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces

File: Client/mods/deathmatch/logic/CElementDeleter.cpp (hunk 1 above)
Comment (tederis) [reply Client/mods/deathmatch/logic/CElementDeleter.cpp]: These temporary textures are internal entities and I'm not sure if it's a good idea to expose them by calling `onClientElementDestroy`.

File: Client/mods/deathmatch/logic/CClientRenderElementManager.cpp (hunk 2 above)
Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: Could you explain what it means practically? Afaik these variables will be inside this cpp without a namespace too.

Comment (tederis) [reply Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: Example:

one.cpp
`int varA = 10;`

two.cpp
`int varA = 10;`

This will cause a compile time error: `one or more multiply defined symbols found.`
And to prevent it you have to use `static` or an unnamed namespace.

File: Client/mods/deathmatch/logic/CElementDeleter.cpp (hunk 1 above)
Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CElementDeleter.cpp]: It might be good for debug purposes. I think anonymous textures are exposed in the elements tree already.

File: Client/mods/deathmatch/logic/CClientRenderElementManager.cpp (hunk 2 above)
Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: You are right. I didn't have issues with multiply defined symbols before.
I checked it. `constrexpr` also prevents this error without a namespace.

Comment (tederis) [reply Client/mods/deathmatch/logic/CClientRenderElementManager.cpp]: Yeah, okay.

File: Client/mods/deathmatch/logic/CElementDeleter.cpp (hunk 1 above)
Comment (tederis) [reply Client/mods/deathmatch/logic/CElementDeleter.cpp]: I'll look how it works.

**Review by botder — DISMISSED** [review]
LGTM. What do you think about adding a timer to run `CClientRenderElementManager::DoPulse()` only every `N` (milli-)seconds?

**Comment by tederis** [comment]
> LGTM. What do you think about adding a timer to run `CClientRenderElementManager::DoPulse()` only every `N` (milli-)seconds?

Yes, it makes sence.

File: Client/mods/deathmatch/logic/CElementDeleter.cpp (hunk 1 above)
Comment (tederis) [reply Client/mods/deathmatch/logic/CElementDeleter.cpp]: I've allowed onClientElementDestroy events

**Review by TheNormalnij — APPROVED** [review]

**Comment by Dutchman101** [comment]
This is huge, thanks

**Comment by Dutchman101** [comment]
Temporarily reverted, see details at [https://github.com/multitheftauto/mtasa-blue/pull/4031#issuecomment-2664054520](https://github.com/multitheftauto/mtasa-blue/pull/4031#issuecomment-2664054520)
