### PR TITLE
Fix assert when model info is missing

### LINKED ISSUE #3192: Assertion failed! CModelInfoSA.cpp
### Describe the bug

After using engineRequestTXD and engineSetModelTXDID i get randomly this error and game crashing (disconnect or quit game)

image

### Steps to reproduce

Use linked resource from https://github.com/multitheftauto/mtasa-blue/issues/3153

### Version

22195

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #3192

### CODE REVIEW

File: Client/game_sa/CModelInfoSA.cpp [hunk 1]
```diff
@@ -812,10 +812,18 @@ void CModelInfoSA::ResetTextureDictionaryID()
...
-        assert(mi);
-        mi->ResetTextureDictionaryID();
+        if (mi)
+        {
+            mi->ResetTextureDictionaryID();
+        }
+        else
+        {
+            // Model was dealocated. Skip it and remove from list 
+            ms_DefaultTxdIDMap.erase(ms_DefaultTxdIDMap.begin()->first);
```
Comment (botder) [inline Client/game_sa/CModelInfoSA.cpp]:
```suggestion
            // Model was deallocated. Skip and remove it from our list.
            ms_DefaultTxdIDMap.erase(ms_DefaultTxdIDMap.begin());
```

Comment (TheNormalnij) [reply Client/game_sa/CModelInfoSA.cpp]: thx

**Comment by botder** [comment]
Thank you for the quick fix.
