### PR TITLE
Move CEF resources path

### LINKED ISSUE #3715: CEF crashing on latest nightly
### Describe the bug

image

### Steps to reproduce

```lua
local sx, sy = guiGetScreenSize()
local browser = guiCreateBrowser(0, 0, sx, sy, false, false, false)
```

### Version

22721

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #3715

[Chrome issue](https://github.com/chromiumembedded/cef/issues/3749#issuecomment-2278568964)

### CODE REVIEW

File: utils/buildactions/install_cef.lua [hunk 1]
```diff
@@ -6,11 +6,11 @@ premake.modules.install_cef = {}
 local CEF_PATH = "vendor/cef3/cef/"
 local CEF_TEMP_PATH = "vendor/cef3/"
 local CEF_URL_PREFIX = "https://cef-builds.spotifycdn.com/cef_binary_"
-local CEF_URL_SUFFIX = "_windows32_beta_minimal.tar.bz2"
+local CEF_URL_SUFFIX = "_windows32_minimal.tar.bz2"
 
 -- Change here to update CEF version
-local CEF_VERSION = "129.0.4+g9774348+chromium-129.0.6668.29"
-local CEF_HASH = "70b021ac8921de30c31241d85be8ad5abc65adec4283aff726600319f27034b1"
+local CEF_VERSION = "128.4.8+g88b5034+chromium-128.0.6613.114"
```
Comment (tederis) [inline utils/buildactions/install_cef.lua:12]: What is the reason for this downgrade?

Comment (TheNormalnij) [reply utils/buildactions/install_cef.lua:12]: beta to stable

**Review by tederis — APPROVED** [review]
