### PR TITLE
Fix #1942: Ped task bug when fighting near to a vehicle

### LINKED ISSUE #1942: Ped task bug when fighting near to a vehicle (nightly)
**Describe the bug**
When fighting near to a vehicle with the special fighting (RMB+F), the player trying to enter the vehicle.

**To reproduce**
1. Spawn a vehicle near to you (or find one)
2. Start fighting with RMB+F combo
3. The player starts sliding fast to the vehicle

**Expected behaviour**
Normal behavior as before

**Version**
All nightly version affected after **r20739**

### PR DESCRIPTION
**Pull request by Zangomangu**
Fixes #1942 
Avoid local player entering vehicle if doing special attack

### CODE REVIEW

**Review by Dutchman101 — APPROVED** [review]

**Comment by Dutchman101** [comment]
This looks rather simple, we should merge it ASAP to get even more stable builds

File: Client/mods/deathmatch/logic/CClientGame.cpp [hunk 1]
```diff
@@ -1537,6 +1537,13 @@ void CClientGame::DoVehicleInKeyCheck()
             else
             {
                 // Enter
+                // Are we holding the aim_weapon key?	
+                SBindableGTAControl* pBind = g_pCore->GetKeyBinds()->GetBindableFromControl("aim_weapon");	
+                if (pBind && pBind->bState)	
+                {	
+                    // Stop because the player is probably doing special attack
```
Comment (StrixG) [inline Client/mods/deathmatch/logic/CClientGame.cpp]: Please remove extra tabs at the end of lines.

**Review by StrixG — APPROVED** [review]

File: Client/mods/deathmatch/logic/CClientGame.cpp (hunk 1 above)
Comment (Zangomangu) [reply Client/mods/deathmatch/logic/CClientGame.cpp]: Done
