### PR TITLE
Fix `Camper`'s third seat not working

### LINKED ISSUE #1338: The third door of the Camper doesn't work
**Describe the bug**
The Camper is the only vehicle in GTA:SA that has 3 passenger seats. In MTA:SA the 3rd passenger seat doesnt work (for peds & players alike).

**To reproduce**
Run this code:
```lua
function onStart()
        local veh = createVehicle(483, 0, 0, 3)
	local ped = createPed(178, 0, 1, 5)
	warpPedIntoVehicle(ped, veh, 0)
	ped = createPed(178, 0, 1, 5)
	warpPedIntoVehicle(ped, veh, 1)
	ped = createPed(178, 0, 2, 5)
	warpPedIntoVehicle(ped, veh, 2)
	for k,v in pairs(getVehicleOccupants(veh)) do
		outputChatBox(k.." -> "..tostring(v))
	end
end
addEventHandler("onResourceStart", resourcerRoot, onStart)
```
The third passenger will not enter the vehicle. You won't be able to enter either.

**Expected behaviour**
The third door should work just as in GTA:SA singleplayer

**Version**
Any

### PR DESCRIPTION
**Pull request by Xenius97**
Fixes #1338

Now it works as it should, added extra checks to avoid desync issues too & fixes entering (there is a bugged seat behind front passanger, thats fixed too)

https://github.com/user-attachments/assets/53d71b45-a0b8-41a7-bdc3-5409778a2eed

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good

File: Client/mods/deathmatch/logic/CClientPed.cpp [hunk 1]
```diff
@@ -6660,6 +6660,15 @@ bool CClientPed::EnterVehicle(CClientVehicle* pVehicle, bool bPassenger)
         return false;
     }
 
+    // Validate camper seat to avoid multiple occupants && desyncronization
+    if (vehicleModel == VehicleType::VT_CAMPER && uiSeat > 0 && pVehicle->GetOccupant(uiSeat))
+    {
+        #ifdef MTA_DEBUG
+        g_pCore->GetConsole()->Printf("Blocked entering to camper seat %d because it's already occupied.", uiSeat);
+        #endif
```
Comment (FileEX) [inline Client/mods/deathmatch/logic/CClientPed.cpp]: It’s probably not needed anymore.

Comment (Xenius97) [reply Client/mods/deathmatch/logic/CClientPed.cpp]: done, removed

**Review by FileEX — APPROVED** [review]
