### PR TITLE
Fix ACL request detection when using refresh (#1824)

### LINKED ISSUE #1824: Refresh does not work on aclrequest list
**Describe the bug**
/refresh command does not refresh aclrequest list in meta.xml

**To reproduce**
1. create resource with meta.xml content eg.
```xml
<aclrequest>
<right name="function.startResource" access="true" />
<right name="function.stopResource" access="true" />
<right name="function.setElementPosition" access="true" />
</aclrequest>
```
2. type /refresh and `aclrequest list X` where X is your resource name
3. modify aclrequest list, eg remove one right
4. type /refresh and `aclrequest list X` again - nothing changed
5. rename resource X to Y
6. type /refresh and `aclrequest list Y` again - you will see you changes

**Expected behaviour**

**Screenshots**
/

**Version**
1.5.8 release 20698

**Additional context**
/

### PR DESCRIPTION
**Pull request by MohabCodeX**
The issue occurred because the system skipped creating the necessary ACL structures when permissions already existed elsewhere. Additionally, it now ensures consistent cleanup of _temporary_ ACL entries and prevents any permission leakage.
Fixes #1824

### CODE REVIEW

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 1]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+        for (uint uiIndex = 0; true; uiIndex++)
+        {
+            CXMLNode* pNodeRight = pNodeAclRequest->FindSubNode("right", uiIndex);
+            if (!pNodeRight)
+                break;
+
+            std::string strName = pNodeRight->GetAttributeValue("name");
+            std::string strAccess = pNodeRight->GetAttributeValue("access");
+            
+            if (!strFingerprint.empty())
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]: uiIndex > 0

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 2]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+    }
+
+    CXMLNode* pRoot = pMetaFile->GetRootNode();
+    if (!pRoot)
+    {
+        delete pMetaFile;
+        return "";
+    }
+
+    std::string strFingerprint;
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]: std::ostringstream?

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 3]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
 
     return pAclRight->GetAttributeValue("pending") != "";
 }
+
+std::string CResource::CalculateACLRequestFingerprint()
+{
+    std::string strPath;
+    if (!GetFilePath("meta.xml", strPath))
+        return "";
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]:
```cpp
return {};
```

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 4]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+
+    CXMLFile* pMetaFile = g_pServerInterface->GetXML()->CreateXML(strPath.c_str());
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]: std::unique_ptr?

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 5]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+        delete pMetaFile;
+        return "";
+    }
+
+    std::string strFingerprint;
+    CXMLNode* pNodeAclRequest = pRoot->FindSubNode("aclrequest", 0);
+    
+    if (pNodeAclRequest)
+    {
+        for (uint uiIndex = 0; true; uiIndex++)
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]: ``std::uint8_t``

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 6]
```diff
@@ -372,3 +369,53 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+
+    CXMLNode* pRoot = pMetaFile->GetRootNode();
+    if (!pRoot)
+    {
+        delete pMetaFile;
+        return "";
+    }
+
+    std::string strFingerprint;
+    CXMLNode* pNodeAclRequest = pRoot->FindSubNode("aclrequest", 0);
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]: Hungarian notation

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 7]
```diff
@@ -372,3 +369,50 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+std::string CResource::CalculateACLRequestFingerprint()
+{
+    std::string strPath;
+    if (!GetFilePath("meta.xml", strPath))
+        return {};
+
+    std::unique_ptr<CXMLFile> metaFile(g_pServerInterface->GetXML()->CreateXML(strPath.c_str()));
+    if (!metaFile || !metaFile->Parse())
+    {
+        return "";
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]:
```cpp
return {};
```

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 8]
```diff
@@ -372,3 +369,50 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+    }
+
+    CXMLNode* root = metaFile->GetRootNode();
+    if (!root)
+    {
+        return "";
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp]:
```cpp
return {};
```

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 9]
```diff
@@ -372,3 +369,50 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+        {
+            CXMLNode* nodeRight = nodeAclRequest->FindSubNode("right", uiIndex);
+            if (!nodeRight)
+                break;
+
+            std::string strName = nodeRight->GetAttributeValue("name");
+            std::string strAccess = nodeRight->GetAttributeValue("access");
+
+            if (uiIndex > 0)
+                fingerprint << ";";
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp:406]: Add new line please

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp [hunk 10]
```diff
@@ -372,3 +369,50 @@ bool CResource::FindAclRequest(SAclRequest& result)
...
+            fingerprint << strName << ":" << strAccess;
+        }
+    }
+    
+    return fingerprint.str();
+}
+
+bool CResource::HasACLRequestsChanged()
```
Comment (FileEX) [inline Server/mods/deathmatch/logic/CResource.AclRequest.cpp:415]: const?

**Review by FileEX — CHANGES_REQUESTED** [review]

File: Server/mods/deathmatch/logic/CResource.AclRequest.cpp (hunk 10 above)
Comment (MohabCodeX) [reply Server/mods/deathmatch/logic/CResource.AclRequest.cpp:415]: It calls GetFilePath() non-const

**Review by FileEX — APPROVED** [review]
