### PR TITLE
Fix CResourceModelStreamer::FullyReleaseModel crash

### LINKED ISSUE #3710: Game crash when leaving local server on windows
### Describe the bug

Launch a local server on windows, connect it, then disconnect by any method (ban/kick/disconnect ... etc)
The game will exit with a crash.

I previuosly reported this bug and the issue was closed. The problem still exists.

### Steps to reproduce

Get latest version from nightly.
Launch server x64 or x86
Launch client, connect to the localserver
Disconnect from it

### Version

Client & Server: 22714
Both x86 & x64 (Windows)

### Additional context

https://imgur.com/a/TJZZYiM

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TheNormalnij**
Fixes #3710 and https://github.com/multitheftauto/mtasa-resources/issues/551

 CClientModelManager stores a pointer to a deleted CResource object. CClientModel::Deallocate uses dead pointer

### CODE REVIEW

File: Client/mods/deathmatch/logic/CResourceModelStreamer.h [hunk 1]
```diff
@@ -26,5 +26,5 @@ class CResourceModelStreamer
     void FullyReleaseModel(std::uint16_t modelId);
 
 private:
-    std::unordered_map<std::uint16_t, std::uint16_t> m_requestedModels;
+    std::map<std::uint16_t, std::uint16_t> m_requestedModels;
```
Comment (tederis) [inline Client/mods/deathmatch/logic/CResourceModelStreamer.h]: Could you elaborate on how exactly `std::unordered_map` was involved in the crash? And why does `std::map` fix it? I just want to understand the logic.

Comment (TheNormalnij) [reply Client/mods/deathmatch/logic/CResourceModelStreamer.h]: You're right. This fix doesn't changes anything. CClientModelManager stores a pointer to a deleted CResource object. CClientModel::Deallocate uses dead pointer

File: Client/mods/deathmatch/logic/CClientModelManager.cpp [hunk 2]
```diff
@@ -49,6 +49,9 @@ bool CClientModelManager::Remove(const std::shared_ptr<CClientModel>& pModel)
     int modelId = pModel->GetModelID();
     if (m_Models[modelId] != nullptr)
     {
+        CResource* perentResource = m_Models[modelId]->GetParentResource();
```
Comment (TracerDS) [inline Client/mods/deathmatch/logic/CClientModelManager.cpp]: typo

**Review by TracerDS — CHANGES_REQUESTED** [review]

**Review by tederis — APPROVED** [review]
