### PR TITLE
Fix isVehicleOnGround

### LINKED ISSUE #471: isVehicleOnGround sometimes returns false incorrectly
**Describe the bug**
isVehicleOnGround returns false on some vehicles upside down and isVehicleOnGround always returns false for Monsters.

Vehicle IDs: 444, 556, 557

isVehicleOnGround(getPedOccupiedVehicle(localPlayer)) always return false

**To Reproduce**
- Spawn a monster (444, 556 or 557)
- `crun isVehicleOnGround(getPedOccupiedVehicle(localPlayer))`

**Expected behavior**
Should return true

**Screenshots**
image

**MTA Client (please complete the following information):**
unstated

**MTA Server (please complete the following information):**
unstated

**Additional context**
From [mantis 7880](https://bugs.mtasa.com/view.php?id=7880) and [mantis 8672](https://bugs.mtasa.com/view.php?id=8672)

### LINKED ISSUE #2093: isVehicleOnGround does not work after setVehicleHandling
**Describe the bug**
isVehicleOnGround does not work after setVehicleHandling

**To reproduce**
1. enter a vehicle and check **isVehicleOnGround**
2. change **"suspensionLowerLimit"** property to -1
3. reset **"suspensionLowerLimit"** property
4. check again **isVehicleOnGround**
5. do /reconnect and check again with same vehicle model

**Expected behaviour**
**isVehicleOnGorund** need return true after **setVehicleHandling**

**Screenshots**
https://www.youtube.com/watch?v=mLFZEdBOrWs

**Version**
client: v1.5.8-release-20829
server: v1.5.8-release-20829

### PR DESCRIPTION
**Pull request by FileEX**
#### Summary
This PR fixes the isVehicleOnGround function similarly to how #4317 fixed IsPedOnGround.

The current logic is very primitive. It simply checks the distance from the bottom of the bounding box to the ground. That’s why if a vehicle is, for example, lying on its roof, it returns false. It can also return false on slopes, and for a Monster Truck it always returns false, because its wheels aren’t included in the bounding box, which ends at the model’s edge.
image

The fixed isVehicleOnGround function now first does a simple check to see if any wheel is touching the ground. If so, the vehicle is considered on the ground. If not, it performs a basic OOB check and measures the distance to the ground. During testing, I never received a false negative.

#### Motivation
Fixed #471 and #2093

#### Test plan
Tested.
```
Spawn Monster Truck
crun isVehicleOnGround(me.vehicle) -- always false
```

```
Spawn Beagle
crun setVehicleDamageProof(me.vehicle, true)
crun me.vehicle.rotation = Vector3(0, 180, 0)
crun isVehicleOnGround(me.vehicle) -- false
```

```
Spawn some car
crun setVehicleHandling(me.vehicle, 'suspensionLowerLimit', -1)
crun isVehicleOnGround(me.vehicle) -- false
```

#### Checklist

* [x] Your code should follow the [coding guidelines](https://wiki.multitheftauto.com/index.php?title=Coding_guidelines).
* [x] Smaller pull requests are easier to review. If your pull request is beefy, your pull request should be reviewable commit-by-commit.

### CODE REVIEW

File: Client/game_sa/CAutomobileSA.h [hunk 1]
```diff
@@ -53,8 +53,8 @@ class CAutomobileSAInterface : public CVehicleSAInterface
     CBouncingPanelSAInterface m_panels[3];
     CDoorSAInterface          m_swingingChassis;
     CColPointSAInterface      m_wheelColPoint[MAX_WHEELS];
-    float                     m_wheelsDistancesToGround1[4];
-    float                     m_wheelsDistancesToGround2[4];
+    float                     m_wheelRatios[4];  // supension compression, 0 = fully compressed, 1 = fully relaxed
```
Comment (qaisjp) [inline Client/game_sa/CAutomobileSA.h]:
```suggestion
    float                     m_wheelRatios[4];  // suspension compression, 0 = fully compressed, 1 = fully relaxed
```

File: Client/game_sa/CAutomobileSA.cpp [hunk 2]
```diff
@@ -21,6 +21,16 @@ CAutomobileSA::CAutomobileSA(CAutomobileSAInterface* pInterface)
     Init();
 }
 
+bool CAutomobileSA::IsAnyWheelTouchingGround() const
```
Comment (qaisjp) [inline Client/game_sa/CAutomobileSA.cpp:25]:
```suggestion
// Returns true when any wheel is partially compressed (not fully relaxed)
bool CAutomobileSA::IsAnyWheelTouchingGround() const
```

**Review by qaisjp — DISMISSED** [review]
