### PR TITLE
Fix CVector optional arguments - #3738

### LINKED ISSUE #3738: createBuilding optional arguments not handled correctly
### Describe the bug

doing code below will throw error for arg 5 expect vector get none

### Steps to reproduce

`createBuilding ( 3534, -2412.30884, -601.68127, 132.56250)`
or
`createBuilding ( 3534, -2412.30884, -601.68127, 132.56250,90)` without rz or ry gives error

### Version

_No response_

### Additional context

_No response_

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TracerDS**
Resolves #3738, #3778

### CODE REVIEW

File: Shared/sdk/CVector.h [hunk 1]
```diff
@@ -30,13 +30,9 @@ class CVector
     float fY;
     float fZ;
 
-    struct NoInit{};
```
Comment (tederis) [inline Shared/sdk/CVector.h:33]: For what reason was removed NoInit?

File: Shared/sdk/CVector.h [hunk 2]
```diff
@@ -30,13 +30,9 @@ class CVector
...
-
-    CVector(NoInit) {}
-
     constexpr CVector() : fX(0.0f), fY(0.0f), fZ(0.0f) {}
 
-    constexpr CVector(float x, float y, float z) : fX(x), fY(y), fZ(z) {}
+    constexpr CVector(float x, float y = 0, float z = 0) : fX(x), fY(y), fZ(z) {}
```
Comment (tederis) [inline Shared/sdk/CVector.h]: You forgot floating point literals.

File: Shared/sdk/CVector.h (hunk 1 above)
Comment (TracerDS) [reply Shared/sdk/CVector.h:33]: To always have an initialized vector

Comment (tederis) [reply Shared/sdk/CVector.h:33]: Why do you need that?

Comment (TracerDS) [reply Shared/sdk/CVector.h:33]: Just to make sure nothing breaks.
Not initialized vector should be zero regardless. And its only used in client code when doing sync.
If its needed, I will bring it back

Comment (tederis) [reply Shared/sdk/CVector.h:33]: This is the standard practice for the sake of optimization. See how vectors are implemented in Eigen, glm, UE, etc.

Comment (TracerDS) [reply Shared/sdk/CVector.h:33]: Well, its only 3 variables. There should be more constructions that depend on the NoInit rule for the sake of optimalization tbf.

But yeah, should I bring it back?

Comment (tederis) [reply Shared/sdk/CVector.h:33]: **NoInit** can be noticable when you need to create hundreds of 3d vectors within an `std::vector`, for example. This is relevant for 3D rendering part, for example. **NoInit** should be added in other structures in future. It would be better to bring it back, yes.

File: Shared/sdk/CVector.h (hunk 2 above)
Comment (tederis) [inline Shared/sdk/CVector.h]: In addition to previous reviews this constructor should be marked as **explicit** to avoid an implicit convertation from **float** to **CVector**.

**Comment by TheNormalnij** [comment]
Did you forget to push your changes?

**Comment by TracerDS** [comment]
> Did you forget to push your changes?

Indeed, gonna push it in a sec

**Comment by tederis** [comment]
Why did you marked conversations resolved without corresponding changes in the code?

**Comment by TracerDS** [comment]
> Why did you marked conversations resolved without corresponding changes in the code?

What do you mean? I updated the code according to your reviews

**Comment by tederis** [comment]
> > Why did you marked conversations resolved without corresponding changes in the code?
> 
> What do you mean? I updated the code according to your reviews

Hmm, that's strange. I thought I saw the files untouched. I'm sorry.

**Comment by Dutchman101** [comment]
Thanks for addressing all reviews and the fix itself

File: Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h [hunk 3]
```diff
@@ -561,7 +561,7 @@ struct CLuaFunctionParserBase
         else if constexpr (std::is_same_v<T, CVector>)
         {
             if (lua_isnumber(L, index))
-                return {PopUnsafe<float>(L, index), PopUnsafe<float>(L, index), PopUnsafe<float>(L, index)};
+                return CVector(PopUnsafe<float>(L, index), PopUnsafe<float>(L, index), PopUnsafe<float>(L, index));
```
Comment (tederis) [inline Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h:564]: The order of evaluation of arguments is unspecified. That leads to #3895.
